### ISSUE TITLE
Bitonic_Sort

### ISSUE THREAD

**Issue by Rj-coder-iitian** [ahampriyanshu/algo_ds_101#101]
**Submission Title**
Bitonic Sort

**Submission Type**
Algorithm

**Submission Description**
Bitonic mergesort is a parallel algorithm for sorting. It is also used as a construction method for building a sorting network. The algorithm was devised by Ken Batcher.
Inventor: Ken Batcher
Worst complexity: log^2n
Average complexity: log^2n
Best complexity: log^2n
Space complexity: n*log(n)^2
Stable: No

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by Rj-coder-iitian** [comment]
I want to work on this please assign this to me.

**Comment by Mayankjha997** [comment]
I want to work on this in c language please assign me

**Comment by sbhavya18** [comment]
I want to implement this in c++. Kindly assign me this.

**Comment by ahampriyanshu** [comment]
> I want to work on this in c language please assign me

sorry @Mayankjha997 I have just merged a PR implemented in C
You can try a different language.

**Comment by Mayankjha997** [comment]
I want to work on this in python language please assign me

**Comment by mk1107** [comment]
I want to work on this in python or cpp language please assign me

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
