### ISSUE TITLE
Non-recursive Merge sort

### ISSUE THREAD

**Issue by divigarg** [ahampriyanshu/algo_ds_101#1036]
**Submission Title**
MergeSort

**Submission Type**
Algorithm

**Submission Description**
provide a non-recurrsive way to merge sort

**Submission Directory**
Algorithm => Sorting_Algorithms => Merge_sort => non_recursive_merge_sort.c

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by deepampriyadarshi** [comment]
Please assign me this for C++ or PHP

**Comment by neha07kumari** [comment]
Can i work on this issue using java? @divigarg

**Comment by SaloniK17** [comment]
Hii, can you please assign me this issue  in c?
Thank you

**Comment by Vinamrata1086** [comment]
hey! can I work on this issue using c?

**Comment by ashima0699** [comment]
Hey can I work this issue in java or python

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
