### ISSUE TITLE
Add NQueen algorithm in C++

### ISSUE THREAD

**Issue by MananOO12** [ahampriyanshu/algo_ds_101#1039]
**Submission Title**
Bubble Sort/AVL Graph/Vector

**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
Describe the Algo/DS/STL

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by rebelfire888** [comment]
Please assign This to me for C

**Comment by Jaynish007** [comment]
Please Assign this for c++, As I recently learn this algorithm I am very curious to contribute

**Comment by Jaynish007** [comment]
I have learned this algorithm recently and I am very curious to contribute. If possible then please assign it to me for c++

**Comment by YashJain2** [comment]
Please assign the problem to me I will push it within an hour of your response with better backtracking approach

**Comment by rgarg-2711** [comment]
can you please assign it to me

**Comment by sadow984** [comment]
can you please assign it to me for java

**Comment by mgncodes** [comment]
Kindly assign this to me for Python

**Comment by Chetan45s** [comment]
I would like to do it in C++ kindly assign.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
