### ISSUE TITLE
Fibonacci Search

### ISSUE THREAD

**Issue by Mihir2527** [ahampriyanshu/algo_ds_101#104]
**Submission Title**
Fibonacci Search

**Submission Type**
Algorithm

**Submission Description**
Fibonacci search technique is a method of searching a sorted array using a divide and conquer algorithm that narrows down possible locations with the aid of Fibonacci numbers.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ahampriyanshu** [comment]
Sure @Mihir2527 
Just make sure to put the **fibonacci.py** file in seperate folder ``Fibonacci Series`` in ``Mathematics`
And also read the contributing guidelines before making the PR

**Comment by Mihir2527** [comment]
Where can I find the folder Mathematics?

**Comment by Ishaandham19** [comment]
I would like to do Fibonacci Search in C++

**Comment by Mihir2527** [comment]
Would also like to add an implementation in C

**Comment by rushitote** [comment]
@ahampriyanshu 
Can I do this in Golang?

**Comment by rushitote** [comment]
@ahampriyanshu 
Can you please assign me this for Golang?

**Comment by NunoAGoncalves** [comment]
I’d be happy to do a Fibonacci Search in Java.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
