### ISSUE TITLE
Egg Dropping Puzzle

### ISSUE THREAD

**Issue by anuva04** [ahampriyanshu/algo_ds_101#1045]
**Submission Title**
Egg Dropping Puzzle

**Submission Type**
Algorithms/Dynamic_Programming

**Submission Description**
Describe the Algo

**Submission Directory**
Algorithms => Dynamic_Programming => Egg_Drop => Egg_Drop.cpp

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
please assign this to me for python

**Comment by rebelfire888** [comment]
I can write the code in C++ language

**Comment by AdhitiS** [comment]
Please assign this to me for C++ language

**Comment by GerardoUbuntu** [comment]
Please assign this to me for TypeScript

**Comment by rebelfire888** [comment]
Please Assign This To Me For C / C++ Language

**Comment by ashima0699** [comment]
Hey can you assign this issue to me in C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
