### ISSUE TITLE
Segmented Sieve

### ISSUE THREAD

**Issue by Kartikey246** [ahampriyanshu/algo_ds_101#1058]
**Submission Title**
Segmented Sieve

**Submission Type**
Algorithm

**Submission Description**
Sieve of Eratosthenes is an algorithm for finding all the prime numbers in a segment [1;n] using **O(n log log n)** operations

**Submission Directory**
Maths_And_Stats => Number_Theory => Segmented_Sieve=> Segmented_Sieve.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by Kartikey246** [comment]
@ahampriyanshu  i created this issue please assign me this.

**Comment by Kadermiyanyedi** [comment]
Can you assign me for Python please?

**Comment by GarvitBanga** [comment]
Can you assign me this for Java?

**Comment by aakashsoni-cloud** [comment]
can you assign me this issue for c++

**Comment by arjank** [comment]
Can you assign this to me for PHP?

**Comment by Kadermiyanyedi** [comment]
> Can you assign me for Python please?

https://github.com/ahampriyanshu/algo_ds_101/pull/1190

**Comment by Kadermiyanyedi** [comment]
Can you assign this to me for Javascript?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
