### ISSUE TITLE
Brick Sort

### ISSUE THREAD

**Issue by Rj-coder-iitian** [ahampriyanshu/algo_ds_101#106]
**Submission Title**
Brick Sort

**Submission Type**
Algorithm

**Submission Description**
In computing, an odd–even sort or odd–even transposition sort is a relatively simple sorting algorithm, developed originally for use on parallel processors with local interconnections. It is a comparison sort related to bubble sort, with which it shares many characteristics.
Inventor: Habermann
Worst complexity: n^2
Average complexity: n^2
Best complexity: n
Space complexity: 1
Method: Exchanging
Stable: Yes

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by Rj-coder-iitian** [comment]
@ahampriyanshu I want to work on this please assign this to me.

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu I want to work on this please assign this to me.

@Rj-coder-iitian Please mention your preffered language

**Comment by shivamkumar123** [comment]
I want to work on it in C++. Please assign it to me

**Comment by saideepesh000** [comment]
I want to work on it in JavaScript.

**Comment by ArpitDarklord** [comment]
I want to give it a shot in python.Please assign it to me @ahampriyanshu

**Comment by shwhite17** [comment]
assign to me for java @ahampriyanshu

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by cuber485** [comment]
I want to work on it in C. Please assign it to me @ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
