### ISSUE TITLE
Peak Finding Algorithm( 1-D & 2-D matrices)

### ISSUE THREAD

**Issue by YashJain2** [ahampriyanshu/algo_ds_101#1063]
**Submission Title**
Peak Finding Algorithm for a 1-D and 2-D matrix if present.

**Submission Type**
Arrays 1-D and 2-D

**Submission Description**
Algorithm approach with linear time complexity

**Submission Directory**
Algo=>Peak Finding=>1-D/2-D=>1-D_peak.cpp/2-D_peak.cpp

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by crew-guy** [comment]
Hey ! Can I work on the python implementation of this ?
I know how to solve for 1-D array so it'll be pretty cool to try and figure out 2-D array implementation
Also, I know some JS and  am currently also learning C++ so I will try to post solutions in them as well.

**Comment by Manas502** [comment]
Can I work on it in CPP?

**Comment by viveksahu26** [comment]
Hey @YashJain2,i would like to work on jave.. Can you assign me..
