### ISSUE TITLE
Gold Mine Problem

### ISSUE THREAD

**Issue by Mihir2527** [ahampriyanshu/algo_ds_101#108]
The example is the Gold Mine Problem. I'll add it's implementation in Python.

**Comment by ahampriyanshu** [comment]
Great @Mihir2527 
Go ahead ✌🏽

**Comment by Mihir2527** [comment]
Done. Do let me know if there are any problems or changes to be made in it

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by Danish-Mahajan** [comment]
i would like to work on this issue ,using c++

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
