### ISSUE TITLE
Crossword Puzzle

### ISSUE THREAD

**Issue by aroradhruv2308** [ahampriyanshu/algo_ds_101#1091]
**Submission Title**
Crossword Puzzle

**Submission Type**
Algorithms/Backtracking

**Submission Description**
Describe the Algo

**Submission Directory**
Algorithms => Backtracking=> Crossword.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ywalia01** [comment]
Hey, I'd like to work on this

**Comment by aroradhruv2308** [comment]
@ywalia01 I have worked in C++ solution you can contribute in any other language.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
