### ISSUE TITLE
New Submission

### ISSUE THREAD

**Issue by Bihari420** [ahampriyanshu/algo_ds_101#110]
**Submission Title**
Bubble Sort/AVL Graph/Vector

**Submission Type**
Algorithm/Data Structure/STL/Mathematical

**Submission Description**
Describe the Algo/DS/STL

**Contributors**
- [x]  python
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ahampriyanshu** [comment]
@Bihari420 Please describe your proposed Algo/DS
Also read the contributing guidelines.

**Comment by Bihari420** [comment]
Bubble sort is an algorithm that compares the adjacent elements and swaps their positions if they are not in the intended order. The order can be ascending or descending.

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by mk1107** [comment]
I would like to work on this issue. Please assign me. I can use c and python as per your convivence.

**Comment by mk1107** [comment]
I have added cpp code for Fibonacci Search program and optimized bubble sort please accept my PR

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
