### ISSUE TITLE
Min Heap Construction

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1115]
**Submission Title**
Min Heap Construction

**Submission Type**
Algorithms

**Submission Description**
Construct a min heap to find the min value in a Binary Tree. This same concept can be extrapolated to use a max heap to find the max value in a Binary Tree

**Submission Directory**
algo_ds_101 => Algorithms => Tree => Heap => minHeap.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [x] Golang -

**Comment by crew-guy** [comment]
Can I please work on the Python and C++ Implementation of this problem ?

**Comment by Nirali0029** [comment]
I would like to work on python implementation

**Comment by MananOO12** [comment]
#1123 
Added min and max heap in single program.

**Comment by crew-guy** [comment]
Alright cool work ! 
Except you both need to **actually** read the **contribution guidelines**
You cannot create PRs without being assigned to the issue 
I guess you might have to revert your PRs till this issue actually gets approved and assigned by a maintainer
This is what prevents duplication of code in open-source projects

**Comment by SaloniK17** [comment]
hii, can you please assign this issue for c?
Thank you

**Comment by crew-guy** [comment]
I'll start working on c++ implementation now !

**Comment by Nirali0029** [comment]
> Alright cool work !
> Except you both need to **actually** read the **contribution guidelines**
> You cannot create PRs without being assigned to the issue
> I guess you might have to revert your PRs till this issue actually gets approved and assigned by a maintainer
> This is what prevents duplication of code in open-source projects

In non-recursive merge sort #1036 I was assigned that task and some other completed it and it was merged too. So i thought there is a change of rules and it is on first come first serve basis.

**Comment by crew-guy** [comment]
> 
> In non-recursive merge sort #1036 I was assigned that task and some other completed it and it was merged too. So i thought there is a change of rules and it is on first come first merge basis.

No no. Just keep reading contributing guidelines and do your work. Call out if someone tries to break guidelines.
Maintainers should know when you need help

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
