### ISSUE TITLE
Red-Black Tree

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1124]
**Submission Title**
Red-Black Tree

**Submission Type**
Data Structure

**Submission Description**
A red–black tree is a kind of self-balancing binary search tree. Each node stores an extra bit representing color, used to ensure that the tree remains approximately balanced during insertions and deletions.

**Submission Directory**
Data_Structures => Tree => Red_Black_Tree => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rebelfire888** [comment]
Assign it to me in python language

**Comment by AnshMishra2001** [comment]
I can code it in java

**Comment by emerzon1** [comment]
I can do Java

**Comment by ahampriyanshu** [comment]
> I can do Java

Hi @emerzon1 :wave:,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
