### ISSUE TITLE
 Longest Common Subsequence of Two Sequences

### ISSUE THREAD

**Issue by yogesh-kansal** [ahampriyanshu/algo_ds_101#113]
**Submission Title**
 Longest Common Subsequence of Two Sequences

**Submission Type**
Algorithm

**Submission Description**
Problem statement:-Given two sequences 𝐴 = (𝑎1, 𝑎2, . . . , 𝑎𝑛) and 𝐵 = (𝑏1, 𝑏2, . . . , 𝑏𝑚), find the length of their longest
common subsequence.
Problem is based on dynamic programing.I will be solving this issue in c++.
Overall time complexity:-O(m*n) ;where m,n are length of sequences.

**Contributors**
- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by yogesh-kansal** [comment]
I would like to implement this algorithm,please assign it to me.

**Comment by PulkitKhagta** [comment]
I would like to implement this algorithm in C++ please assign this issue to me

**Comment by Renu-code** [comment]
I want to work on this issue.. please assign it to me

**Comment by ahampriyanshu** [comment]
@yogesh-kansal and @Renu-code Please mention your preffered language

**Comment by yogesh-kansal** [comment]
@ahampriyanshu  i would like to implement this in c++

**Comment by Renu-code** [comment]
@ahampriyanshu i would like to implement this in java

**Comment by SoundaryaKhanapur** [comment]
> **Submission Title**
> Longest Common Subsequence of Two Sequences
> 
> **Submission Type**
> Algorithm
> 
> **Submission Description**
> Problem statement:-Given two sequences 𝐴 = (𝑎1, 𝑎2, . . . , 𝑎𝑛) and 𝐵 = (𝑏1, 𝑏2, . . . , 𝑏𝑚), find the length of their longest
> common subsequence.
> Problem is based on dynamic programing.I will be solving this issue in c++.
> Overall time complexity:-O(m*n) ;where m,n are length of sequences.
> 
> **Contributors**
> 
> * [x]   C++ -
> * [x]   C -
> * [ ]   Python -
> * [ ]  Java -
> * [ ]  JavaScript -
> * [ ]  TypeScript -
> * [ ]  Golang -
> * [ ]  Ruby -
> * [ ]  Scala -



> **Submission Title**
> Longest Common Subsequence of Two Sequences
> 
> **Submission Type**
> Algorithm
> 
> **Submission Description**
> Problem statement:-Given two sequences 𝐴 = (𝑎1, 𝑎2, . . . , 𝑎𝑛) and 𝐵 = (𝑏1, 𝑏2, . . . , 𝑏𝑚), find the length of their longest
> common subsequence.
> Problem is based on dynamic programing.I will be solving this issue in c++.
> Overall time complexity:-O(m*n) ;where m,n are length of sequences.
> 
> **Contributors**
> 
> * [x]   C++ -
> * [x]   C -
> * [x]   Python -
> * [ ]  Java -
> * [ ]  JavaScript -
> * [ ]  TypeScript -
> * [ ]  Golang -
> * [ ]  Ruby -
> * [ ]  Scala -

**Comment by SoundaryaKhanapur** [comment]
Longest Common Subsequence of Two Sequences.py

**Comment by hritik5102** [comment]
Hello @ahampriyanshu  I would like to work on this issue 

Follow thing I want to add in you repo

- [x] Longest common sequence using Golang

Thank you :)

**Comment by cuber485** [comment]
i would like to implement this in JAVA.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
