### ISSUE TITLE
Doubly Linkedlist in C#

### ISSUE THREAD

**Issue by Danotsonof** [ahampriyanshu/algo_ds_101#1132]
**Submission Title**
Doubly Linkedlist

**Submission Type**
Data Structure

**Submission Description**
Doubly linked list is a linked data structure that consists of a set of sequentially linked records called nodes. 

**Submission Directory**
Data_Structures=> Linked_List=> Doubly_Linked_List => Doubly_Linked_List.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Danotsonof** [comment]
Kindly assign this to me.

**Comment by crew-guy** [comment]
Can I please implement this in Python ?

**Comment by Nirali0029** [comment]
Please assign this to me for python and c

**Comment by crew-guy** [comment]
#### Can you please assign Python and c++ Implementation to me ?

**Comment by neha07kumari** [comment]
can i do it in C? @ahampriyanshu  @Danotsonof

**Comment by SaloniK17** [comment]
hii, can you please assign  this issue to me    for c?
Thank you

**Comment by ahampriyanshu** [comment]
Hi @SaloniK17 :wave:,
Please opt a different language/issue.

**Comment by Aarti002** [comment]
I have already made a PR implementing doubly linked list with its reversing function too using python. lemme know if there is any issue or not in my file!

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
