### ISSUE TITLE
Topological Sort 

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1140]
**Submission Title**
Topological Sort

**Submission Type**
Algorithm

**Submission Description**
This is one of the **_coding interview favourites_**.
Basically enables topological ordering of a directed graph is a linear ordering of its vertices such that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering.

**Submission Directory**
algo_ds_101 => Algorithms => Graph_Algorithms => Topological Sort => Topological_Sort.ext + README.md

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by chehak123** [comment]
can i work on this issue?

**Comment by Nirali0029** [comment]
I would like to work in python

**Comment by krishnmohan19** [comment]
hey @crew-guy .
plz assign me this in any of java/javascript/c#/c++

**Comment by crew-guy** [comment]
#### I am not in charge of assigning issues. Wait for @ahampriyanshu to come, review this issue and assign accordingly

**Comment by ashima0699** [comment]
Please assign this to me for cpp i can upload a detailed explanation with a clear code.Would be happy to help.

**Comment by ahampriyanshu** [comment]
@chehak123 please mention your preffered language.
@Nirali0029 please opt a different langauge/issue.
@krishnmohan19 go ahead with JS and C#.
@ashima0699 go ahead with C++.

**Comment by chehak123** [comment]
I would like to work on this in c++

**Comment by RitayanDas2** [comment]
hey @ahampriyanshu can u assign the c to me i know the code

**Comment by Vibhanshu3** [comment]
I can provide clean and logical code with proper explanation in Java.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
