### ISSUE TITLE
Merge Sorted Arrays

### ISSUE THREAD

**Issue by aakashsoni-cloud** [ahampriyanshu/algo_ds_101#1144]
**Submission Title**
Merge Sorted Array

**Submission Type**
Data Structure

**Submission Description**
 This is one of the  ***basic array problems***
 Given k sorted arrays of possibly different sizes, the task is to merge them and print the sorted output.

**Submission Directory**
algo_ds_101  => Data_Structures => Arrays => Merge-Sorted-Array.extension

**Contributors**

- [x]  C++ -
- [X]  C -
- [X]  Python -
- [X] Java - 
- [X] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by priyankkumar218** [comment]
Please Assign me this issue in c++

**Comment by aakashsoni-cloud** [comment]
> Please Assign me this issue in c++
@aakashsoni-cloud  assigned @priyankkumar218

**Comment by chehak123** [comment]
please assign to me in c++

**Comment by kartavyashankar** [comment]
Please assign this to me in python

**Comment by krishnmohan19** [comment]
hey @aakashsoni-cloud .plz assign me this in c#/javascript

**Comment by crew-guy** [comment]
Please assign this to me in Python

**Comment by aakashsoni-cloud** [comment]
@crew-guy  you have assigned for python    

> go for the implementation

**Comment by aakashsoni-cloud** [comment]
> hey @aakashsoni-cloud .plz assign me this in c#/javascript/typescript

@krishnmohan19  you have assigned for implementation in javascript

**Comment by elshaek** [comment]
Hi, can I please be assigned for ruby?

**Comment by aakashsoni-cloud** [comment]
@elshaek you have assigned for ruby

**Comment by ashima0699** [comment]
Hey! Can you please assign it to me for C

**Comment by g-jindal2001** [comment]
can u please assign this to me in python?

**Comment by crew-guy** [comment]
> @crew-guy  you have assigned for python    
> 
> > go for the implementation
> 
> 

Yayyy !!! 🙏🏻

**Comment by krishnmohan19** [comment]
> > hey @aakashsoni-cloud .plz assign me this in c#/javascript/typescript
> 
> @krishnmohan19 you have assigned for implementation in javascript

hey @Mr-Vaibhav-Shukla .
i have created my PR. Please review it.
https://github.com/ahampriyanshu/algo_ds_101/pull/1176

**Comment by sau-rav** [comment]
Hey! Can you please assign it to me for C++

**Comment by aakashsoni-cloud** [comment]
@sau-rav  we already have the code in C++ go for another language✌

**Comment by maityankan10** [comment]
can u please assign it to me for C-language

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by maityankan10** [comment]
Hey why did u close it after assigning it to me
