### ISSUE TITLE
Shortest Common Supersequence 

### ISSUE THREAD

**Issue by Swarn10** [ahampriyanshu/algo_ds_101#1152]
**Submission Title**
Shortest Common Supersequence

**Submission Type**
Algorithm

**Submission Description**
This algorithm finds the shortest common supersequence of 2 strings - the shortest string that has both str1 and str2 as subsequences. If 'm' is the length of the first string and 'n' is the length of the second string, then this algo takes O(m * n) time and O(m * n) space. 

**Submission Directory**
Algorithms => Dynamic_Programming => Shortest_Common_Supersequence => shortest_common_supersequence.ext

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Swarn10** [comment]
@ahampriyanshu Please assign this issue to me for C++. Will be happy to help.

**Comment by tasfik007** [comment]
@ahampriyanshu I would like to work on this issue in **python**, It will be great if you can assign it to me,

**Comment by AnshMishra2001** [comment]
Can I work in java,pls ?

**Comment by ashima0699** [comment]
Please assign this to me I'll work on this in C

**Comment by sanjiti0606** [comment]
@ahampriyanshu  Please assign this issue to me for C++

**Comment by IamJayshree** [comment]
Hi, if not assigned to anyone, can i work on C++?

**Comment by aakashsoni-cloud** [comment]
### @Swarn10  please assigned me this in python

**Comment by Mr-Vaibhav-Shukla** [comment]
hi @sanjiti0606 , @IamJayshree , @aakashsoni-cloud  Please opt different language

**Comment by aakashsoni-cloud** [comment]
@Mr-Vaibhav-Shukla  assign me for C#

**Comment by georgettica** [comment]
can I do golang? @Mr-Vaibhav-Shukla

**Comment by Athi223** [comment]
i would like to contribute for javascript solution

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
