### ISSUE TITLE
Adjacent Bit Counts

### ISSUE THREAD

**Issue by shagunarora** [ahampriyanshu/algo_ds_101#1159]
**Submission Title**
Adjacent Bit Counts

**Submission Type**
Algorithm/Dynamic_Programming

**Submission Description**
Describe the Algo

**Submission Directory**
Algorithms => Dynamic_Programming => AdjacentBitCounts.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by Athi223** [comment]
I would like to contribute for javascript

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
