### ISSUE TITLE
 Count Square Sub-matrices with All Ones

### ISSUE THREAD

**Issue by aroradhruv2308** [ahampriyanshu/algo_ds_101#1160]
**Submission Title**
 Count Square Sub-matrices with All Ones

**Submission Type**
 Algorithms/Dynamic_programming

**Submission Description**
Describe the Algo

**Submission Directory**
Algorithms =>Dynamic_programming => Count_Square_Matrices.cpp

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rudransh24** [comment]
Can you assign this to me in C++?

**Comment by g-jindal2001** [comment]
can u assign this to me in python?

**Comment by aroradhruv2308** [comment]
@Rudransh24 Sorry I haven't read your comment before can you please do in C instead of C++.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @aroradhruv2308 Please opt different language

**Comment by aroradhruv2308** [comment]
@Mr-Vaibhav-Shukla can you assign me this in C?

**Comment by aroradhruv2308** [comment]
> @aroradhruv2308 I have just implemented it in C++ and it was assigned to me as well......

No issues I will code it in C.

**Comment by Rudransh24** [comment]
@Mr-Vaibhav-Shukla could you please look into this "Count_Square_Matrices.cpp".

**Comment by namansamra** [comment]
please assign it to me for java

**Comment by Vibhanshu3** [comment]
Can you please assign this to me for Java.

**Comment by ahampriyanshu** [comment]
> Can you please assign this to me for Java.

Hi @Vibhanshu3,
Please opt different issue/language.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
