### ISSUE TITLE
Bubble_Sort in Go, Swift, C# and Ruby

### ISSUE THREAD

**Issue by mhalsubhi** [ahampriyanshu/algo_ds_101#1172]
**Submission Title**
Bubble Sort

**Submission Type**
Algorithm

**Submission Description**
It is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order. The pass through the list is repeated until the list is sorted.

**Submission Directory**
algo_ds_101 => Algorithms => Sorting_Algorithms => Bubble_Sort => Bubble_Sort.extension

**Contributors**

- [x] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by emerzon1** [comment]
I can write the Python, Java, and JavaScript ones.

**Comment by emerzon1** [comment]
Never mind they are done already.

**Comment by SaloniK17** [comment]
hii, can you  please assign this issue for c?
Thank you

**Comment by neha07kumari** [comment]
Can i go for bubble sort in C? @ahampriyanshu  @mhalsubhi

**Comment by illiahonchar** [comment]
may I do bubble sort in Golang?

**Comment by aakashsoni-cloud** [comment]
@ahampriyanshu  @mhalsubhi  can you assigned me for C#

**Comment by LucasNahuel945** [comment]
Can i write Ruby solution?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
