### ISSUE TITLE
Youngest Common Ancestor problem

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1174]
**Submission Title**
Youngest Common Ancestor

**Submission Type**
Algorithm

**Submission Description**
A very fundamental graph algorithm based coding interview problem
Find the youngest common parent node given a set of children nodes in a graph data structure.

**Submission Directory**
algo_ds_101 => Algorithms=> Graph_Algorithms => Youngest_Common_Ancestor => index.ext

**Contributors**

- [x]  C++ -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by riyabhatia26** [comment]
Can I pick this one?

**Comment by ahampriyanshu** [comment]
Hi @riyabhatia26 :wave: ,
Please mention your preffered language.

**Comment by riyabhatia26** [comment]
I'd prefer C++.

**Comment by s2agrahari** [comment]
Hey, could you assign this to me to code in Java?

**Comment by kachus22** [comment]
I'd like to do this in TypeScript

**Comment by Kartik-byte** [comment]
I would like to do this in python .Can you please assign me to it.
Thanks.

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by sanjiti0606** [comment]
Hey, @ahampriyanshu, can you assign me this issue for C++?

**Comment by shockedeel** [comment]
I can take this for swift @ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
