### ISSUE TITLE
Kosaraju's Algorithm | Graphs

### ISSUE THREAD

**Issue by ivinaypathak** [ahampriyanshu/algo_ds_101#1180]
**Submission Title**
- Kosaraju's Algorithm 

**Submission Type**
- Algorithm

**Submission Description**
- Kosaraju's algorithm is used to find strongly connected components in graph.
-  A strongly connected component (SCC) of a directed graph is a maximal strongly connected subgraph.

**Submission Directory**
Algorithm => Graph_Algorithms => Kosaraju's Algorithm => kosaraju_algorithm_strongly_connected_components.cpp

**Contributors**

- [x]  C++ - @ivinaypathak
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by riyabhatia26** [comment]
Can I pick this?

**Comment by shubhamnag14** [comment]
i could like to slove this issue...assign me this issue

**Comment by ivinaypathak** [comment]
I would like to work on this.

**Comment by ahampriyanshu** [comment]
Hi @shubhamnag14 and @riyabhatia26 :wave: , please mention your preffered language.
@ivinaypathak go ahead with C++.

**Comment by abhinav-idle** [comment]
I would like to work on this in python.
Please assign me this.

**Comment by shubhamnag14** [comment]
i would like to work with python

**Comment by shubhamnag14** [comment]
assign me this issue then

**Comment by riyabhatia26** [comment]
Since C++ is taken, I'd like to go for Java.

**Comment by LDiazN** [comment]
I would like to provide a Rust implementation for this. I know is not listed, so i could do it in C# if you prefer.

**Comment by GerardoUbuntu** [comment]
I would like to this in TypeScript

**Comment by RitayanDas2** [comment]
@ahampriyanshu  i can do the c implementation

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
