### ISSUE TITLE
Fibonacci Search C language

### ISSUE THREAD

**Issue by danrockdave** [ahampriyanshu/algo_ds_101#1183]
Fibonacci Search C language

Algorithms/Search_Algorithms/Fibonacci_Search/

**Submission Directory**
Algorithms=> Search_Algorithms=>Fibonacci_Search => fibonacci_search.c

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Aarti002** [comment]
@danrockdave hello sir, can i resolve this issue? i'll try my best!

**Comment by Aarti002** [comment]
It will be better for me to understand if you provide me proper question

**Comment by piratelicorne** [comment]
Hi, I can do this in Javascript :)

**Comment by GorettiRivera** [comment]
Can I work on this and resolve it in python?

**Comment by g-jindal2001** [comment]
can u please assign this to me in c++?

**Comment by edoardottt** [comment]
[Here you can find code in Java, C, Python, PHP, C#](https://www.geeksforgeeks.org/fibonacci-search/)

**Comment by shubhamnag14** [comment]
can i do this job with c and c#

**Comment by RitayanDas2** [comment]
can i do this with python?

**Comment by PrakashAditya17** [comment]
I can do it in java

**Comment by ahampriyanshu** [comment]
> [Here you can find code in Java, C, Python, PHP, C#](https://www.geeksforgeeks.org/fibonacci-search/)

go ahead with php

**Comment by piratelicorne** [comment]
@danrockdave  I finished the exercise with javascript -> PR #1435

**Comment by g-jindal2001** [comment]
@ahampriyanshu  Please Take note of this

@Krishna3102 has opened a pull request of FibonacciSearch.cpp which was assigned to me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
