### ISSUE TITLE
Reverse LinkedList

### ISSUE THREAD

**Issue by jindalsachin** [ahampriyanshu/algo_ds_101#1186]
**Submission Title**
Reverse Linked List

**Submission Type**
Data Structure

**Submission Description**
A linked list is a linear data structure, in which the elements are not stored at contiguous memory locations. The elements in a linked list are linked using pointers . I have implemented reverse of Single Linked List in Java.

**Submission Directory**
Data_Structures => Linked_List => Singly_Linked_List => reverseSingleLinkedList.java

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [.] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by crew-guy** [comment]
Can you please assign this to me for Python ?

**Comment by Kadermiyanyedi** [comment]
Please assign me this issue for C++?

**Comment by ManasUniyal** [comment]
Hey, @ahampriyanshu, can you assign me this issue for C?

**Comment by piratelicorne** [comment]
Hi, I can do this in javascript

**Comment by kachus22** [comment]
I would like to do this in TypeScript

**Comment by sau-rav** [comment]
hey! can you please assign it to me for C++

**Comment by namansamra** [comment]
please assign it to me for Java

**Comment by sanjiti0606** [comment]
Hey, @ahampriyanshu, can you assign this issue to me for C++?

**Comment by geekaditi** [comment]
Hi, Can you assign me this for C++?

**Comment by rhea2801** [comment]
Hi, could you please assign me this for Python?
