### ISSUE TITLE
Fibonacci Numbers

### ISSUE THREAD

**Issue by Mihir2527** [ahampriyanshu/algo_ds_101#120]
**Submission Title**
Fibonacci Numbers

**Submission Type**
Algorithm

**Submission Description**
Dynamic Programming is mainly an optimization over plain recursion. Wherever we see a recursive solution that has repeated calls for same inputs

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Mihir2527** [comment]
Done!. Do let me know if any changes are needed.

**Comment by Raksha25** [comment]
Hi I can work on this in java

**Comment by pratheekpai** [comment]
Can I do this in C++?

**Comment by vikttu** [comment]
Hi! I can do this in javascript, could you assign me for it?

**Comment by Sayantan-world** [comment]
Can I do this on C?

**Comment by swagatikapanda123** [comment]
could you assign me for doing this in java?

**Comment by Vimlesh-Kumar** [comment]
Can you assign me in c++ @ahampriyanshu

**Comment by hanyangl** [comment]
@Mihir2527 could you assign me JavaScript?

**Comment by khushali77** [comment]
Hi, Can I do it in C++?

**Comment by crenspact02** [comment]
Hey. Wanna do this in C++?

**Comment by Mihir2527** [comment]
> Hi I can work on this in java

**Comment by ashish-garg18** [comment]
I would like to work on this in C, C++, Python, Java. Can you assign me for any of these languages.

**Comment by ThomasBiede** [comment]
Can you asign me i want to do it in Go

**Comment by KamalSagar** [comment]
Can you assign me I want to program this in c language

**Comment by TomWia9** [comment]
Hi! Can you assign me? I want to program this in C# language

**Comment by juanmagutierrez** [comment]
Hi! Can I do it in PHP language ?

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:

**Comment by thainapires** [comment]
Hi! Can I do it in python?
