### ISSUE TITLE
Quarkus Code

### ISSUE THREAD

**Issue by gauravsharma97** [ahampriyanshu/algo_ds_101#121]
**Submission Title**
Quarkus Code

**Submission Type**
Algorithm

**Submission Description**
???

**Contributors**
- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
