### ISSUE TITLE
Permutation in C# using Recursion

### ISSUE THREAD

**Issue by Danotsonof** [ahampriyanshu/algo_ds_101#1211]
**Submission Title**
Permutation

**Submission Type**
Algorithm

**Submission Description**
This solution implements a Recursive algorithm. The parameter string is permutated without repeating any. 
E.g. parameter: "123"
result: ["123", "132", "213", "231". "312", "321"]

**Submission Directory**
Algorithm=>Recursion_Algorithm=>Permutation.cs

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Danotsonof** [comment]
kindly assign this to me.

**Comment by g-jindal2001** [comment]
Can u assign this to me in python?

**Comment by abhinav-idle** [comment]
I would like to work on this in java language.
Kindly assign it to me.

**Comment by ajeurkar** [comment]
@Mr-Vaibhav-Shukla @Danotsonof  Let me know if I pick this up for any other language? Also, Can the character in the string repeat?!

**Comment by Rudransh24** [comment]
Can you please assign this to me in C++?

**Comment by Danotsonof** [comment]
> @Mr-Vaibhav-Shukla @Danotsonof Let me know if I pick this up for any other language? Also, Can the character in the string repeat?!

No, it can't repeat.

**Comment by ajeurkar** [comment]
@Mr-Vaibhav-Shukla Kindly, Review the PRs and remove the labels for TS/JS. Thank you for letting us contribute 👍🏼

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
