### ISSUE TITLE
Rotated Sorted Array Search

### ISSUE THREAD

**Issue by sanjiti0606** [ahampriyanshu/algo_ds_101#1217]
**Submission Title**
Rotated Sorted Array Search

**Submission Type**
Algorithm

**Submission Description**
Given an array of integers A, of size N, rotated at some unknown pivot and a target value B to search. If B is found in the array return its index, otherwise, return -1. No duplicate exists in the array. Array A was sorted in non-decreasing order before rotation.

**Submission Directory**
algo_ds_101 => Algorithms => Search_Algorithms => Binary_Search => Rotated-Sorted-Array-Search.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sanjiti0606** [comment]
Please assign me for C++.

**Comment by Abheetarora** [comment]
please assign this to me for java

**Comment by g-jindal2001** [comment]
Please assign this to me in python

**Comment by Rudransh24** [comment]
Could you assign this to me in c/python?

**Comment by mandloiaditi** [comment]
please assign this to me for javascript.

**Comment by ahampriyanshu** [comment]
> Could you assign this to me in c/python?
> @Mr-Vaibhav-Shukla ?

go ahead with C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
