### ISSUE TITLE
Lowest Common Manager 

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1224]
**Submission Title**
Lowest Common Manager 

**Submission Type**
Algorithm

**Submission Description**
This is a coding interview favorite - a **combination of recursion and graph algorithm** (it is a more difficult and intuitively enhanced implementation of Youngest Common Ancestor problem - another famous algo)

**Submission Directory**
algo_ds_101 => Algorithms => Graph_Algorithms => Lowest_Common_Manager => lowest_common_manager.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rhea2801** [comment]
Hi @ahampriyanshu, can you assign me this in C++?

**Comment by Abheetarora** [comment]
hi can you assign this to me for java

**Comment by abhstract** [comment]
@ahampriyanshu could you please assign it to me in c++?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
