### ISSUE TITLE
Invert Binary Tree

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1225]
**Submission Title**
Invert Binary Tree

**Submission Type**
Data Structure

**Submission Description**
A fundamentally important problem when it comes to traversing and manipulating Binary Trees

**Submission Directory**
algo_ds_101 => Data Structures => Tree => Binary Tree => Invert_Binary_Tree => invert_bt.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rhea2801** [comment]
Hi @ahampriyanshu, could you assign this to me in Python?

**Comment by sanjiti0606** [comment]
hey @ahampriyanshu Could I please be assigned for C++?

**Comment by shockedeel** [comment]
@ahampriyanshu I'll take this for swift

**Comment by rileyhgrant** [comment]
Hi @ahampriyanshu could I please be assigned this for Java? Thanks!

**Comment by harlansgs** [comment]
Could I be assigned for Ruby?

**Comment by ahampriyanshu** [comment]
thanks eveyone :v:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
