### ISSUE TITLE
Max_Path_Sum_BST

### ISSUE THREAD

**Issue by crew-guy** [ahampriyanshu/algo_ds_101#1226]
**Submission Title**
Max Path Sum in a BST

**Submission Type**
Data Structure

**Submission Description**
It's a pretty complex BST traversal problem that completely helps understand how BST nodes and branches can be traversed and compared and associated.
A pretty imp fundamental concept of understanding BST traversal lies in this problem

**Submission Directory**
algo_ds_101 => Data Structures => Tree => Binary_Search_Tree => Max_Path_Sum_BST => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rhea2801** [comment]
Hi @ahampriyanshu , could you assign me this in Python?

**Comment by SaimantikaBasu** [comment]
Hi @ahampriyanshu can you assign me this in c++.

**Comment by AyeshW** [comment]
Hey, @ahampriyanshu can you assign me to work on this in Java?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
