### ISSUE TITLE
Wave_Sort

### ISSUE THREAD

**Issue by rhea2801** [ahampriyanshu/algo_ds_101#1227]
**Submission Title**
Wave Sort an Array

**Submission Type**
Algorithm

**Submission Description**
Given an array of integers, sort the array into a wave like array, i.e,
arrange the elements into a sequence such that a1 >= a2 <= a3 >= a4 <= a5 >= a6 and so on.
A pet question of big tech, asked in Google, Adobe, etc. It's a great algo to test how you can solve a seemingly complicated problem creatively with some very fundamental algos.

**Submission Directory**
Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.ext

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by g-jindal2001** [comment]
Please Assign this to me in python

**Comment by rhea2801** [comment]
Please assign this to me in C++

**Comment by Rudransh24** [comment]
Please assign this to me in C.

**Comment by RitayanDas2** [comment]
@ahampriyanshu i can do the c implementation of wave sort

**Comment by ahampriyanshu** [comment]
Hi @RitayanDas2 :wave:,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
