### ISSUE TITLE
Floyd's Cycle Detection Algorithm

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1230]
**Submission Title**
Floyd's Cycle Detection Algorithm

**Submission Type**
Algorithm

**Submission Directory**
Data structures=> Linked_List => Floyd_Cycle_Detection =>  Floyd_Cycle_Detection.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python.

**Comment by hellache** [comment]
Please assign this to me for java @Mr-Vaibhav-Shukla

**Comment by sanjiti0606** [comment]
@ahampriyanshu has C++ already been assigned? Asking because the label isn't present but I see only python and java assigned. If not, please assign me for it.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
