### ISSUE TITLE
2 3 Tree

### ISSUE THREAD

**Issue by rohg007** [ahampriyanshu/algo_ds_101#1233]
**Submission Title**
2 3 Tree

**Submission Type**
Data Structure

**Submission Description**
2 3 Tree is a multiway tree in which there can be either 2 or 3 children. 

**Submission Directory**
Data_Structures => Tree => 23Tree => 23Tree.cpp

**Contributors**

- [X]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by chinmaym07** [comment]
Please assign this to me in C.

**Comment by harlansgs** [comment]
Please assign this to me in Java.

**Comment by ahampriyanshu** [comment]
thanks @rohg007 :v:
