### ISSUE TITLE
3-Way QuickSort(Dutch National Flag)

### ISSUE THREAD

**Issue by immortal-j** [ahampriyanshu/algo_ds_101#1241]
**Submission Title**
 3-Way_Quick_Sort

**Submission Type**
Algorithm/Sorting

**Submission Description**
QuickSort3 is a faster alternative for normal QuickSort. It partitions given data into 3 parts(Works by Dutch National Flag Algorithm) and is faster compared to normal Quicksort for some cases.

**Submission Directory**
 Algorithms=> Sorting_Algorithms => 3-Way_Quick_Sort => 3-Way_Quick_Sort.extension

**Contributors**

- [x]   C++ -
- [ ]   C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by immortal-j** [comment]
Hey i have got C++ code with proper documentation for 3-Way quicksort so can i make a pull request.

**Comment by AnshMishra2001** [comment]
I can code it in c#

**Comment by RitayanDas2** [comment]
i can do it in python so can you assign me?

**Comment by varad64** [comment]
I'd love to do this in Java. Could you please assign me?

**Comment by Rudransh24** [comment]
can you assign this to me in c?

**Comment by varad64** [comment]
> I'd love to do this in Java. Could you please assign me?

@ahampriyanshu

**Comment by duttabhishek32** [comment]
I can implement the algorithm in C, can you assign me this?

**Comment by ahampriyanshu** [comment]
> I can implement the algorithm in C, can you assign me this?

Hi @duttabhishek32,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by varad64** [comment]
> thanks everyone ✌️

@ahampriyanshu Will add the Java code in a minute
