### ISSUE TITLE
Water_Area 

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1246]
**Submission Title**
Water Area

**Submission Type**
Algorithm

**Submission Description**
A fundamentally important 2d matrix traversal and divide and conquer problem.

**Submission Directory**
Algorithms => Dynamic_Programming => Water_Area  => Water_Area.extension + QUESTION.md 

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by PratikSangh** [comment]
### Can you please assign this to me in Python

**Comment by parthchainani** [comment]
can u pls give a link to the question i cant seem to find water area folder in dynamic programming

**Comment by PratikSangh** [comment]
Wait for this issue to get approved and assigned first. Only then can I share the question
@ahampriyanshu kindly review this issue

**Comment by Rudransh24** [comment]
can you assign this to me in c++?

**Comment by PrakashAditya17** [comment]
I can implement this algo in Java, please assign if required.

**Comment by SalmonKing72** [comment]
I'd like to implement this with Ruby please.

**Comment by ahampriyanshu** [comment]
Hi @SalmonKing72 ,
I'm closing this issue but you can still make a PR.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by SalmonKing72** [comment]
> Hi @SalmonKing72 ,
> I'm closing this issue but you can still make a PR.

Thank you! I've made this PR https://github.com/ahampriyanshu/algo_ds_101/pull/1519
