### ISSUE TITLE
Right View of Binary Tree

### ISSUE THREAD

**Issue by sanjiti0606** [ahampriyanshu/algo_ds_101#1247]
**Submission Title**
Right View of Binary Tree

**Submission Type**
Data Structure

**Submission Description**
Given a binary tree A of integers, return an array of integers representing its right view.
Right view of a Binary Tree is a set of nodes visible when the tree is visited from Right side.

**Submission Directory**
 Data Structures => Tree => Binary_Tree => Right_View => Right_View.extension 

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sanjiti0606** [comment]
Hey! Please assign C++ to me.

**Comment by jindalsachin** [comment]
Please assign this to me for Java

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by shockedeel** [comment]
please assign this to me for swift

**Comment by Vibhanshu3** [comment]
Please assign this to me for Java.

**Comment by dhairya-parikh** [comment]
Hey, Can I work on this in Java?

**Comment by harlansgs** [comment]
@ahampriyanshu could I be assigned for Ruby please?

**Comment by ahampriyanshu** [comment]
> Hey, Can I work on this in Java?

Hi @dhairya-parikh ,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
