### ISSUE TITLE
Density of Binary Tree

### ISSUE THREAD

**Issue by jindalsachin** [ahampriyanshu/algo_ds_101#1249]
**Submission Title**
Density of Binary Tree 

**Submission Type**
Data Structure

**Submission Description**
Given a Binary Tree, find density of it by doing one traversal of it.

Density of Binary Tree = Size / Height 

**Submission Directory**
 Data_Structures => Tree => Binary_Tree => Density => Density.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -algo_ds_101 =>algo_ds_101 =>
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by jindalsachin** [comment]
Please assign this to me for C++

**Comment by YatharthVyas** [comment]
Please assign this to me for C

**Comment by sakshidhamne** [comment]
I would like to contribute for Java language

**Comment by shockedeel** [comment]
@ahampriyanshu I can take this for swift

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
