### ISSUE TITLE
Brick Wall

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1254]
**Submission Title**
Brick Wall

**Submission Type**
Data Structure

**Submission Description**
An important question on grasping the fundamentals of hash maps

**Submission Directory**
Data_Structures => Maps_Hash_Dict => Brick_Wall => Brick_Wall.extension + README.md

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by PratikSangh** [comment]
### Could you please assign this to me in C++?

**Comment by Rudransh24** [comment]
can you explain the problem statement please?

**Comment by AnshMishra2001** [comment]
I can code it in java.

**Comment by Rudransh24** [comment]
can you assign this to me in C?

**Comment by TheBlckCat** [comment]
Hi ✌️,
I want to work on this issuein in Python 🐍.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
