### ISSUE TITLE
Remove kth Node From End of Linked List

### ISSUE THREAD

**Issue by rhea2801** [ahampriyanshu/algo_ds_101#1260]
**Submission Title**
Remove kth Node From End of Linked List

**Submission Type**
Data Structure

**Submission Description**
 Given a linked list, remove the Kth node from the end of singly linked list and return its head. A fundamental Linked List problem that helps understand traversal and delete operation on Linked List Nodes. Asked by Amazon, HCL. 

**Submission Directory**
 Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rhea2801** [comment]
^ please assign me this in Python, @ahampriyanshu

**Comment by crew-guy** [comment]
Nice problem. I honestly can't wrap my head around this problem in Python. Make sure you comment the code well for precedent purposes

**Comment by sakshidhamne** [comment]
I'd be glad to contribute for Java

**Comment by meteora2002** [comment]
assign it to me for c++

**Comment by meteora2002** [comment]
@ahampriyanshu

**Comment by SUJATA19-could** [comment]
can i work on it in c or c++!

**Comment by Nandini2901** [comment]
I want to contribute to this in C or C++.
:)

**Comment by bhanuone** [comment]
@ahampriyanshu Please assign this to me in ruby

**Comment by maityankan10** [comment]
assign it to me for c

**Comment by deepharshsri** [comment]
Hey, Can you assign me with java?

**Comment by sid-1207** [comment]
Hey can you assign it to me with C?

**Comment by nehalgupta8501** [comment]
Hey, Can you assign it to me with c++?

**Comment by dhairya-parikh** [comment]
Hey, Can I work on this in Java?

**Comment by baniksudipto** [comment]
Hey , can I contribute on this in Ruby ?

**Comment by ahampriyanshu** [comment]
PRs would be merged on  "First Come, First Serve" basis.
:v:

**Comment by sid-1207** [comment]
@ahampriyanshu I have resolved the issue #1260 in C
The code is in the simplest way possible
thanks

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
