### ISSUE TITLE
Exponential Search

### ISSUE THREAD

**Issue by RgnDunes** [ahampriyanshu/algo_ds_101#1273]
**Submission Title**
Exponential Search

**Submission Type**
Algorithm

**Submission Description**
Exponential Search : We first find the range where the element can be found and then apply binary search in that region. The idea to find the range is to start with subarray size 1, compare its last element with x, then try size 2, then 4 and so on until last element of a subarray is not greater. Once we find an index i (after repeated doubling of i), we know that the element must be present between i/2 and i (Why i/2? because we could not find a greater value in previous iteration)

**Submission Directory**
Algorithms => Search_Algorithms => Exponential_Search => Exponential_Search.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by A-Annan** [comment]
Can I work on it ?

**Comment by bitsandbytes1708** [comment]
@RgnDunes Please don't just add all the labels that don't relate to the issue at all. Please remove the labels that shouldn't be here.

**Comment by RgnDunes** [comment]
> @RgnDunes Please don't just add all the labels that don't relate to the issue at all. Please remove the labels that shouldn't be here.

How to delete labels, I don't have much idea, this is my first Hactoberfest.

**Comment by dwij2212** [comment]
Hi! Can I take up this issue in C++ language?

**Comment by bitsandbytes1708** [comment]
> > @RgnDunes Please don't just add all the labels that don't relate to the issue at all. Please remove the labels that shouldn't be here.
> 
> How to delete labels, I don't have much idea, this is my first Hactoberfest.

That's OK! To the right of the issue, where you see all the labels. There should be a gear. Click on the gear and you will see a menu pop up with all the labels. Un-check the ones that aren't necessary. I would recommend getting rid of all the labels that are a programming language and keeping everything else. 
Here is what the gear should look like next to the labels
![image](https://i.ibb.co/f8BK9wK/Screenshot-2020-10-11-at-2-15-40-PM.png)

**Comment by bitsandbytes1708** [comment]
I just saw that a lot of other issues have a bunch of language tags too. You don't want to include a tag unless the question is actually specifically related to that. If it's just "do it in any programming language" then it does NOT specifically relate to those programming languages and thus shouldn't have that as a label.

**Comment by RgnDunes** [comment]
> > > @RgnDunes Please don't just add all the labels that don't relate to the issue at all. Please remove the labels that shouldn't be here.
> > 
> > 
> > How to delete labels, I don't have much idea, this is my first Hactoberfest.
> 
> That's OK! To the right of the issue, where you see all the labels. There should be a gear. Click on the gear and you will see a menu pop up with all the labels. Un-check the ones that aren't necessary. I would recommend getting rid of all the labels that are a programming language and keeping everything else.
> Here is what the gear should look like next to the labels
> ![image](https://camo.githubusercontent.com/9d62a1c091a31a1a9deafb33ea3ee242f4e613f9/68747470733a2f2f692e6962622e636f2f6638424b39774b2f53637265656e73686f742d323032302d31302d31312d61742d322d31352d34302d504d2e706e67)

No gear option bro,
> [image](https://drive.google.com/file/d/1xQpKCjKrqzomzwy6QjbAFIDqL9ZeTRSp/view?usp=sharing)

**Comment by dhairya-parikh** [comment]
Can you please assign it to me for Java?
@ahampriyanshu

**Comment by NumberPiOso** [comment]
Assign this to me in Python please.

**Comment by AtalKhandelwal** [comment]
@ahampriyanshu I would like to contribute for this issue in C#.Please assign it to me in C#.

**Comment by dwij2212** [comment]
@ahampriyanshu exponential search for C++ has already been completed by someone. Should I implement this in python?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
