### ISSUE TITLE
Check if a binary tree is subtree of another binary tree

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1286]
**Submission Title**
Graph

**Submission Type**
Data structure

**Submission Description**
Given two binary trees, check if the first tree is subtree of the second one

**Submission Directory**
Data_Structures => Tree => Binary_Tree => Subtree_check=> Subtree_check.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rohit-2602** [comment]
@Nirali0029 Can i work on this in Java

**Comment by Nirali0029** [comment]
> @Nirali0029 Can i work on this in Java

@ahampriyanshu  will review and assign you the task :)

**Comment by dwij2212** [comment]
Hi! 
Can I work on this in C++?

**Comment by PrakashAditya17** [comment]
@ahampriyanshu , I can code this in Java. Do assign if required.

**Comment by shwhite17** [comment]
i would like to implement in python and c

**Comment by dhairya-parikh** [comment]
Can I work on this in Java?

**Comment by ahampriyanshu** [comment]
Hi @PrakashAditya17 and @dhairya-parikh :wave: ,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
