### ISSUE TITLE
Sublist_Search

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1295]
**Submission Title**
Sublist_Search

**Submission Type**
Algorithm

**Submission Description**
Sublist Search : We first take first node of second list, start matching the first list from this first node, if whole lists match return true, else break and take first list to the first node again and take second list to its second node. Repeat these steps until any of linked lists becomes empty. If first list becomes empty then list found else not.

**Submission Directory**

Algorithms => Search_Algorithms => Sublist_Search => Sublist_Search.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by reyadkhan** [comment]
I would like to do it in php

**Comment by omarahmed1111** [comment]
I would like to implement this in js

**Comment by Kadermiyanyedi** [comment]
I would like to implement this in C ?

**Comment by shwhite17** [comment]
i would like to implement in c language

**Comment by ahampriyanshu** [comment]
> i would like to implement in c language

Hi @shwhite17,
Please opt a different language/issue.

**Comment by harlansgs** [comment]
Please assign me this for Ruby.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
