### ISSUE TITLE
N Queens | Recursion

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1309]
**Submission Title**
N Queens

**Submission Type**
Algorithm

**Submission Description**
A fundamental problem in grasping the concept of recursion

**Submission Directory**
Algorithms => Recursion_Algorithm => N_Queens => N_Queens.extension + README.md

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by PratikSangh** [comment]
Could you assign this to me in C++?

**Comment by ahampriyanshu** [comment]
Duplicate Issue :warning:

**Comment by errpv78** [comment]
Could you assign this to me in Python?
