### ISSUE TITLE
Koko Eating Bananas | Binary Search

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1310]
**Submission Title**
Koko Eating Bananas

**Submission Type**
Algorithm

**Submission Description**
An important problem in illustrating the application of binary search in optimisation problems

**Submission Directory**
Algorithms => Search_Algorithms => Binary_Search =>Koko_Eating_Bananas => Koko_Eating_Bananas.extension + README.md

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by PratikSangh** [comment]
Could you assign this to me in C++?

**Comment by PratikSangh** [comment]
@ahampriyanshu could you let me know the status of this submission?

**Comment by PrakashAditya17** [comment]
I can solve this question in java. Please assign if its open.

**Comment by abhinav-idle** [comment]
I can solve this in python.
Please assign me this one.

**Comment by dhairya-parikh** [comment]
Can you please assign it to me for Java?
@ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
