### ISSUE TITLE
Check for a closed loop in linked lists

### ISSUE THREAD

**Issue by dwij2212** [ahampriyanshu/algo_ds_101#1311]
**Submission Title**
Check for closed loop using Floyd's cycle algorithm

**Submission Type**
Data Structure

**Submission Description**
Fastest algorithm to detect a closed loop in a linked list. We keep track of 2 pointers and traverse one a bit faster than the other. If these pointers meet again then there is a closed loop.

**Submission Directory**
algo_ds_101 => Data_Structures => LinkedList => detect_cycle.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by dwij2212** [comment]
Hi! Could you assign this issue to me in C++

**Comment by divyagupta-98** [comment]
Could you assign this issue to me in Python.

**Comment by ByteCode-Test** [comment]
PLEASE Assign this to me i'm good at it

**Comment by MohitBhagchandani0601** [comment]
I want to work on this issue in java😊

**Comment by dhairya-parikh** [comment]
Could you assign this issue to me in Java.

**Comment by Druffl3** [comment]
@ahampriyanshu  can you assign this task to me for C# implementation?

**Comment by Suparna99** [comment]
Please assign me this for Ruby

**Comment by baniksudipto** [comment]
Please assign me this for Golang

**Comment by Pancreax** [comment]
Hi! I would like to work on this issue in Swift.

**Comment by matheuslmpereira** [comment]
@dwij2212 @ahampriyanshu  Can I suggest to include kotlin language in the list?

**Comment by maityankan10** [comment]
please assign this to me in C

**Comment by nishtha14-arora** [comment]
Hi, I want to solve this issue in java.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
