### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by arron-tij** [ahampriyanshu/algo_ds_101#1314]
**Submission Title**
Permutations

**Submission Type**
Algorithm

**Submission Description**
Given an array of distinct integers, return all possible permutations.

**Submission Directory**
Algorithms => Backtracking => permutations.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by arron-tij** [comment]
Hi @ahampriyanshu please assign me for C++

**Comment by rahulhambarde300** [comment]
Hi @ahampriyanshu @ please assign me this for  python

**Comment by Rudransh24** [comment]
Assign this to me in C

**Comment by MohitBhagchandani0601** [comment]
I want to work on this issue in java😊

**Comment by Kadermiyanyedi** [comment]
Assign this to me in Javascript please

**Comment by aakashsoni-cloud** [comment]
@ahampriyanshu  assign me for python 
✌

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
