### ISSUE TITLE
Simplify Path | Stack

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1320]
**Submission Title**
Simplify Path

**Submission Type**
Data Structure

**Submission Description**
A fundamental question in illustrating the use of stack data structure

**Submission Directory**
Data_Structures=> Stacks => Simplify_Path => Simplify_Path.extension
Data_Structures=> Stacks => Simplify_Path => QUESTION.md

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by raghavrammohan** [comment]
I would like to work on this in Java. Can I be assigned with this ?

**Comment by PratikSangh** [comment]
Could you assign this to me in C++?

**Comment by aroradhruv2308** [comment]
pls assign this to me in python

**Comment by PratikSangh** [comment]
@ahampriyanshu could you look into this?

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu could you look into this?

Sorry for the delay.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
