### ISSUE TITLE
Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by shagunarora** [ahampriyanshu/algo_ds_101#1327]
**Submission Title**
Lowest Common Ancestor of a Binary Tree

**Submission Type**
Algorithm

**Submission Description**
Describe the Algo

**Submission Directory**
Algorithms => Tree_Algorithms => LCA.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by shagunarora** [comment]
Hey Please assign me this issue in c++

**Comment by aroradhruv2308** [comment]
please assign this issue to me in python

**Comment by raghavrammohan** [comment]
Please assign me to java

**Comment by edoardottt** [comment]
I can do it in C#

**Comment by dhairya-parikh** [comment]
Can you please assign it to me for C?
@ahampriyanshu

**Comment by Aarti002** [comment]
Hey @ahampriyanshu can i do this in python please assign me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
