### ISSUE TITLE
Check if a Binary Tree has duplicate values

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1330]
**Submission Title**
Check if a Binary Tree  has duplicate values

**Submission Type**
Data Structure

**Submission Directory**
Data_Structures => Tree => Binary_Tree => Duplicate_values =>Duplicate_values.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by arron-tij** [comment]
Please assign C++ to me @ahampriyanshu

**Comment by jindalsachin** [comment]
please assign me this for java

**Comment by edoardottt** [comment]
I can do it in C#

**Comment by dhairya-parikh** [comment]
Can you please assign it to me for C?
@ahampriyanshu

**Comment by VishwaroopShah** [comment]
I will do it in C kindly assign it to me.

**Comment by harlansgs** [comment]
Please assign me this for Ruby.

**Comment by ahampriyanshu** [comment]
> I will do it in C kindly assign it to me.

Please opt a different language/issue.

**Comment by edoardottt** [comment]
Done. Waiting for pull request acceptance

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
