### ISSUE TITLE
Serialize a Binary Tree

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1331]
**Submission Title**
Serialize and Deserialize a Binary Tree

**Submission Type**
Data structure

**Submission Directory**
Data_Structures => Tree => Binary_Tree =Serialize=>Serialize.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by baniksudipto** [comment]
Hi, Could you assign this issue to me in Ruby ?

**Comment by sagar-monga** [comment]
Hello, could you assign this to me in C++?

**Comment by dhairya-parikh** [comment]
Hello, could you assign this to me in Java?

**Comment by kugiyasan** [comment]
Could you assign python for me please?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
