### ISSUE TITLE
Deserialize a binary tree

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1332]
**Submission Title**
Deserialize a binary tree

**Submission Type**
Data structure

**Submission Directory**
Data_Structures => Tree => Binary_Tree => Deserialize=>Deserialize.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by baniksudipto** [comment]
Hi, Could you assign this issue to me in Ruby ?

**Comment by demonslayer99** [comment]
assign this to me for c++

**Comment by dhairya-parikh** [comment]
Hello, could you assign this to me in Java?

**Comment by demonslayer99** [comment]
my code is not working :( sorry ill take up some other issue.

**Comment by ajitcool19** [comment]
Hello could you please assign this to me in python

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
