### ISSUE TITLE
Implementation of 0/1 Knapsack using Branch and Bound

### ISSUE THREAD

**Issue by aakashsoni-cloud** [ahampriyanshu/algo_ds_101#1335]
**Submission Title**
KnapSack 

**Submission Type**
Algorithm

**Submission Description**
Implement the 0/1 Knapsack using Branch and Bound algorithm

**Submission Directory**
algo_ds_101 => Algorithm => Dynamic_Programming => Branch_And_Bound => 0/1_KnapSack.extesion

**Contributors**
- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by demonslayer99** [comment]
assign this to me for c++

**Comment by 0x6f736f646f** [comment]
Hey @ahampriyanshu please assign me for python

**Comment by Amanj2000** [comment]
I want to work on this in Java.
