### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by arron-tij** [ahampriyanshu/algo_ds_101#1337]
**Submission Title**
Longest Palindromic Substring (LPS)

**Submission Type**
Algorithm

**Submission Description**
Given a string S, find the longest palindromic substring in S. In case of conflict, return the substring which occurs first ( with the least starting index ).

**Submission Directory**
Algorithms => String_Algorithms => LPS => longest_palindromic_substring.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by arron-tij** [comment]
Hey @ahampriyanshu please assign me for C++

**Comment by harshitashankar** [comment]
Please assign this to me for Java.

**Comment by spidergon** [comment]
Hey @ahampriyanshu please assign me for JavaScript.

**Comment by thebhushanmhatre** [comment]
Hi @ahampriyanshu, 
Done for Ruby. Please review the PR.

**Comment by 0x6f736f646f** [comment]
Hey @ahampriyanshu please assign me for Python

**Comment by RgnDunes** [comment]
Hey @ahampriyanshu can you please assign this problem to be so I can solve it in Python.

**Comment by spidergon** [comment]
Hey @ahampriyanshu please review the PR for JavaScript #1355

**Comment by dhairya-parikh** [comment]
Can you please assign it to me for C?
@ahampriyanshu

**Comment by harlansgs** [comment]
Please assign me this for Ruby.

**Comment by 0x6f736f646f** [comment]
@harlansgs Ruby has already been implemented and merged checkout pull request number #1348

**Comment by harlansgs** [comment]
Sorry about that. I got confused since the tag was still there for it.

**Comment by maityankan10** [comment]
assign this to me in c

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
