### ISSUE TITLE
Symmetric Binary Tree

### ISSUE THREAD

**Issue by jindalsachin** [ahampriyanshu/algo_ds_101#1339]
**Submission Title**
Given a binary tree, check whether it is a mirror of itself.

**Submission Type**
Data Structure

**Submission Description**
We will check if a Binary Tree is mirror image of itself and have the symmetry

**Submission Directory**
algo_ds_101 => Data_Structures =>  Tree => Binary_Tree => SymmetryBTree.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by jindalsachin** [comment]
Please assign me this issue for Java

**Comment by arron-tij** [comment]
Hi @ahampriyanshu please assign C++ to me.

**Comment by 0x6f736f646f** [comment]
Please assign me this issue for Python

**Comment by Isha2208** [comment]
Hey, @ahampriyanshu, please assign me the issue for c language

**Comment by manishita24** [comment]
assign me this for c#

**Comment by aolaria** [comment]
Hi, Please assign me this issue for Golang.

**Comment by Suparna99** [comment]
Hi, please assign me this for JavaScript.

**Comment by rishinpandit09** [comment]
hi, pls issue me this for java

**Comment by ahampriyanshu** [comment]
> hi, pls issue me this for java

Please opt a different language/issue.

**Comment by rishinpandit09** [comment]
Can do any other data structure algorithm in java

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
