### ISSUE TITLE
Segment Tree

### ISSUE THREAD

**Issue by ashutoshkumar6** [ahampriyanshu/algo_ds_101#134]
**Submission Title**
Segment Tree

**Submission Type**
Data Structure

**Submission Description**
Finding the range sum queries and range xor queries using Segment Tree

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ashutoshkumar6** [comment]
> 
> 
> **Submission Title**
> Segment Tree
> 
> **Submission Type**
> Data Structure
> 
> **Submission Description**
> Finding the range sum queries and range xor queries using Segment Tree
> 
> **Contributors**
> C++

**Comment by ashutoshkumar6** [comment]
assign me this task

**Comment by Jerry2001** [comment]
Hi, I could work on the segment tree for C++, Java or Python. Could you assign me this task, please?

**Comment by ShubhamNagure** [comment]
Please assign me this task

**Comment by ahampriyanshu** [comment]
thanks @eveyone :v:
