### ISSUE TITLE
Strand_Sort

### ISSUE THREAD

**Issue by RgnDunes** [ahampriyanshu/algo_ds_101#1353]
**Submission Title**
Strand_Sort

**Submission Type**
Algorithm/Sorting_Algorithms

**Submission Directory**
Algorithms => Sorting_Algorithms => Strand_Sort => Strand_Sort.cpp

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by divyagupta-98** [comment]
Can you assign this issue to me in Python?

**Comment by SOURAB-BAPPA** [comment]
can i solve this issue in java

**Comment by Kadermiyanyedi** [comment]
Can I solve this issue in c# and javascript?

**Comment by alvinuday** [comment]
Hi i would like to work on this sorting algorithm in C , can you assign it to me

**Comment by divyagupta-98** [comment]
@ahampriyanshu #1452 Kindly Look into my PR for StrandSort in Python

**Comment by Kadermiyanyedi** [comment]
Sorry, my codes are not working properly.

**Comment by aakashsoni-cloud** [comment]
@ahampriyanshu  Could you assign me in php

**Comment by GuilhermeOliveiraCasagrande** [comment]
Can you assign me typescript?

**Comment by ahampriyanshu** [comment]
> Sorry, my codes are not working properly.

No problem :smile:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
