### ISSUE TITLE
Graph Implementation

### ISSUE THREAD

**Issue by vaishnavirshah** [ahampriyanshu/algo_ds_101#1359]
**Submission Title**
Graph

**Submission Type**
Data Structure

**Submission Description**
Graph implementation using adjancency matrix or list, along with DFS BFS codes

**Submission Directory**
Data_Structures =>Graph 

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by vaishnavirshah** [comment]
I checked the data structures directory and did not find graph implementation over there. Would like to contribute in CPP, please assign it to me.

**Comment by abhinav-idle** [comment]
I would like to do this in python.
Please assign me this.

**Comment by leli-1** [comment]
Can you assign the python version to me please thank you

**Comment by ShaikSarfraj-tech** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by VishwaroopShah** [comment]
I would do it  C language, Kindly assign it to me.

**Comment by ahampriyanshu** [comment]
> I would like to do this in python/java.
> Please assign me this.

go ahead with java.

**Comment by matheuslmpereira** [comment]
Can I include kotlin language implementation?

**Comment by Aarti002** [comment]
@ahampriyanshu Can i do this using python please....

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
