### ISSUE TITLE
Radix_Sort

### ISSUE THREAD

**Issue by Bihari420** [ahampriyanshu/algo_ds_101#136]
**Submission Title**
Radix_Sort

**Submission Type**
Algorithm

**Submission Description**
Radix sort is a sorting technique that sorts the elements by first grouping the individual digits of the same place value.

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by kaggrwal** [comment]
What exactly we have to do ?

**Comment by Nirali0029** [comment]
I will like to write radix sort in python. Please assign it to me

**Comment by kaggrwal** [comment]
Can you assign it to me ?

**Comment by saiharsha-22** [comment]
@ahampriyanshu Can I assign this task to me I will do in c

**Comment by Mayukh-1999** [comment]
I can solve this issue.I can solve this using JAVA,C,C++.
Can you assign me this issue?

**Comment by hritik5102** [comment]
Hello @Bihari420 , I would like to work on this issue 

Follow thing I want to add in you repo

- [x] Radix sort using javascript
- [x] Radix sort using ruby

Thank you :)

**Comment by jain13tushar** [comment]
Hi @Bihari420 and @ahampriyanshu,
Follow thing I want to add in you repo

 Radix sort using PHP

Thank you

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by mk1107** [comment]
I can solve this issue. I can solve this using Python, C, C++.
Can you assign me this issue?

**Comment by ahampriyanshu** [comment]
@kaggrwal go ahead with java
@saiharsha-22 go ahead with cpp
@Mayukh-1999 go ahead with C
@hritik5102 go ahead with JS and ruby
@jain13tushar go ahead with php

**Comment by ahampriyanshu** [comment]
@Nirali0029 @anubhav2005 @mk1107 Please opt a different language/issue

**Comment by kaggrwal** [comment]
Done please merge https://github.com/ahampriyanshu/algo_ds_101/pull/370

**Comment by jain13tushar** [comment]
Done please merge #372

**Comment by hritik5102** [comment]
Hello @ahampriyanshu , please check PR #436 

File added
- [x] Algorithm => Sorting_Algorithms => Radix_Sort => Radix_Sort.js
- [x] Algorithm => Sorting_Algorithms => Radix_Sort => Radix_Sort.rb

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
