### ISSUE TITLE
Group_Anagrams

### ISSUE THREAD

**Issue by PratikSangh** [ahampriyanshu/algo_ds_101#1368]
**Submission Title**
Group Anagrams

**Submission Type**
Data Structure

**Submission Description**
A fundamental application of hashing for grouping anagrams

**Submission Directory**
Data_Structures => Maps_Hash_Dict => Group_Anagrams => Group_anagrams.extension + QUESTION.md

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by PratikSangh** [comment]
Could you assign this to me in C++?

**Comment by Nirali0029** [comment]
Plz assign this to me for python

**Comment by Kadermiyanyedi** [comment]
Can you assign me Javascript please @ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
