### ISSUE TITLE
Kasai’s Algorithm 

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1370]
**Submission Title**
Kasai’s Algorithm for Construction of LCP array from Suffix Array

**Submission Type**
Data Structure

**Submission Description**
LCP Array is an array of size n (like Suffix Array). A value lcp[i] indicates length of the longest common prefix of the suffixes indexed by suffix[i] and suffix[i+1]

**Submission Directory**
Data_Structures => Arrays => Kasai_Algorithm =>kasai_algo.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by demonslayer99** [comment]
assign me this for c++

**Comment by yacth** [comment]
Hi,

Can I be assigned to this in Python please ?

**Comment by dwij2212** [comment]
Hi! Could you assign this to me in python?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
