### ISSUE TITLE
Fibonacci Heap

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1371]
**Submission Title**
Fibonacci Heap

**Submission Type**
Data Structure

**Submission Directory**
Data_Structure=>Tree=>Fibonacci_Heap=>Fibonacci_Heap.extension
**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Druffl3** [comment]
Can this be assigned to me for C# implementation?

**Comment by Kritimakaushal** [comment]
how to get assigned for this? I want to implement it in java.

**Comment by alvinuday** [comment]
Hi , i would like to implement this data structure in python , can you assign it to me

**Comment by 0x6f736f646f** [comment]
@ahampriyanshu Please assign me for C
