### ISSUE TITLE
Babylonian method for square root

### ISSUE THREAD

**Issue by Nirali0029** [ahampriyanshu/algo_ds_101#1374]
**Submission Title**
Babylonian method for square root

**Submission Type**
Maths_And_Stats

**Submission Directory**
Maths_And_Stats =>Algebra=> Babylionian=>Babylionian.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by VishwaroopShah** [comment]
I would do it in C kindly assign it to me.

**Comment by parth93QA** [comment]
assign me for golang

**Comment by demonslayer99** [comment]
assign me this for c++

**Comment by NathanPickard** [comment]
Assign me for javascript

**Comment by mhechavarria** [comment]
Can you assing me for java please? thanks!

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
