### ISSUE TITLE
VerticalOrderTraversal of Binary Tree

### ISSUE THREAD

**Issue by girishgr8** [ahampriyanshu/algo_ds_101#1394]
**Submission Title**
VerticalOrderTraversal of Binary Tree

**Submission Type**
Data_Structure

**Submission Directory**
Data_Structure=>Tree=>Data_Structures/Tree/Binary_Tree => VerticalOrderTraversal.java

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by yacth** [comment]
Hi,

Can I be assigned for this in Python ?

**Comment by Druffl3** [comment]
@ahampriyanshu , can you assign me C# implementation of this issue?

**Comment by shagunarora** [comment]
@ahampriyanshu  can you please assign me this issue in c++

**Comment by Aarti002** [comment]
@ahampriyanshu Can you assign this to me ? i would use python.

**Comment by liamm91** [comment]
Can you assign me this issue? I can use either javascript, java or python

**Comment by ahampriyanshu** [comment]
> Can you assign me this issue? I can use either javascript, java or python

Go ahead with java and JS.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
