### ISSUE TITLE
Palindrome Linked List

### ISSUE THREAD

**Issue by nehalgupta8501** [ahampriyanshu/algo_ds_101#1407]
**Submission Title**
Palindrome Linked List

**Submission Type**
Data Structure

**Submission Description**
Check if Linked List is Palindrome or not

**Submission Directory**
Data_Structures=>Linked_List=>Singly_Linked_List

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Harsh-1906** [comment]
can i solve this in java?

**Comment by rarchitgupta** [comment]
I'd like to do this in C++

**Comment by falguni-k** [comment]
I want to do this in C

**Comment by maityankan10** [comment]
would like to do in c++

**Comment by aj-ya** [comment]
hey! I would like to do this in javascript

**Comment by ghanender-chauhan** [comment]
assign me this issue i will do in python

**Comment by lashewi** [comment]
Can I work on typescript ?

**Comment by ghanender-chauhan** [comment]
> assign me this issue i will do in python

@ahampriyanshu  Sorry to ask but  i m little confused what to do in this issue can u plz tell me as i m a fresher in github

**Comment by ahampriyanshu** [comment]
> Can I work on typescript ? @ahampriyanshu



> > assign me this issue i will do in python
> 
> @ahampriyanshu Sorry to ask but i m little confused what to do in this issue can u plz tell me as i m a fresher in github

Have a look at the ``README.md``

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
