### ISSUE TITLE
Remove duplicates in a Linked List

### ISSUE THREAD

**Issue by nehalgupta8501** [ahampriyanshu/algo_ds_101#1410]
**Submission Title**
Remove duplicates in a Linked List

**Submission Type**
Data Structure

**Submission Description**
The task is to remove all duplicate nodes from a linked list

**Submission Directory**
algo_ds_101/Data_Structures/Linked_List/Singly_Linked_List/

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by MohitBhagchandani0601** [comment]
I want to work on this issue in java😊

**Comment by Harsh-1906** [comment]
please assign this to me.. i will solve this using c++

**Comment by Ayushmanglani** [comment]
Please assign this to me for Python

**Comment by bhavya092** [comment]
Can you assign this to me...I'll help in C++?

**Comment by AlessandroArosio** [comment]
@nehalgupta8501 can I do it in java? An easy and quick way

**Comment by P-cpu** [comment]
Hi @ahampriyanshu please assign me for this issue in c language

**Comment by maityankan10** [comment]
please this to me in c language

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by maityankan10** [comment]
hey this already contains contains C code. Should i develop a C++ code for this project

**Comment by maityankan10** [comment]
hey I have added c++ code for removing duplicates pls verify it asap
