### ISSUE TITLE
Adding code for largest divisible subset

### ISSUE THREAD

**Issue by Sinha199** [ahampriyanshu/algo_ds_101#1425]
**Submission Title**
Dynamic Programming

**Submission Type**
Algorithm

**Submission Description**
Given a set or array, we have to find the largest divisible subset

**Submission Directory**
Algorithms => Dynamic_Programming => Largest_Divisible_Subsets.cpp

**Contributors**

- [x]  C++ - 
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by lashewi** [comment]
I would like to do this in Java

**Comment by lashewi** [comment]
Can I work only on one language? if not would like to do this in python

**Comment by Himanshu-Nagle** [comment]
@Sinha199 Kindly please assign me for python and C#

**Comment by greyGroot** [comment]
@Sinha199 please, assign it to me, i want to do it in JavaScript and TypeScript. Thank you.

**Comment by P-cpu** [comment]
Hi @ahampriyanshu  please assign me this issue in c language
