### ISSUE TITLE
Jump Search

### ISSUE THREAD

**Issue by rushitote** [ahampriyanshu/algo_ds_101#143]
**Submission Title**
Jump Search

**Submission Type**
Search Algorithm

**Submission Description**
Jump Search is a search algorithm for searching an element in a sorted array by ‘jumping’ fixed number of elements every time instead of searching all of them (like linear search).

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by megabyte98** [comment]
can you assign this issue to me?

**Comment by kaggrwal** [comment]
Can you assign this to me?

**Comment by megabyte98** [comment]
I will implement it in python3

**Comment by ahampriyanshu** [comment]
Hi @kaggrwal , please mention your preferred language.

**Comment by kaggrwal** [comment]
I'll do it java

**Comment by megabyte98** [comment]
I have made a PR can you please check by mistake I have not named the branch with my username

**Comment by Mayukh-1999** [comment]
I will do it in C++. Can you assign me this issue?

**Comment by rushitote** [comment]
@megabyte98 
I think you have added wrong issue number, please check again.

**Comment by souvickroy02** [comment]
I would like to work on this issue. I will use C language to solve this issue. can you please assign me with this issue? Thank you.

**Comment by megabyte98** [comment]
@rushitote  issue number 143 correct

**Comment by rushitote** [comment]
@megabyte98 
You have linked issue 23.

**Comment by megabyte98** [comment]
I have made that change

**Comment by megabyte98** [comment]
Thanks @rushitote :)

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use Java to solve this issue. can you please assign me with this issue? Thank you.

**Comment by kaggrwal** [comment]
@ahampriyanshu Can you assign me to do it in Java or python

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
