### ISSUE TITLE
Hungarian algorithm

### ISSUE THREAD

**Issue by 0x6f736f646f** [ahampriyanshu/algo_ds_101#1444]
**Submission Title**
Hungarian algorithm

**Submission Type**
Algorithm

**Submission Description**
Check out this site for [reference](https://en.wikipedia.org/wiki/Hungarian_algorithm)

**Submission Directory**
Algorithm=>Graph=>Hungarian_algorithm=>Hungarian_algorithm.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Flamer17** [comment]
can u assign this issue to me
ill do it using java

**Comment by bobbysaprey420** [comment]
@ahampriyanshu Assign this to me for C++

**Comment by subham5230** [comment]
please assign this to me in python @ahampriyanshu

**Comment by bobbysaprey420** [comment]
@ahampriyanshu By mistake I clicked on unassigned me, can be please assign me again
