### ISSUE TITLE
Jump point search

### ISSUE THREAD

**Issue by 0x6f736f646f** [ahampriyanshu/algo_ds_101#1447]
**Submission Title**
Jump point search algorithm

**Submission Type**
Algorithm

**Submission Description**
Check out this site for [reference](https://en.wikipedia.org/wiki/Jump_point_search)

**Submission Directory**
Algorithm=>Graph=>Jump_point_search=>Jump_point_search.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by aj-ya** [comment]
Hey! I'll submit the C++ implementation of this problem.

**Comment by Alok-873** [comment]
can i work on this in c++?

**Comment by bobbysaprey420** [comment]
@ahampriyanshu  Assign this to me

**Comment by leli-1** [comment]
Can I do this in python?

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Assign this to me

Please mention your preferred language.

**Comment by ahampriyanshu** [comment]
l
