### ISSUE TITLE
Karger's algorithm

### ISSUE THREAD

**Issue by 0x6f736f646f** [ahampriyanshu/algo_ds_101#1449]
**Submission Title**
Karger's algorithm

**Submission Type**
Algorithm

**Submission Description**
Check out this site for [reference](https://en.wikipedia.org/wiki/Karger%27s_algorithm)

**Submission Directory**
Algorithm=>Graph=>Karger_algorithm=>Karger_algorithm.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by liamm91** [comment]
Can you assign me this issue?

**Comment by bobbysaprey420** [comment]
@ahampriyanshu assign this work to me

**Comment by leli-1** [comment]
Can I do this in python?

**Comment by ahampriyanshu** [comment]
@liamm91 and @bobbysaprey420 mention your preferred language.

**Comment by bobbysaprey420** [comment]
C++

**Comment by ahampriyanshu** [comment]
thanks @0x6f736f646f  and @belphegor-s
