### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#148]
**Submission Title**
Armstrong Number

**Submission Type**
Maths_And_Stats

**Submission Description**
An Armstrong number is a number such that the sum ! of its digits raised to the third power is equal to the number ! itself. For example, 371 is an Armstrong number, since !

**Contributors**
- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Vimlesh-Kumar** [comment]
please assign me in c++ @ahampriyanshu

**Comment by akankshast** [comment]
I would like to contribute using C++,Kindly assign it to me.
Regards ,
Akanksha

**Comment by Sayan-Manna** [comment]
I would like to contribute using Java. Please assign me.
Thank You!

**Comment by princekalra** [comment]
i would like to work on cpp please assign it to me

**Comment by saiharsha-22** [comment]
@Vimlesh-Kumar I would like to solve for c

**Comment by saiharsha-22** [comment]
@ahampriyanshu  I would like to work in c program can you please assign me

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu I would like to work in c program can you please assign me

Hi @saiharsha-22 , I already did ...

**Comment by saiharsha-22** [comment]
@ahampriyanshu Thank you. I work on it now

**Comment by Sayantan-world** [comment]
I would like to work on this in PHP, please assign this to me.

**Comment by Samkit-shah** [comment]
I would like to go for C, please assign

**Comment by ankitgoel25** [comment]
I would like to work on this in Python, please assign as the previously assigned removed their assignment

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
