### ISSUE TITLE
Patience Sort Algorithm

### ISSUE THREAD

**Issue by s2agrahari** [ahampriyanshu/algo_ds_101#1480]
**Submission Title**
Patience Sort Algorithm

**Submission Type**
Algorithm

**Submission Description**
Patience Sort Algorithm (https://en.wikipedia.org/wiki/Patience_sorting)

**Submission Directory**
Algorithms => Sorting_Algorithms => Patience_Sort => Patience_Sort.<extension> 

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sarthak-21** [comment]
Please assign this to me, I will do it in C. @ahampriyanshu @s2agrahari

**Comment by monteiromarceloc** [comment]
I would like to do this in python.
Please assign me this one.

**Comment by Aarti002** [comment]
@ahampriyanshu  can you assign this to me i would implement this in python.

**Comment by liamm91** [comment]
Can I do this in python or c++?

**Comment by ahampriyanshu** [comment]
> Can I do this in python or c++?

Please opt a different language/issue.

**Comment by LDiazN** [comment]
I can do it in C#

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
