### ISSUE TITLE
Sum of a AP is not implemented in C.

### ISSUE THREAD

**Issue by VishwaroopShah** [ahampriyanshu/algo_ds_101#1482]
**Submission Title**
Implementation of AP (Arithmetic Progression) in C 

**Submission Type**
Maths_And_Stats

**Submission Description**
While going through the repository, it is found that the sum of a series of Arithmetic progression is not implemented in C. 

**Submission Directory**
Maths_And_Stats => Series => Sum_of_AP => Sum_of_AP.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by VishwaroopShah** [comment]
I like to implement in C, Kindly assigned it to me.

**Comment by ahmeddrawy** [comment]
is this still available for C++ or python ?

**Comment by Sindhu-321** [comment]
may I get this issue assigned? I would like to solve this in C. Also i would like to solve this in c++ as well if available. Thanks.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
