### ISSUE TITLE
Implementation of Permutation_And_Combination

### ISSUE THREAD

**Issue by VishwaroopShah** [ahampriyanshu/algo_ds_101#1483]
**Submission Title**
Permutation_And_Combination

**Submission Type**
Maths_And_Stats/Algebra/Permutation_And_Combination

**Submission Description**
When looking in the repository It is found that the permutation and combination which have been very useful in Mathematics is not implemented.

**Submission Directory**
Maths_And_Stats => Algebra => Permutation_And_Combination => permutation_combination.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by VishwaroopShah** [comment]
I would like to implement it in C++. Kindly assign it to me.

**Comment by SanmitR** [comment]
Can I do this in python?

**Comment by ahmeddrawy** [comment]
Can you tell me what is the input constraints and if the C++ or python or javascript I can do it in any of them

**Comment by ahampriyanshu** [comment]
> Can you tell me what is the input constraints and if the C++ or python or javascript I can do it in any of them

go ahead with JS.

**Comment by ahmeddrawy** [comment]
> > Can you tell me what is the input constraints and if the C++ or python or javascript I can do it in any of them
> 
> go ahead with JS.

Can you give me the input style and constraints ? @ahampriyanshu

**Comment by ahampriyanshu** [comment]
> > > Can you tell me what is the input constraints and if the C++ or python or javascript I can do it in any of them
> > 
> > 
> > go ahead with JS.
> 
> Can you give me the input style and constraints ? @ahampriyanshu

**Input**
 Ask the user whether he/she wishes to find permtaution or combination.

**Constraint:**
``n,r>0``
``n>r``

**Comment by RachanaKampli** [comment]
I would like to implement using C .Can I do this??

**Comment by ShubhamNagure** [comment]
Hi @VishwaroopShah 
Please assign me

**Comment by Aarti002** [comment]
hello @ahampriyanshu Can i do this issue using python?

**Comment by VishwaroopShah** [comment]
Hello @ShubhamNagure I am not the one who is assigning the task, @ahampriyanshu is the one who is assigning.

**Comment by ShubhamNagure** [comment]
> Hello @ShubhamNagure I am not the one who is assigning the task, @ahampriyanshu is the one who is assigning.

Oops, my bad.
@ahampriyanshu can you assign this to me?

**Comment by leli-1** [comment]
Can I do this in python?

**Comment by subham5230** [comment]
Please assign this to me in java
@ahampriyanshu

**Comment by ahampriyanshu** [comment]
> Can I do this in python?

@leli-1 please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
