### ISSUE TITLE
Added=>Data_Structure=>Queue=>circular queue

### ISSUE THREAD

**Issue by SumitKuSahu** [ahampriyanshu/algo_ds_101#1505]
**Submission Title**
Circular queue

**Submission Type**
Data Structure

**Submission Description**
circular queue using linked list perform insertion and dequeue and displays it .

**Submission Directory**
Data_Structure=>Queue=>circular queue

**Contributors**

- [x]  C++ -
- [ x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -

- [ ] Swift -
- [ ] C# -

**Comment by aakashsoni-cloud** [comment]
@ahampriyanshu  could you assign me for c++/python

**Comment by aakashsoni-cloud** [comment]
@ahampriyanshu I just check the repository we have another folder named as Data_structure/Queue could you just merge it with the Data_structure folder to remove any confusion or loss.

**Comment by kusumapriyankaajjarapu** [comment]
@ahampriyanshu could you assign me for java

**Comment by NavyaIyanampudi** [comment]
Can I add circular queue data structure?

**Comment by ahampriyanshu** [comment]
> Can I add circular queue data structure?

Please mention your preferred language.

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu I just check the repository we have another folder named as Data_structure/Queue could you just merge it with the Data_structure folder to remove any confusion or loss.

Done :+1: 
Sorry for the inconvenience.
:v:

**Comment by Sindhu-321** [comment]
If the issue is still open can I give it a try??

**Comment by ahampriyanshu** [comment]
thanks everyone @belphegor-s
