### ISSUE TITLE
Implementing Binary Indexed Tree Or Fenwick Tree | Range Queries | C++

### ISSUE THREAD

**Issue by chiyapathak** [ahampriyanshu/algo_ds_101#1506]
**Submission Title**
- Binary Indexed Tree

**Submission Type**
- Algorithm

**Submission Description**
- To perform query and update both in  O(logN) time we use fenwick tree.
- Compared with Segment Tree, Binary Indexed Tree requires less space and is easier to implement.
- I will perform build, update, query operations to find maximum in a given range.

**Submission Directory** 
algo_ds_101 => Data_Structures => Tree => Binary_Indexed_Tree => range_max_query_BIT.cpp

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by chiyapathak** [comment]
I would like to work on it.

**Comment by kugiyasan** [comment]
Can I get assigned for the python implementation please?

**Comment by kugiyasan** [comment]
Can I do the Golang implementation too?

**Comment by Amanj2000** [comment]
I would like to implement it in c.

**Comment by Amanj2000** [comment]
Can I also implement it in Java?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
