### ISSUE TITLE
Perfect Number

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#151]
**Submission Title**
Perfect Number

**Submission Type**
Maths_And_Stats

**Submission Description**
A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. For instance, 6 has divisors 1, 2 and 3, and 1 + 2 + 3 = 6.

**Folder Related To**
Maths_And_Stats => Perfect_Number

**Contributors**
- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by megabyte98** [comment]
can you assign this issue to me

**Comment by ahampriyanshu** [comment]
Hi @megabyte98, please mention your preffered language 😄

**Comment by megabyte98** [comment]
Python

**Comment by megabyte98** [comment]
I have added perfect number as well can you check the PR  and mention if any changes required

**Comment by Nivedita-coder** [comment]
I would like to work on this in C, please assign this to me.

**Comment by Sayantan-world** [comment]
I would like to work on this in PHP, please assign this to me.

**Comment by Samkit-shah** [comment]
Hey I have Solved it in C++ can you assign it to me so that i can make a PR

**Comment by Wekananda** [comment]
Please assign it to me. I would like to contribute it in Java

**Comment by Samkit-shah** [comment]
I would also like to contribute for this in php

**Comment by Samkit-shah** [comment]
I would like to contribute for this in Javascript can you please assign me that too

**Comment by ashish-garg18** [comment]
I would like to work on  C, C++, Java. Can you assign it to me.

**Comment by jaskarans2000** [comment]
I would like to do it in java

**Comment by geoffgeorgein** [comment]
I shall implement a short and precise code in python. Please assign this to me.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
