### ISSUE TITLE
Want to add Hash Set data structure

### ISSUE THREAD

**Issue by studpeps** [ahampriyanshu/algo_ds_101#1520]
**Submission Title**
Hash Set 

**Submission Type**
Data Structure

**Submission Description**
Want to add use case implementation code for hash set data structure; since it has not been a part yet.

**Submission Directory**
Data Structures =>Maps_Hash_Dict

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by studpeps** [comment]
Please assign the above issue to me

**Comment by bobbysaprey420** [comment]
@ahampriyanshu  Please assign this to me for C++ language

**Comment by YJDoc2** [comment]
Hey 
I checked the Maps_Hash_Dict folder, and could not see the c implementation of HashSet, even though it is ticked in the issue. If it is to be done, can you assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
