### ISSUE TITLE
Graph - Adjancency List - Kotlin Implementation

### ISSUE THREAD

**Issue by matheuslincolnss** [ahampriyanshu/algo_ds_101#1523]
**Submission Title**
Graph

**Submission Type**
Data Structure

**Submission Description**
Graph implementation using adjancency list, along with DFS BFS codes

**Submission Directory**
Data_Structures =>Graph

**Contributors**

- [x]  Kotlin

**Comment by ahampriyanshu** [comment]
thanks @matheuslincolnss :v:
