### ISSUE TITLE
KMP Algorithm for Pattern Searching | Python

### ISSUE THREAD

**Issue by drstrange11** [ahampriyanshu/algo_ds_101#1525]
**Submission Title**
KMP Algorithm

**Submission Type**
Algorithm

**Submission Description**
To search for string patterns.

**Submission Directory**
Algorithms/Pattern_Searching/KMP_Algorithm/kmp.py

**Contributors**

- [X]  Python

**Comment by drstrange11** [comment]
If this looks fine, please assign it to me. @ahampriyanshu

**Comment by Nirali0029** [comment]
Plz assign this to me for python

**Comment by bobbysaprey420** [comment]
Please assign this to me for C++ language

**Comment by Amanj2000** [comment]
I want to work on this in Java.

**Comment by ferch5003** [comment]
I want to work on this in JavaScript.

**Comment by adrputra** [comment]
I'll do it in PHP, please assign me

**Comment by adrputra** [comment]
@ahampriyanshu Please check out my PR

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
