### ISSUE TITLE
Addition of trie data structure

### ISSUE THREAD

**Issue by dwij2212** [ahampriyanshu/algo_ds_101#1527]
**Submission Title**
Add folder for trie

**Submission Type**
Data structure

**Submission Description**
Trie is a type of a tree which enables us to have much faster search results as compared to a BST.

**Submission Directory**
Data_structure=>Trees=>Trie=>Trie.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by dwij2212** [comment]
I would like to work on this issue in C++

**Comment by Nirali0029** [comment]
Plz assign this to me for python

**Comment by shahbazalam07** [comment]
please assign to me for java

**Comment by LDiazN** [comment]
I can do it in C#, assign it to me.

**Comment by bobbysaprey420** [comment]
Please assign this to me for C++ language

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Please assign this to me for C++ language

Please opt a different language/issue.

**Comment by Kashish888** [comment]
I would like to work on this issue in C

**Comment by Kingarturs** [comment]
Hi! I would like to work on this in Golang 🚀

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
