### ISSUE TITLE
Want to add solution for rainwater trapping problem

### ISSUE THREAD

**Issue by technisRahulk** [ahampriyanshu/algo_ds_101#1547]
**Submission Type**
Data_Structure/Arrays

**Submission Description**
Rainwater trapping problem

**Submission Directory**
Data_Structure => Arrays=> rainwater_trapping.cpp

**Contributors**

- [x]  C++ -

**Comment by technisRahulk** [comment]
@ahampriyanshu please assign me this

**Comment by dhairya-parikh** [comment]
Can you please assign this to me in Java ?
@ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
