### ISSUE TITLE
Partition Equal Subset Sum | C++

### ISSUE THREAD

**Issue by trishnakalita660** [ahampriyanshu/algo_ds_101#1552]
**Submission Title**
Data Structure/Array

**Submission Description**
Partition Equal Subset Sum

**Submission Directory**
Folder``(Algorithm/Data_Structures/Array...)`` => Sub_Folder``(equal subset sum partition)`` => ... => ``.cpp``

**Contributors**

- [x]  C++ 
- [ ]  C 
- [ ]  Python 
- [ ] Java 
- [ ] JavaScript
- [ ] TypeScript
- [ ] Golang
- [ ] Ruby
- [ ] php 
- [ ] Swift 
- [ ] C#

**Comment by ldrf** [comment]
Hi! I can try this in Java?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
