### ISSUE TITLE
Want to add N queen problem using bitmasking in data structrue & algo section 

### ISSUE THREAD

**Issue by jvishad** [ahampriyanshu/algo_ds_101#1564]
**Submission Title**
N queen problem using bitmasking 

**Submission Type**
Algorithm/bitmasking

**Submission Description**
Solved a N queen problem using bitmasking,this is very important concept for solving advanced problems.

**Submission Directory**
Folder``(Algorithm)`` => Sub_Folder``(Bitmasking)`` => ... => ``N_queen_problem_using_bitmasking.cpp``

**Contributors**

- [x]  C++ 
- [ ]  C 
- [ ]  Python 
- [ ] Java 
- [ ] JavaScript
- [ ] TypeScript
- [ ] Golang
- [ ] Ruby
- [ ] php 
- [ ] Swift 
- [ ] C#

**Comment by jvishad** [comment]
@ahampriyanshu Please assign this task to me.:) 
Thanks in advance.

**Comment by jvishad** [comment]
@ahampriyanshu Please assign this task to me.:)
Thanks in advance.

**Comment by anirudhps10** [comment]
Can you assign me for Python?

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
@ahampriyanshu ,please assign me for JAVA

**Comment by ahampriyanshu** [comment]
Duplicate Issue ⚠️
