### ISSUE TITLE
Sum of n natural Number

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#157]
**Submission Title**
Sum of n natural Number

**Submission Type**
Maths_And_Stats

**Submission Description**
Let S be the required sum.
Therefore, S = 1 + 2 + 3 + 4 + 5 + .................... + n
Clearly, it is an Arithmetic Progression whose first term = 1, last term = n and number of terms = n.
Therefore, S = n2(n + 1), [Using the formula S = n2(a + l)]

**Folder Related To**
Maths_And_Stats => series => filename.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by deepdhar** [comment]
@Vimlesh-Kumar I would like to work on this in C++, please assign it to me

**Comment by rohitsingh2410** [comment]
@Vimlesh-Kumar  please assign this to me for python.

**Comment by Alifbhanvadiya14** [comment]
please assign this to me in python/java

**Comment by arkumari2000** [comment]
Please assign this to me for C.

**Comment by Vimlesh-Kumar** [comment]
> please assign this to me in python/java

for java.

**Comment by rohitsingh2410** [comment]
@Vimlesh-Kumar  i have sent the PR for python. Thanks for the opportunity.

**Comment by rohitsingh2410** [comment]
@Vimlesh-Kumar i have submitted the PR, but it seems that in you CI CD pipeline there is some error in some yml file,
Could you please check and let me know if this is something to do with my code method wrong or something?
![image](https://user-images.githubusercontent.com/17305828/94912215-f70f2c80-04c4-11eb-9886-db656d538afd.png)

Thanks

**Comment by Sayantan-world** [comment]
I would like to work on this in PHP, please assign it to me.

**Comment by Samkit-shah** [comment]
Please assign it to me for Javascript

**Comment by harshita130602** [comment]
Could you please assign this issue to me for C#. I would like to do that.

**Comment by harshita130602** [comment]
Hey! I have added the program to print the sum of N natural numbers. Please review my PR #280

**Comment by xanaDev** [comment]
I'll be working on a Golang implementation, can you please assign it to me.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
