### ISSUE TITLE
Shamir’s Secret Sharing Algorithm

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1578]
**Submission Title**
Shamir’s Secret Sharing Algorithm

**Submission Type**
Algorithm

**Submission Description**
Shamir’s Secret Sharing is an algorithm in cryptography created by Adi Shamir. The main aim of this algorithm is to divide secret that needs to be encrypted into various unique parts.

**Submission Directory**
Algorithm => Cryptography_Algorithm => Shamir_Cipher => Shamir_Cipher.extension

**Contributors**

- [x]  C++ 
- [x]  C 
- [ ]  Python 
- [ ] Java 
- [ ] JavaScript
- [ ] TypeScript
- [ ] Golang
- [ ] Ruby
- [ ] php 
- [ ] Swift 
- [ ] C#

**Comment by PAARTH2608** [comment]
Can i work on this issue?

**Comment by viralkumar28** [comment]
Can you assign me. I will do in java
