### ISSUE TITLE
Deque - STL

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1579]
**Submission Title**
Deque

**Submission Type**
STL

**Submission Description**
Deque or double-ended queue is an abstract data type that generalizes a queue, for which elements can be added to or removed from either the front or back. Please push a program that explains all the in-built methods like ``push_back()``, ``push_front()``, ``pop_back()``, ``pop_front()``, ``size()``, ``resize()`` , ``at()``, ``front()``, ``back()``, etc.

**Submission Directory**
STL => Deque => Deque.cpp

**Contributors**

- [x]  C++

**Comment by geoffgeorgein** [comment]
I can do this ,I have solved programming problems using deque .Please assign me
