### ISSUE TITLE
KMP algorithm

### ISSUE THREAD

**Issue by shobha9250** [ahampriyanshu/algo_ds_101#1581]
### Submission Directory

Algorithm => string_matching

### Type

Algorithm

### What happened?

Implement KMP string matching algorithm in c++ with O(n) time complexity

### Programming Language

- [X] c++
- [X] c
- [X] c#
- [ ] java
- [ ] python
- [ ] javascript
- [ ] typescript
- [ ] ruby
- [ ] swift
- [ ] scala
- [ ] go
- [ ] php

**Comment by shobha9250** [comment]
I issues are assigned , I made one and I want to contribute to this.

**Comment by shobha9250** [comment]
Please assign me this , I can do this

**Comment by ManavArora26** [comment]
Please assign me this, for python

**Comment by ApoorvaKaushal09** [comment]
Hey I can work on this issue. Please assign this to me, for java.

**Comment by gauravsax1911** [comment]
Hey can you assign this to me,for c++

**Comment by shadowshot-x** [comment]
Can i work on this in Golang?

**Comment by PrakashAditya17** [comment]
I can code KMP in Java
