### ISSUE TITLE
AES Encryption Decryption Algorithm

### ISSUE THREAD

**Issue by sudesh1611** [ahampriyanshu/algo_ds_101#1582]
#### Submission Title
AES Encryption Decryption Algorithm

### Submission Type
Algorithm

### Submission Description
AES is a symmetric algorithm that is used for encryption.

### Submission Directory
Algorithm => Cryptography => AES_Cipher => ReadMe.md

### Programming Language

- [ ] c++
- [ ] c
- [ ] c#
- [ ] java
- [X] python
- [ ] javascript
- [ ] typescript
- [ ] ruby
- [ ] swift
- [ ] scala
- [ ] go
- [ ] php

**Comment by nimishh7** [comment]
@ahampriyanshu Can i work on this issue ?

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Can i work on this issue ?

Hi @nimishh7, please mention your preferred language.

**Comment by nishantkumar1308** [comment]
I can work in C++ please assign it to me.

**Comment by nimishh7** [comment]
> > @ahampriyanshu Can i work on this issue ?
> 
> Hi @nimishh7, please mention your preferred language.

@ahampriyanshu python

**Comment by nishantkumar1308** [comment]
@ahampriyanshu  please assign me this in c++ .I am first timer
