### ISSUE TITLE
Avl tree

### ISSUE THREAD

**Issue by shobha9250** [ahampriyanshu/algo_ds_101#1585]
### Directory

Algorithms => tree_algorithms => avl_tree

### Programming Language

- [X] c++
- [X] c
- [X] c#
- [ ] java
- [ ] python
- [ ] javascript
- [ ] typescript
- [ ] ruby
- [ ] swift
- [ ] scala
- [ ] go
- [ ] php

**Comment by shobha9250** [comment]
Please assign me this

**Comment by ahampriyanshu** [comment]
Please take a look at #489
