### ISSUE TITLE
Deque

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1587]
### Type

Data-Structure

### Directory

Data-Structures => Queue => Deque => Deque.extension

### Description

Deque or double-ended queue is an abstract data type that generalizes a queue, for which elements can be added to or removed from either the front or back.
**Note :** Please don't use any inbuilt library/function.

### Programming Language

- [X] c++
- [ ] c
- [ ] c#
- [ ] java
- [X] python
- [x] javascript
- [X] typescript
- [ ] ruby
- [ ] swift
- [ ] scala
- [ ] go
- [ ] php

**Comment by EANimesha** [comment]
I would like to add code in Java. Please assign me

**Comment by amitsat27** [comment]
hello @ahampriyanshu can you assign me the task in c?

**Comment by rohitkumar9710** [comment]
@ahampriyanshu can you assign this task to me? I'll be using c++.

**Comment by harshitsuthar77731** [comment]
can you assign me in go

**Comment by not4YU5H** [comment]
@ahampriyanshu can you assign this task to me in python?

**Comment by ignacioespinoso** [comment]
Can you assign this task to me in swift?

**Comment by divyansh1511** [comment]
can u assign this issue to me .... in  cpp
@ahampriyanshu

**Comment by hitesh1906** [comment]
I want to work on this issue. Can you assign me this issue in c language?
