### ISSUE TITLE
Circular Queue

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1588]
### Type

Data-Structure

### Directory

Data-Structures => Queue => Circular-Queue => Circular-Queue.extension

### Description

A circular queue is the extended version of a regular queue where the last element is connected to the first element.
**Note :** Please don't use any inbuilt library/function.

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [x] php
- [ ] haskell
- [ ] bash

**Comment by Samkit-shah** [comment]
Can i go with this for php?

**Comment by Samkit-shah** [comment]
Can I work for python?

**Comment by ManavArora26** [comment]
Assign me in python pls!

**Comment by amitsat27** [comment]
Hello @ahampriyanshu can you assign the task to me in python ?

**Comment by ParthPali** [comment]
Hello @ahampriyanshu - please assign the task to me in java.

**Comment by rohitkumar9710** [comment]
Hello @ahampriyanshu can you assign this task to me in C, C++?

**Comment by shadowshot-x** [comment]
I want to contribute to this in golang. Can you assign me?

**Comment by ghozt777** [comment]
@ahampriyanshu I want to contribute in Java. Can you please assign me

**Comment by 2309harshit** [comment]
Hey can you please assign this issue to me. I think I can do this in c++.
Thanks in anticipation!
