### ISSUE TITLE
Mean

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#159]
**Submission Title**
Mean of given Numbers

**Submission Type**
Maths_And_Stats

**Submission Description**
The mean is the average of the numbers. It is easy to calculate: add up all the numbers, then divide by how many numbers there are. In other words it is the sum divided by the count.

**Folder Related To**
Maths_And_Stats => Stats => filename.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by js899** [comment]
Can I do this with python/cpp ?

**Comment by Alifbhanvadiya14** [comment]
Can I work in python

**Comment by Alifbhanvadiya14** [comment]
or Java

**Comment by sonuishaq67** [comment]
I can do the C javascript C# part

**Comment by Vimlesh-Kumar** [comment]
> Can I do this with python/cpp ?

Go with c++

**Comment by Alifbhanvadiya14** [comment]
in which language shall i Python or ?

**Comment by js899** [comment]
i have done it please merge it in yours

**Comment by sonuishaq67** [comment]
I implemented this in c , c# and javascript 
please do check  #169

**Comment by Sayantan-world** [comment]
I would like to work on this in PHP, please assign this to me.

**Comment by LUCIFER-dev-king** [comment]
Hi @ahampriyanshu , Assign me on this I can work on Java and C.

**Comment by sonuishaq67** [comment]
Hi @LUCIFER-dev-king  i already did the c part

**Comment by LUCIFER-dev-king** [comment]
> Hi @LUCIFER-dev-king i already did the c part

Ok I'll do java part.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
