### ISSUE TITLE
Priority Queue

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1590]
### Type

Data-Structure

### Directory

Data-Structures => Queue => Priority-Queue => Priority-Queue.extension

### Description

A priority queue is an abstract data type similar to a regular queue or stack data structure in which each element additionally has a "priority" associated with it.
**Note : ** Please don't use any inbuilt library/function.

### Programming Language

- [ ] c++
- [ ] c
- [X] python
- [ ] java
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [x] php
- [ ] haskell
- [ ] bash

**Comment by Tusharsd123** [comment]
I would like to work on this in c++.

**Comment by Samkit-shah** [comment]
Can i work on it for php

**Comment by ahampriyanshu** [comment]
CPP => 1 Day
