### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1591]
### Type

Data-Structure

### Directory

Data-Structures => Array => Array.extension

### Description

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.
Just declare an array dynamically, insert some elements from the stdin/console and then print(transverse) the array.

### Programming Language

- [x] c++
- [x] c
- [x] python
- [x] java
- [ ] javascript
- [x] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [x] go
- [x] php
- [ ] haskell
- [ ] bash

**Comment by KamalAres** [comment]
I would like to work on this issue. Could you please assign it to me? I can submit the code in Java

**Comment by Tusharsd123** [comment]
Hey , I would like to work on this .. I can submit it in C++

**Comment by HariMenon2002** [comment]
i can only see redme.md in Array but i cant find the extension,can you please help me out

**Comment by HariMenon2002** [comment]
even i would like to work on this

**Comment by ahampriyanshu** [comment]
> i can only see redme.md in Array but i cant find the extension,can you please help me out

https://github.com/ahampriyanshu/algo_ds_101#how-to-contribute

**Comment by durgeshahire07** [comment]
I want to work on this issue, i can implement this using javascript

**Comment by nibble-4bits** [comment]
Hello @ahampriyanshu, I'd like to work on this issue. I could implement the code in TypeScript

**Comment by Harshgupta5901** [comment]
Hello @ahampriyanshu, I want to work on the issue in python. Pls assign me.

**Comment by Harshgupta5901** [comment]
#1607

**Comment by Samkit-shah** [comment]
Can i work on it for php?

**Comment by KevalPrajapati** [comment]
Hey I cant to work for this in go. Please assign it to me.

**Comment by Aaryan0424** [comment]
I would like to work on this issue in C . can you assign it to me

**Comment by VidushiJain30** [comment]
Hii,
I would like to contribute!!

**Comment by ahampriyanshu** [comment]
> Hii, I would like to contribute!!

Hi @VidushiJain30, please mention your preferred language.

**Comment by aditya-gaikwad** [comment]
Hello, I would like to contribute.
preffered language C++

**Comment by harshvardhan56** [comment]
can you please merge PR #1711 
i have implemented all the methods of array

**Comment by Ashishadhikari123** [comment]
I would like to contribute.
Language c++

**Comment by ahampriyanshu** [comment]
thank you **everyone**

**Comment by AR10X** [comment]
Hi, I would like to add code for Ruby.

**Comment by aditya-gaikwad** [comment]
> Hello, I would like to contribute. preffered language C++

PLease reply
