### ISSUE TITLE
Java Collections : ArrayList

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1592]
### Type

Collection

### Directory

Collection => ArrayList => ArrayList.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by KamalAres** [comment]
I can implement all basic operations in ArrayList in java collections. Can you assign the task to me?
