### ISSUE TITLE
Java Collection : LinkedList

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1593]
### Type

Collection

### Directory

Collection => LinkedList => LinkedList.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by KamalAres** [comment]
I can implement the basic methods of LinkedList Collection in java. Can you assign this task to me?

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you please assign this task to me for C++, Thanks!
