### ISSUE TITLE
Java Collection : ArrayDeque

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1594]
### Type

Collection

### Directory

Collection => ArrayDeque => ArrayDeque.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by Gagan-Shenoy** [comment]
Can I take up this issue please?

**Comment by Gagan-Shenoy** [comment]
Thank you for assigning the issue. Will do the pr ASAP!

**Comment by Gagan-Shenoy** [comment]
Please review my PR #1683
Thank you.
