### ISSUE TITLE
Java Collection : Deque

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1595]
### Type

Collection

### Directory

Collection => Deque => Deque.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by rezwan2525** [comment]
Hi, can you assign me this issue, please? I want to do it in Java.
