### ISSUE TITLE
Java Collection : PriorityQueue

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1599]
### Type

Collection

### Directory

Collection => PriorityQueue => PriorityQueue.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by rezwan2525** [comment]
I would like to work on this issue. Can you please assign me?

**Comment by rezwan2525** [comment]
@ahampriyanshu Hi, I think, this issue can be closed now. Since "Collection" is a Java framework, we need not wait for other programming language solutions in this case probably. What's your thought on this? Thanks.
