### ISSUE TITLE
Java Collection : Stack

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1601]
### Type

Collection

### Directory

Collection => Stack => Stack.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by Iconic-It-Is** [comment]
I would like to work on this issue, please consider my profile for this task and do assign it to me.
Programming Language: C++

**Comment by rishikeshreddyakkireddy** [comment]
Can you assign this to me ? I have already written using java.
