### ISSUE TITLE
Java Collection : Vector

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1602]
### Type

Collection

### Directory

Collection => Vector => Vector.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by durgeshahire07** [comment]
i can work with the c++ implementation

**Comment by Iconic-It-Is** [comment]
I would like to work on this issue, please consider my profile for this task and do assign it to me.
