### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by threedotspast** [ahampriyanshu/algo_ds_101#1605]
### Directory

Data-Structure=>Stack=>Readme.md

### Things To Remember

- [X] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc. For theory, use open-source alternatives like WikiPedia.
- [X] I have used github flavoured md syntax only.
- [X] All the relative links are working.
- [X] All the absolute links are working.
- [X] I have synced-up my forked repo.
- [X] Ain't pushing from the main branch.

**Comment by nishantkumar1308** [comment]
Assign this to me i will do in C++

**Comment by ignacioespinoso** [comment]
I can do this in Swift

**Comment by keinisha** [comment]
Hi, can I do this in C? @ahampriyanshu

**Comment by Monem-Shahriar** [comment]
Hi, can I do this in python?

**Comment by Tanushreesuthar** [comment]
assign me in javascript

**Comment by 2309harshit** [comment]
Hey can you please assign this issue to me. I think I can do this in c++.
Thanks in anticipation!
