### ISSUE TITLE
Stack Using Array

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1608]
### Type

Data-Structure

### Directory

Data-Structures => Stack => StackUsingArray.extension

### Description

A Stack is a linear data structure that follows the LIFO (Last-In-First-Out) policy.

### Programming Language

- [X] c++
- [X] c
- [x] python
- [x] java
- [ ] kotlin
- [X] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [X] ruby
- [ ] scala
- [x] go
- [x] php
- [X] haskell
- [ ] bash

**Comment by Devenkapoor7303** [comment]
Hey, Can I work on this can you please assign this issue to me? I can do it cpp language. @ahampriyanshu

**Comment by ahampriyanshu** [comment]
> Hey, Can I work on this can you please assign this issue to me? I can do it cpp language. @ahampriyanshu

Hi @Devenkapoor7303, please opt a different language.

**Comment by Devenkapoor7303** [comment]
@ahampriyanshu  I can go with javascript ?

**Comment by Devenkapoor7303** [comment]
@ahampriyanshu  Can I go with java?

**Comment by Samkit-shah** [comment]
Can i work on it for php?

**Comment by Anushka1211300** [comment]
please assign me task

**Comment by ahampriyanshu** [comment]
> please assign me task

Hi @Anushka1211300 , please mention your preferred language.

**Comment by Shahakshar** [comment]
hey, can I make it in java?
stack using an array.

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you please assign me this task for python? thanks!

**Comment by shivam1612tyagi** [comment]
Can i work on it for python?

**Comment by amitsat27** [comment]
Hello @ahampriyanshu  Can i do the task in python?

**Comment by harshitsuthar77731** [comment]
please assign me it in go

**Comment by sahelisaha2k** [comment]
Please assign me in C language

**Comment by SahilKesarwani** [comment]
Hey, I will add more functions in the program in C language. Can you assign it to me?

**Comment by SahilKesarwani** [comment]
Hey, can I change the whole code of the file or should I have to only add new functions... Because my approach is same but I can make the code structure or execution better.
