### ISSUE TITLE
Stack Using Linked List

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1609]
### Type

Data-Structure

### Directory

Data-Structures => Stack => StackUsingLL.extension

### Description

A Stack is a linear data structure that follows the LIFO (Last-In-First-Out) principle.

### Programming Language

- [X] c++
- [X] c
- [x] python
- [x] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [X] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by patrickfoconnor** [comment]
Hey, I would like to help you with this. I have taken data structures through university and have a java file on hand that is a stack using a linkedlist.

**Comment by Sun-0321** [comment]
@ahampriyanshu  Can you please assign this task to me? I will do it in C++

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Can you please assign this task to me? I will do it in C++

Hello @Sun-0321, please a different language.

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Can you please assign this task to me? I will do it in C++

Hi @Sun-0321, please opt a different language.

**Comment by theyup12** [comment]
Can I do for python?

**Comment by ManavArora26** [comment]
Can I do for Javascript?

**Comment by Phoenix6296** [comment]
Can you please assign this task to me as an assignment for hactober fest. I can do it in c++, js, java, c.

**Comment by ahampriyanshu** [comment]
> Can you please assign this task to me as an assignment for hactober fest. I can do it in c++, js, java, c.

Hi @Phoenix6296 , go ahead with c.

**Comment by Phoenix6296** [comment]
okay but can you guide me the process of contributing as I am new to github.

**Comment by Phoenix6296** [comment]
I have done the program but please guide me through the process.

**Comment by subham5230** [comment]
Hey @ahampriyanshu can you please assign me this issue for python, Thanks!

**Comment by rohitkumar9710** [comment]
@ahampriyanshu  I have all the knowledge of stacks being implemented using linked lists in both c and cpp. please assign this task to me.

**Comment by harshitsuthar77731** [comment]
assign me in javascript

**Comment by raazanand** [comment]
heyy @ahampriyanshu! I am surely interested in this problem, Please assign it to me in Java.
