### ISSUE TITLE
Mode

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#161]
**Submission Title**
Mode

**Submission Type**
Maths_And_Stats

**Submission Description**
The number which appears most often in a set of numbers. 
Example: in {6, 3, 9, 6, 6, 5, 9, 3} the Mode is 6 (it occurs most often).

**Folder Related To**
Maths_And_Stats => stats => filename.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by deepdhar** [comment]
I want to contribute in this in CPP

**Comment by coding-sourabh** [comment]
i will contribute in C
please assign it to me

**Comment by Wekananda** [comment]
Hello,
I want to code this on Java. Thanks

**Comment by crenspact02** [comment]
Hey, I wanna do it in cpp.

**Comment by aayushi02agarwal** [comment]
I want to do it in c.

**Comment by dheerajvenugopal96** [comment]
@ahampriyanshu  can i do this using Java

**Comment by adaugochi** [comment]
Hi, @ahampriyanshu I will like to do this in PHP. Can you assign this to me?

**Comment by Avninder99** [comment]
Hi @ahampriyanshu I would like to do this in JavaScript. Please assign it to me ?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
