### ISSUE TITLE
BST from Sorted Array

### ISSUE THREAD

**Issue by shivanshuman021** [ahampriyanshu/algo_ds_101#1623]
### Type

Data-Structure

### Directory

Algorithms => Tree-Algorithm => Sorted-Array-To-BST => Sorted-Array-To-BST.cpp.

### Description

Added code for making a binary search tree from given sorted array

### Programming Language

- [X] c++
- [x] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by subham5230** [comment]
Hey @shivanshuman021 can you please assign me this issue for Java, Thanks!

**Comment by PAARTH2608** [comment]
Can i work on this issue?

**Comment by nimishh7** [comment]
Can you please assign this to me in c++ ?

**Comment by prinsusinghal** [comment]
@shivanshuman021 Assign this to me for JAVA.

**Comment by rupayanxn** [comment]
Hey, I am proficient in C++ and would love to work on this issue.

**Comment by himanshugoldy** [comment]
I have already learned a lot about this topic would like to contribute

**Comment by ahampriyanshu** [comment]
@PAARTH2608 & @himanshugoldy , please mention your preferred language.
@rupayanxn & @prinsusinghal, kindly opt a different language.

**Comment by himanshugoldy** [comment]
i would like to opt for C++



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
10/02/21,
08:45:52 PM

**Comment by disha4u** [comment]
Can I work on this in python

**Comment by himanshugoldy** [comment]
Yes, you can do that.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
10/02/21,
10:16:54 PM

**Comment by PAARTH2608** [comment]
> @PAARTH2608 & @himanshugoldy , please mention your preferred language. @rupayanxn & @prinsusinghal, kindly opt a different language.

C++, Java, python i am familiar with both the languages

**Comment by not4YU5H** [comment]
@ahampriyanshu I would like to implement this in C language. Can you assign it to me?

**Comment by PAARTH2608** [comment]
Can you assign it to me please?

**Comment by dittapandey** [comment]
Can this be assigned to me please in c++
