### ISSUE TITLE
Rat in a Maze Problem

### ISSUE THREAD

**Issue by kirito-udit** [ahampriyanshu/algo_ds_101#1627]
### Type

Algorithm

### Directory

Algorithms =>Backtracking => Rat in a Maze.cpp

### Description

In this problem, there is a given maze of size N x N. The source and the destination location is top-left cell and bottom right cell respectively. Some cells are valid to move and some cells are blocked. If one rat starts moving from start vertex to destination vertex, we have to find that is there any way to complete the path, if it is possible then mark the correct path for the rat.

The maze is given using a binary matrix, where it is marked with 1, it is a valid path, otherwise 0 for a blocked cell.

NOTE: The rat can only move in two directions, either to the right or to the down.

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by PAARTH2608** [comment]
Can I work on this issue?

**Comment by kirito-udit** [comment]
> 
> 
> Can I work on this issue?

**Comment by kirito-udit** [comment]
> 
> 
> Can I work on this issue?

Unfortunately,no
