### ISSUE TITLE
Trie

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1631]
### Type

Data-Structure

### Directory

Data-Structures => Tree => Trie => Trie.extension

### Description

Trie is a non-linear data structure that is used for locating specific keys from within a set. 
**Note :** Just simply demonstrate insert and search operations for a dict.

### Programming Language

- [X] c++
- [X] c
- [X] python
- [x] java
- [ ] kotlin
- [x] javascript
- [x] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by SudipMukhejee** [comment]
I to have fix your issue if you want then assignee

**Comment by ahampriyanshu** [comment]
> I to have fix your issue if you want then assignee

Hi @SudipMukhejee, please mention your preferred language.

**Comment by lakshyamcs16** [comment]
Hi @ahampriyanshu Can I pick this up for Java, Javascript and typescript?

**Comment by SudipMukhejee** [comment]
Javascript i used
