### ISSUE TITLE
Dutch National Flag Problem

### ISSUE THREAD

**Issue by nimishh7** [ahampriyanshu/algo_ds_101#1634]
### Type

Algorithm

### Directory

Algorithms => Array-Algorithm => dutch_national_flag

### Description

Dutch National Flag(DNF) is a  programming problem. The task is to randomly arrange balls of white, red and blue is such a way that balls of the same color are placed together.

### Programming Language

- [X] c++
- [X] c
- [x] python
- [x] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by Aaryanpal** [comment]
Kindly assign this to me @nimishh7

**Comment by lucy2512** [comment]
I would like to work on this in C++.
Will you please assign it to me?

**Comment by ahampriyanshu** [comment]
duplicate of #1241
