### ISSUE TITLE
AVL tree insertion and deletion cpp program

### ISSUE THREAD

**Issue by SaahilSabu** [ahampriyanshu/algo_ds_101#1638]
### Type

Algorithm

### Directory

algo_ds_101=>Algorithms=>Graph-Algorithms

### Description

AVL tree insertion and deletion cpp program

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by ahampriyanshu** [comment]
duplicate of #489

**Comment by prinsusinghal** [comment]
@ahampriyanshu  Assign this to me for JAVA language.
