### ISSUE TITLE
Sum of n²

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#165]
**Submission Title**
Sum of n²

**Submission Type**
Maths_And_Stats

**Submission Description**
The family of natural numbers includes all the counting numbers, starting from 1 till infinity. If n consecutive natural numbers are 1, 2, 3, 4, …, n, then the sum of squared ‘n’ consecutive natural numbers is represented by 12 + 22 + 32 + … + n2.
Σn2 = [n(n+1)(2n+1)]/6

**Folder Related To**
Maths_And_Stats => series => filename.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [x] Swift -
- [x] C# -

**Comment by Himith** [comment]
I want to work on this.Please

**Comment by zahinekbal** [comment]
@Vimlesh-Kumar please assign it to me I would love to contribute on it..
I will apply implementation part in c++..

**Comment by Vimlesh-Kumar** [comment]
> I want to work on this.Please

Go with C

**Comment by Sayantan-world** [comment]
@Vimlesh-Kumar I will love to contribute to this repo,  I will like to add the code python

**Comment by aniketrochwani** [comment]
@Vimlesh-Kumar Please assign it to me. I would like to contribute it in Javascript

**Comment by Wekananda** [comment]
Please assign it to me. I would like to contribute it in Java

**Comment by Samkit-shah** [comment]
Heya,
i would like to gice a try for python

**Comment by Samkit-shah** [comment]
please assign to me for php

**Comment by zahinekbal** [comment]
@Vimlesh-Kumar I added (algo_ds_101=> Maths_And_Stats => Series => SumOf_n^2.C++)#165..(Sum of n^2 in C++)
kindly check my code & review my PR

**Comment by Nirali0029** [comment]
Please assign this to me for  C#.

**Comment by juneadkhan** [comment]
Hi @ahampriyanshu, could I do this in Swift?

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
