### ISSUE TITLE
Open Addressing (Hashing) using Quadratic Probing

### ISSUE THREAD

**Issue by iamHrithikRaj** [ahampriyanshu/algo_ds_101#1654]
### Type

Algorithm

### Directory

Algorithms => Hashing => Open Addressing => quadraticProbingHashingTable.cpp

### Description

**Quadratic probing** is an open addressing scheme in computer programming for resolving hash collisions in hash tables. Quadratic probing operates by taking the original hash index and adding successive values of an arbitrary quadratic polynomial until an open slot is found. 
We look for i^2‘th slot in i’th iteration.  

```txt
let hash(x) be the slot index computed using hash function.  
If slot hash(x) % S is full, then we try (hash(x) + 1*1) % S
If (hash(x) + 1*1) % S is also full, then we try (hash(x) + 2*2) % S
If (hash(x) + 2*2) % S is also full, then we try (hash(x) + 3*3) % S
..................................................
..................................................
```

### Programming Language

- [X] c++
- [ ] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by iamHrithikRaj** [comment]
I would like to contribute on this please assign me. :)

**Comment by Onkar627** [comment]
I would like to contribute to this in java.

**Comment by meghna750** [comment]
Hello @ahampriyanshu ,
I would like to contribute to this topic in python. Kindly assign this to me.
Thanks.
