### ISSUE TITLE
Level Order Traversing in BST

### ISSUE THREAD

**Issue by sreechand2002** [ahampriyanshu/algo_ds_101#1655]
### Type

Algorithm

### Directory

Alogrithm ==> Tree Algorithm ==> level_traversing,cpp

### Description

A algorithm for level order traversing in a BST

### Programming Language

- [X] c++
- [ ] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [x] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nikku971** [comment]
Assign me this in c++

**Comment by sreechand2002** [comment]
> @ahampriyanshu Assign me this in c++

I am working on this after creating

**Comment by sreechand2002** [comment]
@ahampriyanshu please assign it to  me I have already started with this

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Assign me this in c++

Hi @nikku971, kindly opt a different language.

**Comment by Manas0916** [comment]
Hey! can you assign this to me! 
I want to work on this problem in JAVA!
Thank You!

**Comment by karthikhegde05** [comment]
Hey @ahampriyanshu , can you please assign python and javascript version of this problem to me?

Thank you

**Comment by webdesignbydivyansh** [comment]
hello @ahampriyanshu can u assign me this work on C?

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you please assign me this issue in Javascript, Thanks!

**Comment by karthikhegde05** [comment]
> Hey @ahampriyanshu , can you please assign python and javascript version of this problem to me?
> 
> Thank you

@ahampriyanshu , I am already working on javascript version of this problem

**Comment by ignacioespinoso** [comment]
Assign this to me in Swift please

**Comment by vivekarora-02** [comment]
Hey there,
 @ahampriyanshu , can you please assign C and C++ version of this problem to me? I'm already working on it.

Thankyou!

**Comment by Heisenberg-Vardan** [comment]
hey I can solve this using python, can you assign this to me

**Comment by esheetaparulekar** [comment]
Hello, can I work on this issue in php?
