### ISSUE TITLE
Smith-Number (Maths section)

### ISSUE THREAD

**Issue by meghna750** [ahampriyanshu/algo_ds_101#1661]
### Type

Maths

### Directory

Maths=>Number-Theory

### Description

Hello @ahampriyanshu ,
I hope you are going very well.
Here is the description of my issue and plans for submission:
A Smith number is a composite number whose sum of digits is equal to the sum of digits in its prime factorization. It uses the concept of  Sieve of Sundaram. This type of concept help in building a strong base in number theory. I will submit a well commented and justified code and make sure that readers can understand each and every line of my code.

Please assign this issue to me.

Thanks.

### Programming Language

- [X] c++
- [X] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [x] php
- [ ] haskell
- [ ] bash

**Comment by meghna750** [comment]
Hello @ahampriyanshu ,
I have participated in hacktoberfest2021. 
Can you please confirm that my contribution will count in hacktoberfest or not (I will contribute in any case though :)   ).
Thanks.

**Comment by ahampriyanshu** [comment]
> Hello @ahampriyanshu , I have participated in hacktoberfest2021. Can you please confirm that my contribution will count in hacktoberfest or not (I will contribute in any case though :) ). Thanks.

Hi @meghna750, I have participated as a maintainer in hackertoberfest 2021, so once a PR gets merged/approved, it will count as a contribution. Nevertheless, you can track the status of your PR(s) on https://hacktoberfest.digitalocean.com/profile.
Regards @ahampriyanshu :v:

**Comment by U-c0de** [comment]
Hello @ahampriyanshu ,
I have participated in hacktoberfest2021. I want to write the code in Python, php and Java

**Comment by rohitkumar9710** [comment]
@ahampriyanshu , please assign this to me. I would like to write its code in C, C++.

**Comment by meghna750** [comment]
hello @rohitkumar9710 ,
I am already working on this issue with C++, you can work with C.
Thanks!

**Comment by aryan-139** [comment]
javascript => 2 hour
