### ISSUE TITLE
Rearrange an array with alternate high and low elements

### ISSUE THREAD

**Issue by 264pranjal** [ahampriyanshu/algo_ds_101#1678]
### Type

Algorithm

### Directory

Algorithm=>Array-Algorithm

### Description

Given an integer in an array is greater then its left and right integers. No duplications allowed in the array.

### Programming Language

- [X] c++
- [X] c
- [X] python
- [X] java
- [x] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by webdesignbydivyansh** [comment]
Hello, can you assign C++ task to me?

**Comment by 264pranjal** [comment]
I can do code in all 5 languages please assign this task to me

**Comment by pranesh6876** [comment]
@ahampriyanshu please assign me python and c# for this task.

**Comment by ahampriyanshu** [comment]
> Hello, can you assign C++ task to me?

Hi @webdesignbydivyansh, please opt a different language/issue.

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you please assign me this issue for Javascript, Thanks!

**Comment by webdesignbydivyansh** [comment]
Hey, @ahampriyanshu can you assign me in Kotlin?

**Comment by webdesignbydivyansh** [comment]
hello @ahampriyanshu , can you assign this task to me in golang language. I have already started working on it.
