### ISSUE TITLE
Adding Rat in a Maze solution in C++

### ISSUE THREAD

**Issue by noob-26** [ahampriyanshu/algo_ds_101#1681]
### Type

Algorithm

### Directory

Algorithms => Backtracking => Rat in a Maze

### Description

https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1 Solution to the problem Rat in Maze in C++ 

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by U-c0de** [comment]
Hello @ahampriyanshu ,
I have participated in hacktoberfest2021. Please assign me this issue in Python and java

**Comment by bite1392** [comment]
Thanks

**Comment by vivekarora-02** [comment]
Hey there,
@ahampriyanshu, can you please assign me this problem, I'll submit it in C or C++ or both
Thankyou!

**Comment by bite1392** [comment]
Bot Android

در تاریخ یکشنبه ۳ اکتبر ۲۰۲۱،‏ ۹:۵۲ VIVEK ARORA ***@***.***>
نوشت:

**Comment by esheetaparulekar** [comment]
Hello, can I work on this issue in Java?

**Comment by snehashukkla** [comment]
@noob-26 i would like to contribute to this ,could you please assign this to me in C++

**Comment by chehak123** [comment]
can i work on this issue in c++?
