### ISSUE TITLE
Isomorphic String

### ISSUE THREAD

**Issue by pranesh6876** [ahampriyanshu/algo_ds_101#1682]
### Type

Algorithm

### Directory

Algorithms=>String-Algorithm

### Description

Two strings are called isomorphic if there is a one to one mapping possible for every character of 1st string to every character of 2nd string. And all occurrences of every character in 1st string map to same character in 2nd string.

### Programming Language

- [X] c++
- [X] c
- [X] python
- [X] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by pranesh6876** [comment]
@ahampriyanshu please assign me java, python and c# for this code.

**Comment by 264pranjal** [comment]
@ahampriyanshu please assign me c and c++ for this code

**Comment by owaiskhan3** [comment]
Please assign javascript to me!

**Comment by rsh-raj** [comment]
@ahampriyanshu Assign me kotlin for this.

**Comment by AnupamTekale** [comment]
@ahampriyanshu Assign me JavaScript for this.
