### ISSUE TITLE
DSU (Disjoint Set Union)

### ISSUE THREAD

**Issue by MrNaif2018** [ahampriyanshu/algo_ds_101#1686]
### Type

Algorithm

### Directory

Algorithms=>Graph-Algorithms=>DSU=>dsu.ext

### Description

Disjoint set union (or Union Find) is a data structure which is initialized of N sets with 1 element in each, and supports the following operations:
- `union_sets(a, b)` - unite two sets (the set where element a is located, and the set where element b is located)
- `find_set(v)`- return the head (leader) element of the set by one of it's elements

DSU is usually implemented as a tree, where to find head element of a set we go up till the root. 
Two optimisations should be implemented: path shortening (let's say you have a long chain of elements, you can cache the `find_set` calls and connect the deepest elements to higher elements in the tree to reduce traversion time) and ranking system (either via size of a set, or it's rank)

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by MrNaif2018** [comment]
Could I please be assigned for c++ and python? Thanks

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you assign me this issue for Java, Thanks!
