### ISSUE TITLE
Count Inversions in an Array

### ISSUE THREAD

**Issue by rishab1128** [ahampriyanshu/algo_ds_101#1687]
### Type

Algorithm

### Directory

Algorithm => Sorting => Merge Sort => Application of Merge Sort => Count_Inversions.cpp

### Description

Let A[0...n - 1] be an array of n distinct positive integers. If i < j and A[i] > A[j] then the pair (i, j) is called an inversion of A. Given n and an array A our task is to find the number of inversions of A. 

This is a very standard and important problem related to Merge Sort .  

### Programming Language

- [X] c++
- [X] c
- [x] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by rishab1128** [comment]
@ahampriyanshu Please assign me the C and C++ code for this program

**Comment by RaghuvirSingh23** [comment]
Hey! Please assign me the python part for this.
TIA.

**Comment by RaghuvirSingh23** [comment]
@ahampriyanshu I have created a PR. Do checkout!

**Comment by ishar19** [comment]
hey, @ahampriyanshu  assign me the javascript part of this issue.

**Comment by PrakashAditya17** [comment]
I can do this 'Count inversions ' in java language.

**Comment by dittapandey** [comment]
Hey @ahampriyanshu could this be assigned to me in c++?
