### ISSUE TITLE
Search in a  sorted 2-D matrix (BINARY SEARCH)

### ISSUE THREAD

**Issue by rexa0310** [ahampriyanshu/algo_ds_101#1689]
### Type

Algorithm

### Directory

Algorithm =>Searching =>Binary Search=>search_in_2d_matrix.cpp

### Description

 An efficient algorithm that searches for a value in an m x n matrix. This matrix has the following properties:
->Integers in each row are sorted from left to right.
->The first integer of each row is greater than the last integer of the previous row.

This is a problem related to binary search .Its frequently asked in interviews.   

### Programming Language

- [X] c++
- [X] c
- [x] python
- [x] java
- [x] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by rexa0310** [comment]
@ahampriyanshu please assign c and cpp code for this program to me.

**Comment by sairam-kakarla** [comment]
@ahampriyanshu please assign python program to me.

**Comment by Siddhesh4501** [comment]
I can do it in python or Javascript please assigned me any of these

**Comment by raazanand** [comment]
Hey @rexa0310! I would like to work on this problem, please assign it to me in Java.

**Comment by Lakshay-Pruthi** [comment]
solved in JAVA do checkout #1720

**Comment by Ishaan-10** [comment]
Hey @ahampriyanshu ! I can do this in Kotlin. Please assign it to me

**Comment by Pranay-Thakre** [comment]
Hello @ahampriyanshu,  please assign c and cpp code for this program to me.

**Comment by MuhammadFajrian** [comment]
Hello @ahampriyanshu, please assign go program to me.

**Comment by esheetaparulekar** [comment]
Hello, can I work on this issue in C#?

**Comment by DelunRex** [comment]
Java => 1 day
