### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1693]
### Type

Data-Structure

### Directory

Data-Structures => Map => Map.extension

### Description

Map or HashMap or Dict is a data structure that pairs keys to values.
Note : Please don't use any inbuilt library/function.

### Programming Language

- [x] c++
- [ ] c
- [x] python
- [x] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [x] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by deDSeC00720** [comment]
I would like to implement Hashmap in c++.

**Comment by deDSeC00720** [comment]
Hey @ahampriyanshu , I would like to work on hashmap in c++ and java.

**Comment by miguelnietoa** [comment]
Hello everyone, I would like to contribute with Maps on Python and Ruby. 

Question: Is this repo really counting for Hacktoberfest 2021?
Question2: Should I send just one PR with 2 files or one PR per file (Python and Ruby)?

**Comment by harshitsuthar77731** [comment]
i want to contribute in  javascript

**Comment by divyansh1511** [comment]
Hey everyone!! I would like to contribute with maps on cpp.
@ahampriyanshu

**Comment by Ronak55** [comment]
Hey everyone, i would like to contribute in maps on cpp language
@ahampriyanshu

**Comment by Nandini2901** [comment]
Hey, I would like to contribute in maps in cpp language

**Comment by vikashpatel07** [comment]
Hello, I would like to contribute on this issue.
Kindly assign it to me

**Comment by ahampriyanshu** [comment]
> Hey @ahampriyanshu , I would like to work on hashmap in c++ and java.

Hi @deDSeC00720, go ahead with java.

**Comment by divyansh1511** [comment]
I made the PR....
@ahampriyanshu #1875

**Comment by divyansh1511** [comment]
@ahampriyanshu It was done by mistake...please assign me again
