### ISSUE TITLE
Fibonacci Heap

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1694]
### Type

Data-Structure

### Directory

Data-Structures => Tree => Fibonacci-Heap => Fibonacci-Heap.extension

### Description

Fibonacci heap is a data structure for priority queue operations, consisting of a collection of heap-ordered trees.

### Programming Language

- [X] c++
- [X] c
- [x] python
- [ ] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nishantkumar1308** [comment]
please assign this to me I can do it in C++

**Comment by Sameera-Aryasomayajula** [comment]
Can I please implement this in C

**Comment by dittapandey** [comment]
Can this be assigned to me in c++?

**Comment by Heisenberg-Vardan** [comment]
Hi @ahampriyanshu  Can you assign this issue to me, I can solve it in python.

**Comment by harshitsuthar77731** [comment]
assign me in js
