### ISSUE TITLE
Segment tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1697]
### Type

Data-Structure

### Directory

Data-Structures => Tree => Segment-Tree => Segment-Tree.extension

### Description

A segment tree, also known as a statistic tree, is a tree data structure used for storing information about intervals, or segments. It allows querying which of the stored segments contain a given point.

### Programming Language

- [x] c++
- [x] c
- [ ] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by shiladityab24** [comment]
Hey @ahampriyanshu, I want to this issue with java and c++

**Comment by vikashpatel07** [comment]
Hey @ahampriyanshu, I want to work on this issue with python.

**Comment by dittapandey** [comment]
Hey @ahampriyanshu, I want to work on this issue in c++

**Comment by shiladityab24** [comment]
@dittapandey I am already working on c++ and java and going to complete the code within today

**Comment by Tri-via** [comment]
hey @ahampriyanshu  , i want to contribute a struct in C++ for the segment tree to provide minimum element
