### ISSUE TITLE
Splay Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1698]
### Type

Data-Structure

### Directory

Data-Structures => Tree => Splay-Tree => Splay-Tree.extension

### Description

A splay tree is a binary search tree with the additional property that recently accessed elements are quick to access again.

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nishantkumar1308** [comment]
please assign it to me. i can do it in c++

**Comment by varnaa** [comment]
@ahampriyanshu Hi, i'd like to work on this issue for java.
