### ISSUE TITLE
Red-Black-Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1699]
### Type

Data-Structure

### Directory

Data-Structures => Tree => Red-Black-Tree => Red-Black-Tree.ext

### Description

A red–black tree is a kind of self-balancing binary search tree. Each node stores an extra bit representing "color", used to ensure that the tree remains balanced during insertions and deletions.

### Programming Language

- [X] c++
- [X] c
- [X] python
- [X] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by luckysharma05** [comment]
please assign it to me

**Comment by ahampriyanshu** [comment]
> please assign it to me

Hi @luckysharma05, kindly mention your preferred language.

**Comment by luckysharma05** [comment]
my preferred language is c++

**Comment by 22Niharika** [comment]
hello @ahampriyanshu can you assign this to me, i would like to work in c++ language

**Comment by subham5230** [comment]
Hey @ahampriyanshu  can you assign me this issue for Javascript, Thanks!

**Comment by gargi111** [comment]
Hey!  please assign this to me,my preferred language is python.

**Comment by 2309harshit** [comment]
Hey can you please assign this issue to me. I think I can do this.
Thanks in anticipation!
