### ISSUE TITLE
I would like to add some programming/puzzle books pdf in the resources section

### ISSUE THREAD

**Issue by amishaagarwal1998** [ahampriyanshu/algo_ds_101#170]

**Comment by amishaagarwal1998** [comment]
Please assign this to me!

**Comment by coding-sourabh** [comment]
please assign this to me

**Comment by ahampriyanshu** [comment]
Hi @amishaagarwal1998 and @coding-sourabh, please make sure to not to push any copyrighted material 😅

**Comment by amishaagarwal1998** [comment]
Sure. Thanks!

**Comment by amishaagarwal1998** [comment]
@coding-sourabh I was thinking it would be better to merge programming books in one folder!

**Comment by ahampriyanshu** [comment]
> @coding-sourabh I was thinking it would be better to merge programming books in one folder!

Done 👍🏽
