### ISSUE TITLE
2-3 Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1701]
### Type

Data-Structure

### Directory

Data-Structures => Tree => 23Tree => 23Tree.extension

### Description

A 2–3 tree is a tree data structure, where every node with children has either two children and one data element or three children and two data elements. 

### Programming Language

- [X] c++
- [X] c
- [X] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by berry120** [comment]
Hey, could I take this for Java?

**Comment by Sameera-Aryasomayajula** [comment]
Can I work on the C++ implementation if this

**Comment by ahampriyanshu** [comment]
> Can I work on the C++ implementation if this

Hi @Sameera-Aryasomayajula, please opt a different language/issue.

**Comment by Heisenberg-Vardan** [comment]
I can solve this in python can u assign this to me

**Comment by ManavArora26** [comment]
Can i work for Javascript?? @ahampriyanshu
