### ISSUE TITLE
Generic Tree

### ISSUE THREAD

**Issue by nikku971** [ahampriyanshu/algo_ds_101#1708]
### Type

Data-Structure

### Directory

Algorithm => Trees => Generic Tree implementation

### Description

Generic trees are a collection of nodes where each node is a data structure that consists of records and a list of references to its children(duplicate references are not allowed). Unlike the linked list, each node stores the address of multiple nodes. Every node stores address of its children and the very first node’s address will be stored in a separate pointer called root.

### Programming Language

- [X] c++
- [x] c
- [ ] python
- [ ] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [x] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nikku971** [comment]
@ahampriyanshu assign me this in c++.I am working on this

**Comment by ignacioespinoso** [comment]
Can you assign this to me in swift?

**Comment by not4YU5H** [comment]
@ahampriyanshu can you assign this to me in C?

**Comment by divyansh1511** [comment]
can u assign this to me... @ahampriyanshu in cpp.

**Comment by SuperAayush** [comment]
@ahampriyanshu Please assign this to me in JAVA.

**Comment by SuperAayush** [comment]
I have already made a PR for java and can also contribute using JS so please assign me for JS as well

**Comment by Abhishek5002443** [comment]
Hey @ahampriyanshu, can you assign me in python.

**Comment by divyansh1511** [comment]
@ahampriyanshu I made the PR for it....you can merge it...

**Comment by SuperAayush** [comment]
@ahampriyanshu please do assign me for javascript as well.
