### ISSUE TITLE
Tower-of-Hanoi

### ISSUE THREAD

**Issue by sudhanshupatel-dev** [ahampriyanshu/algo_ds_101#1723]
### Type

Algorithm

### Directory

Algorithm => Recursion => Tower-of-Hanoi.py

### Description

One of the most popular problem of all time tower of hanoi

### Programming Language

- [ ] c++
- [ ] c
- [X] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by sudhanshupatel-dev** [comment]
@ahampriyanshu assign me this in python please.

**Comment by sarthakdelori** [comment]
Assign me this in C++.

**Comment by ahampriyanshu** [comment]
duplicate of #697, #1707 and #1706 !
Please follow contributing guidelines.
