### ISSUE TITLE
Java Collection : LinkedList

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1727]
### Type

Collection

### Directory

Collection => LinkedList => LinkedList.java

### Description

Just declare the data structure, take the input dynamically, demonstrate some inbuilt methods.

### Programming Language

- [ ] java

**Comment by ZohaibSoomro** [comment]
Assign it to me Sir  i will do it in java.

**Comment by SuperAayush** [comment]
Please assign it to me.

**Comment by PrakashAditya17** [comment]
I can do in java

**Comment by AnupamTekale** [comment]
Can you please assign it to me? I can do it elegantly in java.

**Comment by AnupamTekale** [comment]
JAVA => 2 hours.
