### ISSUE TITLE
Binary Lifting For LCA on Trees

### ISSUE THREAD

**Issue by MojoAlpha** [ahampriyanshu/algo_ds_101#1733]
### Type

Algorithm

### Directory

Algorithms=>Tree-Algorithm=>Binary_Lifting

### Description

Binary lifting is a technique which is used to find the LCA of two nodes in a tree in O(logn) time. This technique uses some a precomputation time of O(nlogn).

### Programming Language

- [X] c++
- [ ] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by MojoAlpha** [comment]
Could you assign this issue to me for c++?

**Comment by PrakashAditya17** [comment]
I can do this in Java. Do assign if required

**Comment by Heisenberg-Vardan** [comment]
i can do this in python can u assign this to me

**Comment by shubhamhere** [comment]
I can do this in C++. Do assign if required

**Comment by vikkastiwari** [comment]
Please assign me this task I will do it in Javascript.
Thank You

**Comment by Karssido** [comment]
I can do this in C#. Please assign me this issue.

**Comment by iamrk09** [comment]
javascript=>1Day
