### ISSUE TITLE
Median

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#174]
**Submission Title**
Median

**Submission Type**
Maths_And_Stats

**Submission Description**
 Median is a value separating the higher half from the lower half of a data sample, a population or a probability distribution. 

**Folder Related To**
Maths_And_Stats => Stats => Median.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by aayushi02agarwal** [comment]
I'm working on this

**Comment by crenspact02** [comment]
Hey! I want to work on this using C.

**Comment by Wekananda** [comment]
Hello, please assign me. I want to work this on Javascript or Typescript

**Comment by AnkitJuyal009** [comment]
Hey! I would like to work this on Java. 
Thanks!

**Comment by LUCIFER-dev-king** [comment]
Hi, @ahampriyanshu can you assign me on this. I'll do this task in C++.

**Comment by aniketrochwani** [comment]
@ahampriyanshu Please assign this to me. I would like to contribute to it in python

**Comment by LUCIFER-dev-king** [comment]
@ahampriyanshu looks like median for c++ is already finished.

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu looks like median for c++ is already finished.

🤦🏽 You can opt a different language/issue.

**Comment by SalmonKing72** [comment]
I would like to contribute to this in Ruby.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
