### ISSUE TITLE
Standard Deviation

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#177]
**Submission Title**
Standard Deviation

**Submission Type**
Maths_And_Stats

**Submission Description**
The standard deviation is a measure of the amount of variation or dispersion of a set of values

**Folder Related To**
Maths_And_Stats => Stats => Standard_Deviation.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [x] Swift -
- [ ] C# -

**Comment by LUCIFER-dev-king** [comment]
Assign me on this, I would like to contribute in c++.

**Comment by Wekananda** [comment]
Hello,
I want to work this on Java. Thanks

**Comment by cuber485** [comment]
Assign me, I would like to contribute in C

**Comment by ashish-garg18** [comment]
Assign it to me for Python

**Comment by Esoiya** [comment]
@ahampriyanshu please assign it to me for python

**Comment by dipankargoswami** [comment]
@ahampriyanshu , can I pick up swift please ?

**Comment by zerox029** [comment]
I would like to work on the javascript version
Thank you

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
