### ISSUE TITLE
Disjoint Set

### ISSUE THREAD

**Issue by akash435** [ahampriyanshu/algo_ds_101#1784]
### Type

Data-Structure

### Directory

Data-Structure => Disjoint-Set => disjoint_set.cpp

### Description

Here will be adding a new data structure in Data Structure folder i.e. Disjoint Set data structure.
Disjoint Set is an advanced data structure and I will be give the implementation in C++ language.

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by himanshukaushal123** [comment]
please sir assign this to me... i will do it in C++

**Comment by akash435** [comment]
@ahampriyanshu can i work on this in c++?

**Comment by Heisenberg-Vardan** [comment]
@ahampriyanshu I can solve this in python, can you please assign this to me

**Comment by Tanushreesuthar** [comment]
please assign me in javascript

**Comment by PrakashAditya17** [comment]
I can do disjoint set in java

**Comment by yash49** [comment]
Java => 1 Day
