### ISSUE TITLE
two pointer for sorted array in c++ 

### ISSUE THREAD

**Issue by KshitijSabale** [ahampriyanshu/algo_ds_101#1787]
### Type

Algorithm

### Directory

Algorithm => Array-Algorithm => two-pointer-sorted-array.cpp

### Description

two find whether there is a pair present in the sorted array we use two pointer technique to achieve it in o(n) - TC and o(1) - SC . 

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [x] java
- [x] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by KshitijSabale** [comment]
CPP => 1 day

**Comment by vaishnavyogesh** [comment]
HI Kshitij!
is it two sum problem?

**Comment by vaishnavyogesh** [comment]
Kotlin => 1 Day

**Comment by AnupamTekale** [comment]
Java => 4 hours.

**Comment by harshitsuthar77731** [comment]
python => 1hour
