### ISSUE TITLE
Two Sum(2-sum) Problem

### ISSUE THREAD

**Issue by vaishnavyogesh** [ahampriyanshu/algo_ds_101#1789]
### Type

Algorithm

### Directory

Algorithms => Array-Algorithm => twoSum.cpp

### Description

Well known two sum problem to find whether a pair of elements exist in the given array which adds up to the given target value.
Approaches:
1 -> Brute force : Check all the pairs TC: O(n*n) SC: O(1)
2 -> Better: Sorting with two pointers TC: O(nlogn) SC: O(n)
3 -> Optimal: Using a HashMap TC: O(n) SC: O(n)

### Programming Language

- [X] c++
- [x] c
- [ ] python
- [ ] java
- [X] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by 2309harshit** [comment]
Hey can you please assign this issue to me. I think I can do this.
Thanks in anticipation!

**Comment by vaishnavyogesh** [comment]
You can add 3sum and 4sum which would be contained in this issue :)

**Comment by iamrk09** [comment]
Python=>1Day

**Comment by esheetaparulekar** [comment]
Can I work on this issue in Java?

**Comment by vaishnavyogesh** [comment]
Sure! just add Java => (time you would require to complete the task)

**Comment by esheetaparulekar** [comment]
Java =>1 day

**Comment by khushipunia21** [comment]
@vaishnavyogesh I am interested to work on this issue in C++.

**Comment by vaishnavyogesh** [comment]
I've already taken c++ :)

**Comment by AnupamTekale** [comment]
JavaScript => 2 hours

**Comment by Nishit278** [comment]
@vaishnavyogesh Can you please assign me 3 sum problem and please tell me how can I upload the solution of 3 sum ? I mean under which directory ? CPP => 2 hours

**Comment by Heisenberg-Vardan** [comment]
Can I add the c code for this?

**Comment by reyadkhan** [comment]
I want to do it in php please.

**Comment by gattsu997** [comment]
Python => 1 hour
