### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by Singh-Aishwarya** [ahampriyanshu/algo_ds_101#18]
**Submission Title**
Bubble Sort

**Submission Type**
Algo

**Submission Description**
Bubble sort is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.

**Contributors**
- [x]  C++ - @bhagya05 
- [x]  C - @Abantika20 
- [x]  Python - 
- [x] Java - @Singh-Aishwarya 
- [x] JavaScript -
- [ ] Golang -

**Comment by Singh-Aishwarya** [comment]
Assign this task to me in Java @ahampriyanshu

**Comment by bhagya05** [comment]
I can do c++

**Comment by Harshi7016** [comment]
Can I work on Javascript on the same?
Thanks

**Comment by HarshUdai** [comment]
hey @Singh-Aishwarya , i can do the bubble sort implementation in Python, can you assign this to me

**Comment by Abantika20** [comment]
I wish to do it in C . Please assign me

**Comment by hemangdtu** [comment]
I wish to do it in Python. Please assign me.

**Comment by ahampriyanshu** [comment]
@all-contributors please add @bhagya05  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @HarshUdai  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Abantika20  for code

**Comment by zahinekbal** [comment]
@Singh-Aishwarya Can i contribute in this issues In C++ STL...

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
