### ISSUE TITLE
Tribonacci Numbers

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1807]
### Type

Maths

### Directory

Maths => Number-Theory => Tribonacci-Numbers => Tribonacci-Numbers.ext

### Description

The tribonacci series is a generalization of the Fibonacci sequence where each term is the sum of the three preceding terms.
Eg => 0, 0, 1, 1, 2, 4, 7, 13, 24, 44, 81 ...

### Programming Language

- [x] c++
- [x] c
- [x] python
- [x] java
- [x] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by B1TSH3LL** [comment]
I Can Work On This Issue If You Like :) Just Remeber to add label hacktoberfest and hacktoberfest-accepted in small letters.

**Comment by Rockarya** [comment]
Hey @ahampriyanshu, can u assign this task to me? I will do this in both C++ and Python => 1 Day.

**Comment by Nishit278** [comment]
C++ => 3 hours

**Comment by AnupamTekale** [comment]
java => 2 hours

**Comment by Heisenberg-Vardan** [comment]
Hey @ahampriyanshu  Can I solve this in Python?

**Comment by ahampriyanshu** [comment]
> Hey @ahampriyanshu Can I solve this in Python?

Hi @Heisenberg-Vardan, please opt a different language/issue.

**Comment by Heisenberg-Vardan** [comment]
@ahampriyanshu  How about C?

**Comment by Nishit278** [comment]
@ahampriyanshu Hey, can you create an issue for trapping rainwater problem ? If its not done already.

**Comment by AnupamTekale** [comment]
@ahampriyanshu  Hey can you create Tribonacci-Numbers  Folder in Number-Theory.

**Comment by Anubha13kumari** [comment]
I want to work on this please assign me @ahampriyanshu

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Hey can you create Tribonacci-Numbers Folder in Number-Theory.

https://github.community/t/add-a-folder/2304

**Comment by vaishnavyogesh** [comment]
Kotlin => 1 Hour

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu are you the first three elements are 0, 0, 1 and not 0, 1 and 1? or doesn't really matter?

https://en.wikipedia.org/wiki/Generalizations_of_Fibonacci_numbers#:~:text=The%20first%20few%20tribonacci%20numbers,of%20Species%20by%20Charles%20R.

**Comment by anandamideShakyan** [comment]
@ahampriyanshu I would like to work on this issue in javascript. please assign me .
Thank You

**Comment by B1TSH3LL** [comment]
C++ => 1 Day 👍 Assign It To Me

**Comment by JonasWoeg** [comment]
Haskell => 2 Hours
