### ISSUE TITLE
Trapping Rainwater Problem (DP)

### ISSUE THREAD

**Issue by Nishit278** [ahampriyanshu/algo_ds_101#1809]
### Type

Algorithm

### Directory

Algorithm => Dynamic-Programming => TrappingWater => TrappingWater.cpp

### Description

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nimishh7** [comment]
Hi @ahampriyanshu, Can you please assign this to me in working with c++ ?

**Comment by Nishit278** [comment]
C++ => 1 hour

**Comment by chehak123** [comment]
can i work on this issue in c++?

**Comment by harshitsuthar77731** [comment]
assign me in js =>1 hour

**Comment by esheetaparulekar** [comment]
Can I work on this issue in Java?
Java => 1 day

**Comment by snehaa1989** [comment]
python=>1 hr
