### ISSUE TITLE
Sum of n³

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#181]
**Submission Title**
Sum of n³

**Submission Type**
Maths_And_Stats

**Submission Description**
Describe the Algo/DS/STL

**Folder Related To**
Maths_And_Stats => series => filename.extension

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by pranjalkumar153** [comment]
can you please assign this to me. I am ready to do this in C++,C, Python and java and JavaScript. Will explain the code nicely with comments and also the mathematical theory behind it. the solution will be O(1) in terms of time complexity.

**Comment by crenspact02** [comment]
Hey! I want to work on this!

**Comment by ahampriyanshu** [comment]
> Hey! I want to work on this!

Hi @crenspact02 , please mention your preffered language.

**Comment by ahampriyanshu** [comment]
> can you please assign this to me. I am ready to do this in C++,C, Python and java and JavaScript. Will explain the code nicely with comments and also the mathematical theory behind it. the solution will be O(1) in terms of time complexity.

@pranjalkumar153 I have just updated folder's directory and pull request template.So , I suggest you to sync your forked repo with the master one to avoid any future merge conflicts.

**Comment by Samkit-shah** [comment]
i would like to contribute for php

**Comment by geoffgeorgein** [comment]
I shall work on python  to implement a short and precise code. Please assign me this.

**Comment by pranjalkumar153** [comment]
Excuse me sir, I am sorry I wont be able to complete the assigned task. Please assign it to some other contributor.

**Comment by prajwlr** [comment]
Hey @ahampriyanshu ! It seems from the comment above that @pranjalkumar153  will not be contributing in c++. Please assign it to me. I'll send a PR shortly.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
