### ISSUE TITLE
Trapping Rainwater Problem (Two Pointer)

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1812]
### Type

Algorithm

### Directory

Algorithm => Two-Pointer => TrappingWater => TrappingWater.cpp

### Description

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

### Programming Language

- [x] c++
- [ ] c
- [x] python
- [x] java
- [ ] kotlin
- [x] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nishantkumar1308** [comment]
please assign it to me I will do in c++

**Comment by SuperAayush** [comment]
Please assign me this for JAVA

**Comment by Nishit278** [comment]
@ahampriyanshu I uploaded the solution under issue #1809 which I created, what should I do ?

**Comment by chehak123** [comment]
pls assign it to me in c++

**Comment by harshitsuthar77731** [comment]
assign me in python

**Comment by harshitsuthar77731** [comment]
=>1 hour

**Comment by esheetaparulekar** [comment]
Can I work on this issue in Javascript?
Javascript => 1 day

**Comment by vaishnavyogesh** [comment]
Kotlin => 1 Hour

**Comment by gattsu997** [comment]
C => 1 Hour

**Comment by Rohitshailesh43** [comment]
python=>1 day
