### ISSUE TITLE
Prim's MST

### ISSUE THREAD

**Issue by nikku971** [ahampriyanshu/algo_ds_101#1823]
### Type

Algorithm

### Directory

algo_ds_101=>Algorithms=>Graph-Algorithms=>Prim's_MST

### Description

algorithm for Prim's Minimum spanning tree

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by nikku971** [comment]
@ahampriyanshu assign me this in c++

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu assign me this in c++
https://github.com/ahampriyanshu/algo_ds_101#how-to-contribute

**Comment by aryan-139** [comment]
java => 1 day

**Comment by aryan-139** [comment]
java => 1 day

**Comment by snehaa1989** [comment]
python => 1 hr

**Comment by kritika-sharma130** [comment]
java=>3hrs
