### ISSUE TITLE
Pattern-Searching (Rabin-Karp Algorithm)

### ISSUE THREAD

**Issue by tanuj1811** [ahampriyanshu/algo_ds_101#1827]
### Type

Algorithm

### Directory

Algorithms => String-Algorithm => Pattern-Searching

### Description

This algo. will return all the patterns (string) present inside the given String[]

### Programming Language

- [x] c++
- [x] c
- [x] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash
### Comment In The Stated Syntax
![6](https://user-images.githubusercontent.com/54521023/135754330-be6aa099-2ccf-44c7-aebe-e9348c23ae82.png)

* ``Language In Which You Will Contribute => Time Required By You To Push The Changes``
* Ask for the issue that you plan to complete.
* Do not wait to get assigned.
* Please try to push the changes in less than or equal to the stated(by you only) time period. Failing to do that, your comment will be discarded and the language will be made available to other participants.
* Try to avoid any casual communication.

**Comment by tanuj1811** [comment]
Java => 4hrs

**Comment by harsh6975** [comment]
c++ => 1hr

**Comment by harshitsuthar77731** [comment]
assign me in pyhton => 1hr

**Comment by snehaa1989** [comment]
aiign me c++

**Comment by snehaa1989** [comment]
assign me c
