### ISSUE TITLE
Bridges in Graph

### ISSUE THREAD

**Issue by tanuj1811** [ahampriyanshu/algo_ds_101#1841]
### Type

Algorithm

### Directory

Algorithms => Graph-Algorithms

### Description

Bridge -> A bridge is an edge removing which increases number of disconnected components. 

### Programming Language

- [x] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by absolute-looser** [comment]
I would like to do this in c++

**Comment by shakil12-coder** [comment]
I am good with grapg problem ,I can do this ,please assign me

**Comment by shakil12-coder** [comment]
I am good with graph problem ,I can do this ,please assign me

**Comment by absolute-looser** [comment]
Hey @ahampriyanshu I have a query do i have to make my own branch or i can commit through the branch you made by your name.

**Comment by shakil12-coder** [comment]
as you wish
