### ISSUE TITLE
Rotate a matrix by 90 degree in clockwise direction

### ISSUE THREAD

**Issue by tanuj1811** [ahampriyanshu/algo_ds_101#1849]
### Type

Algorithm

### Directory

Algorithms => Matrix-Algorithm

### Description

Get a square matrix, turn it by 90 degrees in a clockwise direction.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by ahampriyanshu** [comment]
duplicate of #1848
