### ISSUE TITLE
Rotate a matrix by 90 degree in anti-clockwise direction (Inplace)

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#1850]
### Type

Algorithm

### Directory

Algorithm => Matrix-Algorithm => Rotate-Anti-ClockWise => Rotate-Anti-ClockWise.ext

### Description

Rotate a matrix by 90 degree in anti clockwise direction in constant space.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by srr2k21** [comment]
Hello, can I work on this issue? Thanks

**Comment by Ace117MC** [comment]
Can, I work on this issue in C++ ? @ahampriyanshu

**Comment by nimishh7** [comment]
C++ => 2 hrs

**Comment by webdesignbydivyansh** [comment]
hey @ahampriyanshu can you assign this issue to me in C++?
I am already working on it.

**Comment by vatsalya-gupta** [comment]
Java => 1 Day
