### ISSUE TITLE
Search a 2D Matrix (sorted from left to right)

### ISSUE THREAD

**Issue by tanuj1811** [ahampriyanshu/algo_ds_101#1853]
### Type

Algorithm

### Directory

Algorithm => Matrix-Algorithm

### Description

Need Efficient solution

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

### Comment In The Stated Syntax
![6](https://user-images.githubusercontent.com/54521023/135754330-be6aa099-2ccf-44c7-aebe-e9348c23ae82.png)

* ``Language In Which You Will Contribute => Time Required By You To Push The Changes``
* Ask for the issue that you plan to complete.
* Do not wait to get assigned.
* Please try to push the changes in less than or equal to the stated(by you only) time period. Failing to do that, your comment will be discarded and the language will be made available to other participants.
* Try to avoid any casual communication.

**Comment by srr2k21** [comment]
Can u assign this issue to me? Thank you

**Comment by shaurya5** [comment]
Java => 1 Day

**Comment by Tri-via** [comment]
c++ => 1 day

**Comment by gattsu997** [comment]
Python=>2 hours
