### ISSUE TITLE
Binary Insertion Sort

### ISSUE THREAD

**Issue by kinshukdua** [ahampriyanshu/algo_ds_101#188]
**Submission Title**
Binary Insertion Sort

**Submission Type**
Algorithm

**Submission Description**
Implementing Insertion Sort but using binary search to find the insertion point to improve time complexity.

**Folder Related To**
Algorithms => Sorting_Algorithms => Insertion_Sort

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [x] Swift -
- [ ] C# -

**Comment by kinshukdua** [comment]
I would like to work on this issue using Python. Kindly assign it to me.

**Comment by DEEPAKSINGHRAGHAV** [comment]
@ahampriyanshu  Could you please assign the task for Javascript.

**Comment by ahampriyanshu** [comment]
Hi @kinshukdua , please make a new folder ``Binary_Insertion_Sort`` in the ``Sorting_Algorithms`` sub folder

**Comment by juneadkhan** [comment]
Hi, @ahampriyanshu. Could I be assigned the task for Java?

**Comment by kinshukdua** [comment]
> Hi @kinshukdua , please make a new folder `Binary_Insertion_Sort` in the `Sorting_Algorithms` sub folder

Yes sure.

**Comment by LUCIFER-dev-king** [comment]
Hi, @ahampriyanshu  can you assign me on this. I'll do this task in C++.

**Comment by Heisenberg-Vardan** [comment]
Can you please assign this task to me , I would implement it in C

**Comment by juneadkhan** [comment]
Hi @ahampriyanshu looks like Java has already been completed. I can take Swift instead. Could you reassign please?

**Comment by LUCIFER-dev-king** [comment]
> Hi, @ahampriyanshu can you assign me on this. I'll do this task in C++.

@ahampriyanshu  Merge the PR.

**Comment by ahampriyanshu** [comment]
Hi @juneadkhan , go ahead with swift

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
