### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#2]
**Submission Title**
Linear Search

**Submission Type**
Algorithm

**Submission Description**
A linear search or sequential search is a method for finding an element within a list. 

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] Golang -

**Comment by Pranjal81** [comment]
Please assign this task to me. @ahampriyanshu

**Comment by ahampriyanshu** [comment]
> Please assign this task to me. @ahampriyanshu

What is your preffered language @Pranjal81

**Comment by Pranjal81** [comment]
> 
> 
> > Please assign this task to me. @ahampriyanshu
> 
> What is your preffered language @Pranjal81

it was C++ but as it is assigned I can do it in C.

**Comment by Pranjal81** [comment]
#4

**Comment by Harshi7016** [comment]
Can I work on Javascript on this?
Thanks

**Comment by hemangdtu** [comment]
Please assign it to me for Python.

**Comment by Harshi7016** [comment]
Can I go ahead with adding the js file, or should I wait till I get assigned?
I am bit confused
Thanks

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Singh-Aishwarya

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Singh-Aishwarya  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Pranjal81 @Vimlesh-Kumar @Harshi7016 @hemangdtu  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @hemangdtu for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Harshi7016 for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @ahampriyanshu  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Singh-Aishwarya  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Singh-Aishwarya for code

**Comment by hanyangl** [comment]
@all-contributors can you assign linear search in go to me?

**Comment by hemangdtu** [comment]
@ahampriyanshu I have made a PR. Please check.

**Comment by hemangdtu** [comment]
> @ahampriyanshu I have made a PR. Please check.

All conflicts are now resolved.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
