### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#20]
**Submission Title**
Merge Sort

**Submission Type**
Algo

**Submission Description**
Merge sort is one of the most efficient sorting algorithms. It works on the principle of Divide and Conquer.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] Golang -

**Comment by Vimlesh-Kumar** [comment]
Please assign this task to me in C++ @ahampriyanshu

**Comment by abhaybhatt** [comment]
@Vimlesh-Kumar  assign this to me for java?

**Comment by dindatiwi** [comment]
ill do the javascript one
assigned me pls

**Comment by dindatiwi** [comment]
https://github.com/ahampriyanshu/algo_ds_101/pull/98

added

**Comment by Sayantan-world** [comment]
Can I do this in C?

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
