### ISSUE TITLE
Golomb Sequence

### ISSUE THREAD

**Issue by Mihir2527** [ahampriyanshu/algo_ds_101#205]
**Submission Title**
Golomb Sequence

**Submission Type**
Algorithm

**Submission Description**
It is an algorithm based on dynamic programming. The Golomb sequence is a non-decreasing integer sequence where n-th term is equal to number of times n appears in the sequence. This is the Python implementation.

**Folder Related To**
Algorithms => Dynamic_Programming => Golomb_Sequence =>Golomb.py

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by LUCIFER-dev-king** [comment]
Hi @ahampriyanshu. Assign me on this, I would like to contribute in c++.

**Comment by Mihir2527** [comment]
I have added the implementation of Golomb Sequence in Python

**Comment by firehawk23** [comment]
Hi @ahampriyanshu. Assign this to me i would like to contribute in java.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
