### ISSUE TITLE
Knapsack problem

### ISSUE THREAD

**Issue by shreyrai99** [ahampriyanshu/algo_ds_101#214]
**Submission Title**
0-1 Knapsack problem

**Submission Type**
Algorithm

**Submission Description**
Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack.

**Folder Related To**
Algorithms => Dynamic_Programming => 0-1 Knapsack Problem  =>knapsack_problem_0_1.cpp

**Submission Title**
Bubble Sort/AVL Graph/Vector

**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
Describe the Algo/DS/STL

**Folder Related To**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Samkit-shah** [comment]
Please assign it to me,i would like to contribute

**Comment by ahampriyanshu** [comment]
Hi @Samkit-shah , please mention your preffered language.

**Comment by Samkit-shah** [comment]
> Hi @Samkit-shah , please mention your preffered language.

I have made the pr using C++
please review

**Comment by Heisenberg-Vardan** [comment]
Can I implement this using python
@ahampriyanshu

**Comment by cuber485** [comment]
@ahampriyanshu I would like to implement this using JAVA.

**Comment by jaskirankaur51** [comment]
Please assign me this issue for C language and JavaScript

**Comment by Danish-Mahajan** [comment]
please assign me this for c languaage

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
