### ISSUE TITLE
Sieve of Eratosthenes method

### ISSUE THREAD

**Issue by subhayuroy** [ahampriyanshu/algo_ds_101#221]
**Submission Title**
Sieve of Eratosthenes

**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
This is the fastest method to find the number of Prime numbers to a certain limit.

**Folder Related To**
Maths_And_Stats => Algebra => Sieve of Eratosthenes => SieveOfEratosthenes.py

**Contributors**
- [x]  Python -
- [x]  C++ -
- [x]  C -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by subhayuroy** [comment]
Thank you for assigning me!

**Comment by chinmaym07** [comment]
I can do it in C++ . Can you assign it to me

**Comment by alkatrivedi** [comment]
I would like to implement in C.

**Comment by Hashrin** [comment]
I can implement it in Java and C#. Can you please assign those languages to me?

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
