### ISSUE TITLE
Merge Intervals

### ISSUE THREAD

**Issue by Sushantrimurti** [ahampriyanshu/algo_ds_101#229]
**Submission Title**
Merge Intervals

**Submission Type**
Algorithm/Data Structures

**Submission Description**
Given a collection of intervals, merge all overlapping intervals.

**Folder Related To**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -

**Comment by sathiyajith** [comment]
Let me work on this.

**Comment by akshithsriram** [comment]
Hi @ahampriyanshu, I would like to work on it in C. Please assign it to me. Thank you!

**Comment by KKghub** [comment]
let me work on the C++ version of it :)

**Comment by jyotiGambhir** [comment]
Can I work on this issue? I would like to add in CPP.

**Comment by dheerajodha** [comment]
Hey! Can I work on this issue? I'd love to contribute code in Java.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
