### ISSUE TITLE
Anagram of two strings in java

### ISSUE THREAD

**Issue by ashivamj2105** [ahampriyanshu/algo_ds_101#232]
**Submission Title**
Anagram

**Submission Type**
Algorithm

**Submission Description**
Anagram of two strings

**Folder Related To**
Algorithm=> String_Algorithms=> anagram.java

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by ARYAMANSHIVAMJHA** [comment]
Assign me for this task please.

**Comment by Nirali0029** [comment]
Assign me this task for python

**Comment by anantbharti30** [comment]
Assign me for C++

**Comment by ashish-garg18** [comment]
Assign me this task for java and c language

**Comment by ashish-garg18** [comment]
Assign me this for c, c++, javascript, java

**Comment by OfiliPatrick** [comment]
Assign me this for python

**Comment by jaskirankaur51** [comment]
Kindly assign me this task for PHP please

**Comment by AlxGration** [comment]
Assign me this task for С# pls)

**Comment by ahampriyanshu** [comment]
> Assign me this for python

Hi @OfiliPatrick, please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
@ashish-garg18  go ahead with C, C++, JS and Java
@jaskirankaur51 go ahead with php

**Comment by atorr5555** [comment]
Hi, can i do it in C? Or is there someone already doing it?

**Comment by beccadaniel** [comment]
Can I get assigned this for Swift?

**Comment by chinmaym07** [comment]
Hi can i do it in Javascript.?

**Comment by beccadaniel** [comment]
I just created a PR for anagrams using the Swift Programming Language @ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
