### ISSUE TITLE
Trie Insertion && Trie Search

### ISSUE THREAD

**Issue by CormacKrum** [ahampriyanshu/algo_ds_101#243]
**Submission Title**
Trie Insertion && Trie Search

**Submission Type**
Algorithm

**Submission Description**
Describe the Algo/DS/STL

**Folder Related To**
Algorithm => Search_Algorithm => Trei_Search => Filename.extension

**Contributors**
- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by onkargagare** [comment]
Please assign me for Java implementation

**Comment by sbhavya18** [comment]
I can implement this in C. Kindly assign me.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
