### ISSUE TITLE
Add Code for LCS of 3 Strings

### ISSUE THREAD

**Issue by snape-here** [ahampriyanshu/algo_ds_101#245]
**Submission Title**
LCS of 3 strings

**Submission Type**
Algorithms

**Submission Description**
DP algorithm. Find LCS of 3 strings

**Folder Related To**
Algorithms => Dynamic_Programmin

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by CormacKrum** [comment]
Please Assign me for this Algo in Java

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
