### ISSUE TITLE
GCD

### ISSUE THREAD

**Issue by taresh18** [ahampriyanshu/algo_ds_101#250]
**Submission Title**
GCD

**Submission Type**
Maths_And_Stats

**Submission Description**
Finding GCD of two numbers using Euclidean algirithm.

**Folder Related To**
Maths_And_Stats => Algorithms => GCD => GCD.cpp

**Contributors**
- [X]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [x] Swift -
- [x] C# -

**Comment by AnshMishra2001** [comment]
Pls assign

**Comment by AnshMishra2001** [comment]
this to me.

**Comment by AnshMishra2001** [comment]
I can code it in Java, Cpp and python.

**Comment by CormacKrum** [comment]
Please Assign this to me in Java ,CPP Or Python

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by jaskirankaur51** [comment]
Please assign this to me for C language

**Comment by ashish-garg18** [comment]
Assign it to me for C, C++, python, Java

**Comment by ahampriyanshu** [comment]
@AnshMishra2001 go ahead with Java
@CormacKrum go ahead with CPP
@Nirali0029 go ahead with Python
@jaskirankaur51 go ahead with C
@ashish-garg18 please choose a different language/issue

**Comment by harshita130602** [comment]
Hey! I would love to contribute to this repo. Can I add the code for it in C#

**Comment by harshita130602** [comment]
Please assign this issue to me.

**Comment by ashish-garg18** [comment]
Can go for javascript

**Comment by harshita130602** [comment]
So, can I start working for javascript with this?

**Comment by ashish-garg18** [comment]
No, i was asking @ahampriyanshu if i should go with javascript. Sorry for misunderstanding @harshita130602

**Comment by dipankargoswami** [comment]
Hi @taresh18 , I would like to do it in Swift

**Comment by ahampriyanshu** [comment]
@harshita130602 go ahead with C#
@ashish-garg18 go ahead with JS
@dipankargoswami go ahead with Swift

**Comment by Vimlesh-Kumar** [comment]
Please assign me in php

**Comment by ashish-garg18** [comment]
#339 Added GCD file in Javascript

**Comment by ashish-garg18** [comment]
Added GCD in Javascript #339

**Comment by Chaitalykundu** [comment]
I want to do this in C

**Comment by ahampriyanshu** [comment]
Hi @harshita130602 go ahead with JS
Hi @Chaitalykundu go ahead with C

**Comment by rishabhsudan** [comment]
Hi, I can contribute in Scala, Please assign

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
