### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Rituraj-commits** [ahampriyanshu/algo_ds_101#257]
**Submission Title**
Dijkstra's Algorithm

**Submission Type**
Algorithm/Graph_Algorithms/Dijkstra

**Submission Description**
Describe the Dijsktra's Algorithm to find the shortest path between two nodes in a graph

**Folder Related To**
Algorithm => Graph_Algorithm => Dijkstra => Dijkstra.cpp

**Contributors**
- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rituraj-commits** [comment]
I want to work on this issue @ahampriyanshu

**Comment by hadron43** [comment]
I'll do it for java.

**Comment by ShubhamJamuar** [comment]
I wish to work on this using C++

**Comment by ahampriyanshu** [comment]
@Rituraj-commits please mention your preferred language

**Comment by Srijan7777** [comment]
I want to work on this using Javascript

**Comment by AnshMishra2001** [comment]
I can do this in Python

**Comment by Vaibhav7860** [comment]
@ahampriyanshu  Sir I want to implement Dijkstra's Algorithm in Python. Please assign this issue to me.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
