### ISSUE TITLE
PrimeFactorisation

### ISSUE THREAD

**Issue by taresh18** [ahampriyanshu/algo_ds_101#263]
**Submission Title**
Prime Factorisation

**Submission Type**
Maths_And_Stats

**Submission Description**
Find all the prime factors of a given number efficiently.

**Folder Related To**
Maths_And_Stats => Algorithms => Prime_Factorization => PrimeFactorisation.cpp 

**Contributors**

- [X]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Vimlesh-Kumar** [comment]
Please assign this task to me in c @ahampriyanshu

**Comment by Mr-Vaibhav-Shukla** [comment]
@ahampriyanshu Please assign me this task in Python

**Comment by jatin-773762** [comment]
@ahampriyanshu Could you please assign this task to me in java

**Comment by AnshMishra2001** [comment]
Pls assign this to me in cpp

**Comment by Srijan7777** [comment]
Can u assign this to me in JavaSript

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @AnshMishra2001, Please opt a different language :smile:

**Comment by sakshamsablok** [comment]
Hello @ahampriyanshu ,
Please assign this issue to me in C++.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @sakshamsablok , Please opt a different language/issue

**Comment by harshita130602** [comment]
Hey! Can I do this in C# ? Please assign it to me

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
