### ISSUE TITLE
Factorial

### ISSUE THREAD

**Issue by rohanBrid18** [ahampriyanshu/algo_ds_101#279]
**Submission Title**
Factorial

**Submission Type**
Maths_And_Stats

**Submission Description**
A recursive function to calculate the factorial of a number

**Folder Related To**
Maths_And_Stats => Algebra => Factorial => factorial.py

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by adrikagupta** [comment]
Hey, I am interested in working on this. Can you assign it to me?

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @adrikagupta, Please select a language.

**Comment by adrikagupta** [comment]
I can do it in C, C++, Java, and Javascript. Do you want me to pick only one or is it fine if I do for all four of them? @Mr-Vaibhav-Shukla

**Comment by harshita130602** [comment]
Hey I have done it in C++. Can you review my PR  #283

**Comment by harshita130602** [comment]
@Mr-Vaibhav-Shukla I have done it in C++

**Comment by Mr-Vaibhav-Shukla** [comment]
Great @adrikagupta, go ahead with C, Java, Javascript

**Comment by ahampriyanshu** [comment]
Hi @harikesh409 , Please fill up the PR(#283) template correctly

**Comment by harshita130602** [comment]
> Hi @harikesh409 , Please fill up the PR(#283) template correctly

I edited it now. I think it should be fine now. Please check :)

**Comment by adrikagupta** [comment]
> Great @adrikagupta, go ahead with C, Java, Javascript

Yep. I am done with C. Now, I need to do Java and Javascript.

**Comment by ahampriyanshu** [comment]
Hi @ShubhayanDas08 , please opt a different language.

**Comment by ahampriyanshu** [comment]
> > Hi @harikesh409 , Please fill up the PR(#283) template correctly
> 
> I edited it now. I think it should be fine now. Please check :)

#283 has been merged successfully

**Comment by adrikagupta** [comment]
Hey. After doing it in C, I went ahead and did it in Java and Javascript. Please review. Thank you for the opportunity:)

**Comment by adrikagupta** [comment]
Hey. I have done this program in Ruby too. You can tick it in the list 👍

**Comment by adrikagupta** [comment]
Hey! I have done this program in C# too. You can tick it in the list 👍

**Comment by swas1820** [comment]
Hi @ahampriyanshu , I can code this in PHP.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
