### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by realvaibhav** [ahampriyanshu/algo_ds_101#3]
**Submission Title**
Binary Search 

**Submission Type**
 Algorithms

**Submission Description**
 Search a sorted array by repeatedly dividing the search interval in half

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] Golang -

**Comment by realvaibhav** [comment]
I want to contribute to this task through C++ @ahampriyanshu please assign this task to me .

**Comment by Dheeraj-01** [comment]
Can I do that problem?? In  Java and python

**Comment by killerpanda101** [comment]
i would like to work on the javaScript version

**Comment by Singh-Aishwarya** [comment]
Assign me in Java if you could @ahampriyanshu

**Comment by ahampriyanshu** [comment]
@Singh-Aishwarya go ahead with java
@Dheeraj-01 go ahead with python

**Comment by GGolfz** [comment]
Assign me in js @ahampriyanshu Thanks

**Comment by GGolfz** [comment]
> Assign me in js @ahampriyanshu Thanks

I means javascript

**Comment by ahampriyanshu** [comment]
@all-contributors please add @realvaibhav  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @killerpanda101   for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Dheeraj-01 for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @harikesh409  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @GGolfz  for code

**Comment by dipankargoswami** [comment]
Hi @ahampriyanshu , could you please help removing or renaming one of the Javascript files for binary search. 
There are two files with exactly same name (only difference is Case) and git not able to handle properly in Mac(and I think might be in Windows as well). 
Thank you.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
