### ISSUE TITLE
LCM

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#301]
**Submission Title**
LCM

**Submission Type**
Maths_And_Stats

**Submission Description**
In arithmetic and number theory, the least common multiple, lowest common multiple, or smallest common multiple of two integers a and b, usually denoted by lcm(a, b), is the smallest positive integer that is divisible by both a and b.

**Folder Related To**
Maths_And_Stats => Algebra => LCM => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by priya-pri** [comment]
Can I add in java?

**Comment by priya-pri** [comment]
> Can I add in 

> Can I add in java?

Please review my pull request for LCM.java

**Comment by Mikadore** [comment]
I would like to implement this in C++

**Comment by sidanand67** [comment]
I can implement it in python

**Comment by yogeswarl** [comment]
I can do this in JS. could you assign this

**Comment by potato874** [comment]
I'd like to do this for Python please :)

**Comment by ahampriyanshu** [comment]
Hi @sidanand67, please opt a different language/issue.

**Comment by sidanand67** [comment]
> Hi @sidanand67, please opt a different language/issue.

Sure, No problem. I'll take a different issue.

**Comment by cuber485** [comment]
@ahampriyanshu  I can implement it in C.

**Comment by BabesGotByte** [comment]
Hey!! I would like to do this in C++

**Comment by BabesGotByte** [comment]
> Hey!! I would like to do this in C++

Please review my pull request #500

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
