### ISSUE TITLE
Arthimetic Progression

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#305]
**Submission Title**
Arthimetic Progression

**Submission Type**
Maths_And_Stats

**Submission Description**
An arithmetic progression is a sequence of numbers such that the difference of any two successive members is a constant.

**Folder Related To**
Maths_And_Stats => Algebra => Arthimetic_Progression =>  Arthimetic Progression.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by DanielVip3** [comment]
Can I contribute to JavaScript and TypeScript Arithmetic Progressions?

**Comment by Grasstown** [comment]
Can I contribute to the Java Arithmetic Progressions task?

**Comment by ShubhamJamuar** [comment]
I can do it in C++

**Comment by Nirali0029** [comment]
I can do it in python

**Comment by chinmaym07** [comment]
Can I do this in C.?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
