### ISSUE TITLE
Sum_of_AP

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#306]
**Submission Title**
Sum_of_AP

**Submission Type**
Maths_And_Stats

**Submission Description**
An arithmetic progression is a sequence of numbers such that the difference of any two successive members is a constant.

**Folder Related To**
Maths_And_Stats => Algebra => Sum_of_AP =>  Sum_of_AP.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by SayaniG371** [comment]
I would like to work on this in c++ and Python. Please assign me this !

**Comment by Procoder16** [comment]
@ahampriyanshu sir/madam, I would like to work on this ticket with JAVA and C++. 

Can you please assign me this??

**Comment by ahampriyanshu** [comment]
Hi @SayaniG371 go ahead with C++ and python
Hi @Procoder16 go ahead with Java

**Comment by Prash2002** [comment]
hey @ahampriyanshu , I would like to do it using C, can you assign it to me?

**Comment by Procoder16** [comment]
thank you @ahampriyanshu

**Comment by pulkitsapra** [comment]
hey @ahampriyanshu I would like to do in Scala ?

**Comment by pulkitsapra** [comment]
I would like to do in Javascript & Golang ?

**Comment by akaash11** [comment]
Hey can I do this one  in Javascript?

**Comment by Vimlesh-Kumar** [comment]
> I would like to do in Javascript & Golang ?

Go with Golang only.

**Comment by pulkitsapra** [comment]
@ahampriyanshu There is no structured directory for this. Should i create one along with my code ?

**Comment by pulkitsapra** [comment]
> > I would like to do in Javascript & Golang ?
> 
> Go with Golang only.

Can you add me ass assignee

**Comment by pulkitsapra** [comment]
Can you please merge my PR. @Vimlesh-Kumar @ahampriyanshu 

Thanks!

**Comment by Hashrin** [comment]
Hi,
I would like to implement this in C#. Can you please assign it to me?

**Comment by SayaniG371** [comment]
Can you please review my PR #430  @ahampriyanshu . Thank you

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by akaash11** [comment]
Hi @ahampriyanshu , I have successfully created pull request #738 , following all the guidelines.
