### ISSUE TITLE
Geometric Progression

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#307]
**Submission Title**
Geometric Progression

**Submission Type**
Maths_And_Stats

**Submission Description**
A geometric progression, also known as a geometric sequence, is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed, non-zero number called the common ratio.

**Folder Related To**
Maths_And_Stats => Algebra => Geometric_Progression  =>  Geometric Progression.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by firehawk23** [comment]
@ahampriyanshu I want to implement this in python. so assign it to me.

**Comment by jyotiGambhir** [comment]
@ahampriyanshu Can yu assign it to me? I would like to code in CPP

**Comment by DevanshiJain** [comment]
Hey, I would like to contribute the code in java. Could you assign it to me?

**Comment by AlxGration** [comment]
hi, can u assign me for C# ?

**Comment by akaash11** [comment]
@ahampriyanshu I would like to work on Javascript

**Comment by chinmaym07** [comment]
Hi @ahampriyanshu . I would like to work on Java. can you assign it to me.?

**Comment by ahampriyanshu** [comment]
Hi @ahampriyanshu , please opt a different language/issue. :smiley:

**Comment by chinmaym07** [comment]
@ahampriyanshu can I do it in C.?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by chinmaym07** [comment]
Hey @ahampriyanshu . Can you assign it to me . I would like to work on C .

**Comment by chinmaym07** [comment]
Hey @ahampriyanshu  .you have assigned me this task to do in C . but you have closed this issue earlier. Please reopen it so that i can made a PR for the C code.
