### ISSUE TITLE
Sum_of_GP

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#308]
**Submission Title**
Sum_of_GP

**Submission Type**
Maths_And_Stats

**Submission Description**
A geometric progression, also known as a geometric sequence, is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed, non-zero number called the common ratio.

**Folder Related To**
Maths_And_Stats => Algebra => Sum_of_GP  =>  Sum_of_GP.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by beccadaniel** [comment]
I'll like to take this issue up. Can I add in Java?

**Comment by ShubhamJamuar** [comment]
I can do this in C++

**Comment by jyotiGambhir** [comment]
Can I take this issue and add in Python?

**Comment by abhinav889** [comment]
i want to work on the c code

**Comment by chinmaym07** [comment]
@ahampriyanshu can I work on Javascript for this.?

**Comment by Avninder99** [comment]
I would like to do this problem in JavaScript. Can it be issued to me ?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
