### ISSUE TITLE
Sum_of_HP

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#309]
**Submission Title**
Sum_of_HP

**Submission Type**
Maths_And_Stats

**Submission Description**
A harmonic progression is a sequence of real numbers formed by taking the reciprocals of an arithmetic progression.

**Folder Related To**
Maths_And_Stats => Algebra => Sum_of_HP => Sum_of_HP.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by prajwlr** [comment]
Hey @ahampriyanshu ! I'd love to solve this issue. Please assign it to me

**Comment by Nirali0029** [comment]
I would like to solve this in python

**Comment by ahampriyanshu** [comment]
Hi @prajwlr, Please opt a differerent language/issue.

**Comment by dipankargoswami** [comment]
Hi @ahampriyanshu , can I do it in swift ?

**Comment by abhinav889** [comment]
i would like to solve this in c# please assign it to me

**Comment by jaskarans2000** [comment]
I would love to solve this in java

**Comment by chinmaym07** [comment]
I would like to solve in c. Please assign it to me

**Comment by kushkamisha** [comment]
I can do the js implementation

**Comment by rishabhsudan** [comment]
Hi, I can contribute in Scala, Please assign

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
