### ISSUE TITLE
Harmonic_Progression

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#310]
**Submission Title**
Harmonic_Progression

**Submission Type**
Maths_And_Stats

**Submission Description**
A harmonic progression is a sequence of real numbers formed by taking the reciprocals of an arithmetic progression.

**Folder Related To**
Maths_And_Stats => Algebra => Harmonic_Expression => Harmonic_Expression.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Assign this to me for python

**Comment by firehawk23** [comment]
Assign this to me for cpp

**Comment by Nirali0029** [comment]
I have created a pull request for python

**Comment by Nirali0029** [comment]
plz add the tag hacktober accepted as per new rules for my merged code ;)

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
