### ISSUE TITLE
Factorial_of_Large_Number

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#311]
**Submission Title**
Factorial_of_Large_Number

**Submission Type**
Maths_And_Stats

**Submission Description**
Factorial of a large number

**Folder Related To**
Maths_And_Stats => Algebra => Factorial_of_Large_Number => Factorial_of_Large_Number.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Mikadore** [comment]
Hello! From reading the `README` and `CONTRIBUTING` Files, I have gathered that the task at hand is to implement a program that reads from `stdin`, and in this case calculates the factorial of an arbitrarily sized (very large) number, is that correct? If that is so, I would like to implement it in C and C++.

**Comment by parjanyaacoder** [comment]
I would like to implement it in Java.

**Comment by SardulDhyani** [comment]
Hello, @ahampriyanshu I would like to work on JS.
Please assign Js issue to me.

**Comment by atorr5555** [comment]
I would like to do it in Python

**Comment by ankurjain00** [comment]
Hello @ahampriyanshu please assign Python issue to me

**Comment by ahampriyanshu** [comment]
Hi @ankurjain00, Please opt a different language/issue 😄

**Comment by SardulDhyani** [comment]
Thanks @ahampriyanshu. 🙂

**Comment by akaash11** [comment]
Hey, I would like  to do in JavaScript

**Comment by SardulDhyani** [comment]
Hey, @akaash11 the JavaScript is already assigned to me.

**Comment by akaash11** [comment]
> Hey, @akaash11 the JavaScript is already assigned to me.
Ok. Will go for another one

**Comment by Vivek-Raman** [comment]
Hello, I would like to solve this in C#, if it's available!

**Comment by ankurjain00** [comment]
Hi @ahampriyanshu please assign TypeScript

**Comment by geoffgeorgein** [comment]
I shall do this in python. Please assign me this.

**Comment by reyadkhan** [comment]
Hi, I would like to solve it in PHP

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
