### ISSUE TITLE
Taylor Expansion

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#313]
**Submission Title**
Taylor Expansion

**Submission Type**
Maths_And_Stats

**Submission Description**
The so-called invertible matrix theorem is major result in linear algebra which associates the existence of a matrix inverse with a number of other equivalent properties.

**Folder Related To**
Maths_And_Stats => Algebra => Taylor _Expansion=> filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by idlanqmohaimin** [comment]
First timer here. Requesting to contribute in C. Thanks!

**Comment by prajwlr** [comment]
Hey @ahampriyanshu ! I'd love to contribute to this issue in c++. Please assign it to me

**Comment by subham5230** [comment]
Hey @ahampriyanshu , I am willing to work on this issue in python please assign it to me

**Comment by idlanqmohaimin** [comment]
May I know what function (f(x)) is being approximated with this expansion?

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` ,`` JS`` , ``Java`` versions of this algo have already been implemented .
