### ISSUE TITLE
Matrix_Multipication

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#314]
**Submission Title**
Matrix_Multipication

**Submission Type**
Matrix_Multipication

**Submission Description**
The so-called invertible matrix theorem is major result in linear algebra which associates the existence of a matrix inverse with a number of other equivalent properties.

**Folder Related To**
Maths_and_Stats => Algebra => Matrix_Multiplication => MatrixMultipication.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift
- [ ] C# -

**Comment by krabhisharma** [comment]
Assign me I will do it matrix multiplication in java

**Comment by ankurjain00** [comment]
hello @ahampriyanshu please assign python issue to me

**Comment by SravanthiKaki** [comment]
Can you please assign C issue to me?

**Comment by subham5230** [comment]
Can you please assign the javascript issue to me?

**Comment by AjinkyaSahu** [comment]
Can you please accept my pull request. I have completed matrix multiplication program with all 4 languages.

**Comment by null-sys** [comment]
Please assign javascript implementation of Matrix multiplication to me.

**Comment by GrishonNganga** [comment]
Could you please assign me the Typescript implementation as well?

**Comment by dheerajvenugopal96** [comment]
Please assign java issue to me

**Comment by ahampriyanshu** [comment]
Hi @dheerajvenugopal96 please opt a different/language issue :grin:

**Comment by Astrogeek77** [comment]
@ahampriyanshu Can you assign this task to me in JS?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
