### ISSUE TITLE
Target Sum

### ISSUE THREAD

**Issue by Prodip-Kumar-Paul** [ahampriyanshu/algo_ds_101#356]
**Submission Type**
Algorithm

**Description**
Find out the number of subset sum equal to the given sum

**Folder Related To**
Algorithm => Dynamic_Programming =>Target_Sum => Target_Sum.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Prodip-Kumar-Paul** [comment]
may I work on this issue ??

**Comment by aditya1abhinav** [comment]
Java

**Comment by aditya1abhinav** [comment]
> may I work on this issue ??

How do you add labels? like C#, C++, etc.

**Comment by aditya1abhinav** [comment]
Can anyone tell me how to add labels?

**Comment by ahampriyanshu** [comment]
> Can anyone tell me how to add labels?

Sorry @aditya1abhinav only collaborators can add or remove labels 😄

**Comment by utkarshgupta2504** [comment]
Hi, I would like to work on this in Python

**Comment by AnshMishra2001** [comment]
I can code in java

**Comment by jaskarans2000** [comment]
Can I work on this in java?

**Comment by chinmaym07** [comment]
I can work on this in C . Please assign it to me

**Comment by ahampriyanshu** [comment]
> Can I work on this in java?

Hi @jaskarans2000 please opt a different language/issue

**Comment by julianasinai** [comment]
Please, assign Javascript to me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
