### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#365]
**Submission Title**
Bucket Sort

**Submission Type**
Algorithm

**Submission Description**
Bucket Sort is a sorting algorithm that works by distributing the elements of an array into a number of buckets.

**Folder Related To**
Algorithms => Sorting_Algorithms => Bucket_Sort => BucketSort.py

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @ahampriyanshu , Please assign me this issue in C++.

**Comment by Sanika1999** [comment]
Hi @ahampriyanshu I can work on java?

**Comment by AnshMishra2001** [comment]
I can code this in ruby

**Comment by swas1820** [comment]
Hi @ahampriyanshu , I can code this in PHP. Please assign this issue to me.

**Comment by SUJATA19-could** [comment]
hey! can I do this in C#

**Comment by Harshalszz** [comment]
Hey! can I work on this in C language

**Comment by SriCoD** [comment]
heya, i can code this on kotlin

**Comment by mariothedog** [comment]
I would like to work on this algorithm in JavaScript.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
