### ISSUE TITLE
Clock Angle

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#384]
**Submission Title**
Clock Angle

**Submission Type**
Maths_And_Stats

**Submission Description**
Clock angle problems relate two different measurements: angles and time. The angle is typically measured in degrees from the mark of number 12 clockwise. The time is usually based on a 12-hour clock. ... The hour hand of a normal 12-hour analogue clock turns 360° in 12 hours (720 minutes) or 0.5° per minute.

**Folder Related To**
Maths_And_Stats => Geometry => Clock_Angle => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by junyongxlee** [comment]
Can I be assigned the Java Version?

**Comment by xanaDev** [comment]
I'd like to work on the Golang implementation, can you assign me ?

**Comment by Avninder99** [comment]
I would like to work on this issue in JavaScript. Please assign this to me.

**Comment by apar23** [comment]
Can I be assigned the C# implementation?

**Comment by TanishqPorwar** [comment]
I'd like to work on the python implementation, can you assign it to me?

**Comment by mariothedog** [comment]
I would like to work on the JavaScript version.

**Comment by Avninder99** [comment]
@ahampriyanshu Javascript code pushed by me has been merged for this issue along with C. So please checkmark the javascript.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
