### ISSUE TITLE
Distance Formula

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#389]
**Submission Title**
Distance Formula

**Submission Type**
Maths_And_Stats

**Submission Description**
The Distance Formula is a variant of the Pythagorean Theorem 
Given the two points (x1, y1) and (x2, y2), the distance d between these points is given by the formula:
d=√((x_2-x_1)²+(y_2-y_1)²) 

**Folder Related To**
Maths_And_Stats/Geometry => Distance_Formula => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Diadochokinetic** [comment]
I would like to be assigned to the Python version :)

**Comment by lucid-dreem** [comment]
Hey, could I be assigned the C++ version?

**Comment by Vivek-Raman** [comment]
I'd like to be assigned C# version for this issue!

**Comment by parth93QA** [comment]
please assign me the golang version

**Comment by lucid-dreem** [comment]
Hey, this is my first contribution to this repository, could anyone help me out and let me know why it didn't pass the checks?

**Comment by amansaxena1** [comment]
I would like to be assigned to the java version

**Comment by Diadochokinetic** [comment]
> Hey, this is my first contribution to this repository, could anyone help me out and let me know why it didn't pass the checks?

I'm not sure, but maybe you have to name the file exactly like the directory name. So upper case letters.

**Comment by pavnesh2019** [comment]
i would like to do this in c

**Comment by junyongxlee** [comment]
Can I be assigned for Java?

**Comment by adrputra** [comment]
I would like to be assigned for php version

**Comment by kushkamisha** [comment]
I could do js implementation

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
