### ISSUE TITLE
Circular Linked List

### ISSUE THREAD

**Issue by GGolfz** [ahampriyanshu/algo_ds_101#39]
**Submission Title**
Circular Linked List

**Submission Type**
Data Structure

**Submission Description**
I implement circular linked list in java language using my own node class and provide isEmpty(), addToTail(), and printAll() method for circular linked list

**Contributors**
- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] Golang -

**Comment by Pandiurex** [comment]
i can do it in c++, actually im doing it right now, do u want it?

**Comment by ahampriyanshu** [comment]
@Pandiurex go ahead with C++

**Comment by shubham2704** [comment]
@Pandiurex i would like to implement it with python and javascript

**Comment by manvendra264** [comment]
I would like to implement BST in C++. Can I?

**Comment by ahampriyanshu** [comment]
@all-contributors please add @Pandiurex  for code

**Comment by ahampriyanshu** [comment]
@all-contributors please add @shubham2704   for code

**Comment by Goyalscode** [comment]
Can i implement circular linked list in c ?

**Comment by ahampriyanshu** [comment]
> Can i implement circular linked list in c ?

Hi @Goyalscode, Please refer #

**Comment by ahampriyanshu** [comment]
Thanks @Pandiurex , @GGolfz  , @shubham2704 and @joyeta148 :v:
