### ISSUE TITLE
 Leibniz Formula

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#391]
**Submission Title**
 Leibniz Formula

**Submission Type**
Maths_And_Stats

**Submission Description**
The Leibniz formula expresses the derivative on nth order of the product of two functions. Suppose that the functions u(x) and v(x) have the derivatives up to nth order. The first derivative is described by the well known formula: (uv)′=u′v+uv′.

**Folder Related To**
Maths_And_Stats => Calculus =>  Leibniz_Formula =>  Leibniz_Formula.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by saurabh80521** [comment]
@ahampriyanshu ..can you assign this to me..i wanna work on this in cpp..

**Comment by chinmaym07** [comment]
@ahampriyanshu can i do it in C, Java & Pyhton. ?

**Comment by Astrogeek77** [comment]
@ahampriyanshu can you assign this task to 
me in C?

**Comment by TanishqPorwar** [comment]
@ahampriyanshu  @Mr-Vaibhav-Shukla 
I want to work on this issue in python, can you assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
