### ISSUE TITLE
Riemann Sum

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#392]
**Submission Title**
Riemann Sum

**Submission Type**
Maths_And_Stats

**Submission Description**
Riemann Sum is a certain kind of approximation of an integral by a finite sum. The sum is calculated by partitioning the region into shapes (rectangles, trapezoids, parabolas, or cubics) that together form a region that is similar to the region being measured, then calculating the area for each of these shapes, and finally adding all of these small areas together.

**Folder Related To**
Maths_And_Stats => Calculus =>  Riemann Sum =>  Riemann Sum.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Vivek-Raman** [comment]
I'd like to try this in C#. Also, shouldn't this be under Calculus?

**Comment by arnav-roy** [comment]
I want to work on this issue in C++

**Comment by TanishqPorwar** [comment]
I want to work on this issue in python

**Comment by Rajwrita** [comment]
I would want to work on this in python

**Comment by Astrogeek77** [comment]
i would like to do this in C , C++, python ? @ahampriyanshu @Mr-Vaibhav-Shukla

**Comment by ahampriyanshu** [comment]
Hi @Astrogeek77 ,
Please opt a different language/issue.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
