### ISSUE TITLE
Euler_Approximation

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#393]
**Submission Title**
Euler_Approximation

**Submission Type**
Maths_And_Stats

**Submission Description**
Euler_Approximation method is a first-order numerical procedure for solving ordinary differential equations with a given initial value. 

**Folder Related To**
Maths_And_Stats => Calculus =>  Euler_Approximation =>  Euler_Approximation.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by itIsBrando** [comment]
I can do it in Java

**Comment by itIsBrando** [comment]
I can do it in Java

**Comment by SOURAB-BAPPA** [comment]
i would like to work in c#, go, c++, python, java, c, R

**Comment by Mr-Vaibhav-Shukla** [comment]
Great @SOURAB-BAPPA , go ahead in all except java

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
