### ISSUE TITLE
Runge–Kutta_Method

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#395]
**Submission Title**
Runge–Kutta_Method

**Submission Type**
Maths_And_Stats

**Submission Description**
Runge–Kutta methods are a family of implicit and explicit iterative methods, which include the well-known routine called the Euler Method

**Folder Related To**
Maths_And_Stats => Calculus =>  Runge–Kutta_Method =>  Runge–Kutta_Method.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by SOURAB-BAPPA** [comment]
i want to solve 
in which programming language do you want?

**Comment by SOURAB-BAPPA** [comment]
i would like to work in c#, go, c++, python, java, c, R

**Comment by NumberPiOso** [comment]
Assign this to me in Python.

**Comment by nayanika0208** [comment]
can i do it in c++?

**Comment by nayanika0208** [comment]
Please check my pull request no #956

**Comment by SOURAB-BAPPA** [comment]
can i do it in  C

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by SOURAB-BAPPA** [comment]
Runge–Kutta_Method in c added

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
