### ISSUE TITLE
Manhattan distances

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#396]
**Submission Title**
Manhattan distances

**Submission Type**
Maths_And_Stats

**Submission Description**
The distance between two points measured along axes at right angles. In a plane with p1 at (x1, y1) and p2 at (x2, y2), it is |x1 - x2| + |y1 - y2|.

**Folder Related To**
Maths_And_Stats => Geometry => Manhattan_Distance => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by deepdhar** [comment]
@Vimlesh-Kumar I would like to add the code in CPP

**Comment by subham5230** [comment]
I would like to contribute to this issue in python please assign me

**Comment by mariothedog** [comment]
I would like to complete this issue for JavaScript.

**Comment by TheOldTravellerNetwork** [comment]
I would like to do this in Java!

**Comment by devanshOrz** [comment]
@ahampriyanshu i would like to do this in C

**Comment by Astrogeek77** [comment]
@ahampriyanshu Can you assign this task to me in C?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
