### ISSUE TITLE
Ackermann_Peter

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#398]
**Submission Title**
Ackermann_Peter

**Submission Type**
Maths_And_Stats

**Submission Description**
 It is one of the simplest and earliest-discovered examples of a total computable function that is not primitive recursive. 

**Folder Related To**
Maths_And_Stats => Discrete =>  Ackermann_Peter =>  Ackermann_Peter.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by julianasinai** [comment]
Hi, I would like to solve this in python

**Comment by Sayantan-Bhowmick** [comment]
Hi, I would like to solve this in C++

**Comment by OverPoweredDev** [comment]
Mind if I resolve this in C and JavaScript?

**Comment by Astrogeek77** [comment]
Can you assign this task to me in C, CPP, JS? @ahampriyanshu @Mr-Vaibhav-Shukla

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
