### ISSUE TITLE
Exponential_Smoothing

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#399]
**Submission Title**
Exponential_Smoothing

**Submission Type**
Maths_And_Stats

**Submission Description**
Exponential smoothing is a rule of thumb technique for smoothing time series data using the exponential window function.

**Folder Related To**
Maths_And_Stats => Statistics =>  Exponential_Smoothing =>  Exponential_Smoothing.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by manvendra3** [comment]
hi @ahampriyanshu please assign this task to me in ruby

**Comment by manvendra3** [comment]
@ahampriyanshu assign this task in java

**Comment by manvendra3** [comment]
@ahampriyanshu assign this task to me c++

**Comment by manvendra3** [comment]
@ahampriyanshu assign this task in php

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
