### ISSUE TITLE
Confidence_Interval

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#401]
**Submission Title**
Confidence_Interval

**Submission Type**
Maths_And_Stats

**Submission Description**
In statistics, a confidence interval is a type of estimate computed from the statistics of the observed data. This proposes a range of plausible values for an unknown parameter. 

**Folder Related To**
Maths_And_Stats => Statistics =>  Confidence_Interval => Confidence_Interval.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by meteoritenhagel** [comment]
I'd like to add the C++ code for that one.

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by ukitta555** [comment]
I'd like to work on JS version of this.

**Comment by ahampriyanshu** [comment]
Hi @ukitta555  :wave: 
I'm closing this issue but you can still go ahead and create a PR.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
