### ISSUE TITLE
Logistic_Function

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#402]
**Submission Title**
Logistic_Function

**Submission Type**
Maths_And_Stats

**Submission Description**
A logistic function or logistic curve is a common S-shaped curve (sigmoid curve) with equation. where = the value of the sigmoid's midpoint, = the curve's maximum value, = the logistic growth rate or steepness of the curve.

**Folder Related To**
Maths_And_Stats => Statistics => Logistic_Function => Logistic_Function.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by shaunak56** [comment]
Can you please assign me C++ and Python? Thank you

**Comment by shaunak56** [comment]
What is the expected output? can you describe a little bit, as the variables are no visible in the issue

**Comment by Astrogeek77** [comment]
@Mr-Vaibhav-Shukla  Can you assign this task to me in c?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
