### ISSUE TITLE
Polar_Cartesian_Conversion

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#404]
**Submission Title**
Polar_Cartesian_Conversion

**Submission Type**
Maths_And_Stats

**Submission Description**
Converting Polar Coordinates to Cartesian

**Folder Related To**
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Polar_Cartesian_Conversion.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by julianasinai** [comment]
I will do it in python

**Comment by pulkitsapra** [comment]
Please assign me for Golang.

**Comment by XoMute** [comment]
Please check my PR, thanks

**Comment by Calm-23** [comment]
Hello, I would like to add the code for this problem in CPP.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
