### ISSUE TITLE
N Dimensional Distance

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#405]
**Submission Title**
N_Dimensional_Distance

**Submission Type**
Maths_And_Stats

**Submission Description**
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm. Older literature refers to the metric as the Pythagorean metric. A generalized term for the Euclidean norm is the L2 norm or L2 distance.

**Folder Related To**
Maths_And_Stats => Geometry => N_Dimensional_Distance => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by cdefga** [comment]
i'll do python version

**Comment by alkatrivedi** [comment]
I would like to implement in C++. May I?

**Comment by verma-pulkit** [comment]
I can do this for cpp. Can I be assigned.

**Comment by meteoritenhagel** [comment]
I'd like to do the C implementation.

**Comment by subham5230** [comment]
I can do it in java @Vimlesh-Kumar please assign me this issue

**Comment by william-gooch** [comment]
I'd like to have a go at this in C# if possible.

**Comment by dandynaufaldi** [comment]
@ahampriyanshu  could I get assigned for ruby version?

**Comment by dheerajvenugopal96** [comment]
Please assign the java part to me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
