### ISSUE TITLE
Radians_Degrees_Conversion

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#406]
**Submission Title**
Radians_Degrees_Conversion

**Submission Type**
Maths_And_Stats

**Submission Description**
Radians  <=> Degrees

**Folder Related To**
Maths_And_Stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Parth-Gupta10** [comment]
i will do it in c++

**Comment by utkarshgupta2504** [comment]
I would like to do this in Python

**Comment by tintindas** [comment]
I would like to do this in js

**Comment by M4rkoHR** [comment]
I would like to do it in C.

**Comment by EnzoRobaina** [comment]
I'd like to contribute with the Java version.

**Comment by dipankargoswami** [comment]
Hi @ahampriyanshu , can I do it in scala ?

**Comment by ahampriyanshu** [comment]
Perfect code :+1: 
Thanks @dipankargoswami 
Happy contributing :v:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
