### ISSUE TITLE
Scalar_Product

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#407]
**Submission Title**
Scalar_Product

**Submission Type**
Maths_And_Stats

**Submission Description**
Scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors), and returns a single number.

**Folder Related To**
Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Diadochokinetic** [comment]
I'd like to do the python version :)

**Comment by deepdhar** [comment]
@ahampriyanshu I would like to do this in CPP

**Comment by atorr5555** [comment]
I would like to do this in Java

**Comment by devanshOrz** [comment]
@ahampriyanshu can you assign me this task in C

**Comment by EnzoRobaina** [comment]
I'd like to contribute with the javascript version.

**Comment by beccadaniel** [comment]
Can I do this in Swift?

**Comment by Astrogeek77** [comment]
@ahampriyanshu Can you assign me this task in JS?

**Comment by dandynaufaldi** [comment]
@ahampriyanshu could you assign me for ruby version?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
