### ISSUE TITLE
Vector_Product

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#408]
**Submission Title**
Vector_Product

**Submission Type**
Maths_And_Stats

**Submission Description**
Cross product or Vector product is a binary operation on two vectors in three-dimensional space

**Folder Related To**
Maths_And_Stats => Geometry => Vector_Product => Vector_Product.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by verma-pulkit** [comment]
Assign CPP program to me.

**Comment by Diadochokinetic** [comment]
I'd like to do the python version :)

**Comment by EnzoRobaina** [comment]
I'd like to contribute with the javascript version.

**Comment by devanshOrz** [comment]
@ahampriyanshu  please assign me this task in C

**Comment by DanielVip3** [comment]
I'd like to do the JavaScript version.

**Comment by Astrogeek77** [comment]
@ahampriyanshu Can you assign this task to me in JAVA

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
