### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by GGolfz** [ahampriyanshu/algo_ds_101#41]
**Submission Title**
Binary Search Tree

**Submission Type**
Data Structure

**Submission Description**
Implementing Binary Search Tree in any given language

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - @GGolfz 
- [ ] JavaScript -
- [ ] Golang -

**Comment by Balaguru4580** [comment]
I'd like to implement this in Python. Can I get assigned for that?

**Comment by manvendra264** [comment]
I would like to implement BST in C++. Can I?

**Comment by Balaguru4580** [comment]
Alright. PR submitted.

**Comment by sbhavya18** [comment]
I would like to implement this in c++. Kindly assign me this.

**Comment by ahampriyanshu** [comment]
thanks @GGolfz :v:
