### ISSUE TITLE
Polar_Cartesian_Conversion

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#410]
**Submission Title**
Polar_Cartesian_Conversion

**Submission Type**
Maths_And_Stats

**Submission Description**
The polar coordinates r and φ can be converted to the Cartesian coordinates x and y by using the trigonometric functions sine and cosine:

**Folder Related To**
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
Duplicate ⚠️
