### ISSUE TITLE
Pythagorean_theorem

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#413]
**Submission Title**
Pythagorean_theorem

**Submission Type**
Maths_And_Stats

**Submission Description**
For a right triangle with legs a and b and hypotenuse c,
a^2 + b^2 = c^2

**Folder Related To**
Maths_And_Stats => Geometry => Pythagorean_theorem => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by utkarshgupta2504** [comment]
I would like to work on this in C++

**Comment by VarunV991** [comment]
I would like to work on this in Java

**Comment by subham5230** [comment]
I would be interested to work on this in python, please assign this to me

**Comment by Hashrin** [comment]
Please assign the C# version to me.

**Comment by junyongxlee** [comment]
Can you assign javascript to me?

**Comment by SaiAshish2906** [comment]
Can I try the C version?

**Comment by rahulsunil2** [comment]
Can I work on the Python version please?

**Comment by beccadaniel** [comment]
Can I work on this using Swift?

**Comment by SalmonKing72** [comment]
Sorry I missed you earlier as I was at my son's soccer game... Can I implement this in Ruby?

**Comment by silentwraith6** [comment]
Can I work on it in javascript, actually already generated a pull request for the same

**Comment by disha4u** [comment]
Can i work on java

**Comment by mariothedog** [comment]
I would like to implement this in C#.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
