### ISSUE TITLE
Selection sort

### ISSUE THREAD

**Issue by KamalSagar** [ahampriyanshu/algo_ds_101#415]
**Submission Title**
Selection sort

**Submission Type**
Algorithm

**Submission Description**
Describe the Algo

**Folder Related To**
algo_ds_101=> Algorithms => Selection_Algorithms => Selection_Sort.py

**Contributors**

- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by SOURAB-BAPPA** [comment]
i want to work in this issue
and in which programming language do you want?

**Comment by SUJATA19-could** [comment]
i want to work in this issue in c

**Comment by SOURAB-BAPPA** [comment]
i would like to work in c#, go, c++, python, java, c, R

**Comment by ahampriyanshu** [comment]
@SUJATA19-could go ahead with C
@SOURAB-BAPPA go ahead with  go and R

**Comment by sachin-611** [comment]
I would like to work on this issue in c++ and python

**Comment by aanshi18** [comment]
can I work in ruby?

**Comment by beccadaniel** [comment]
Can I take this in Swift?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
