### ISSUE TITLE
Palindrome

### ISSUE THREAD

**Issue by KN027** [ahampriyanshu/algo_ds_101#449]
Palindrome

Algorithm

To check whether the entered string is palindrome or not.

Algorithms=> String_Algorithms => Palindrome.c

KN

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by zerox029** [comment]
Please assign me Js and Java

**Comment by Vimlesh-Kumar** [comment]
Please Assign me in c++ @ahampriyanshu @Mr-Vaibhav-Shukla

**Comment by Ace117MC** [comment]
please assign me this c++

**Comment by subhadeep1912** [comment]
please assign me for c# thank you

**Comment by junyongxlee** [comment]
Can you assign me for python?

**Comment by swas1820** [comment]
Hi @ahampriyanshu Can you assign me for php?

**Comment by aanshi18** [comment]
can I work for ruby code?

**Comment by adaugochi** [comment]
Hi, @ahampriyanshu I will like to do this in PHP. Can you assign this to me

**Comment by rahulsunil2** [comment]
Can you assign me for Python?

**Comment by joaopedrocampos** [comment]
Hello @ahampriyanshu! Could you please assign me for Typescript?

**Comment by deepjyot** [comment]
Can you assign me for Swift?

**Comment by reyadkhan** [comment]
Hi, I would like to do it in php.

**Comment by hansholani** [comment]
I would like to do this for Golang

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
