### ISSUE TITLE
Modular_Exponentiation

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#451]
**Submission Title**
Modular_Exponentiation

**Submission Type**
Maths_And_Stats

**Submission Description**
The operation of modular exponentiation calculates the remainder when an integer b (the base) raised to the eth power (the exponent), be, is divided by a positive integer m (the modulus). In symbols, given base b, exponent e, and modulus m, the modular exponentiation c is: c = be mod m.

**Folder Related To**
Maths_And_Stats => Series => Modular_Exponentiation => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by jayaganeshkumar** [comment]
@Vimlesh-Kumar  can you assign me this? I will do it

**Comment by Dutta-SD** [comment]
Hi
I would like to commit code in Python

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @jayaganeshkumar Please opt a language

**Comment by jayaganeshkumar** [comment]
@Mr-Vaibhav-Shukla  C, C++ and Java

**Comment by jayaganeshkumar** [comment]
@Mr-Vaibhav-Shukla can you please re-assign me

**Comment by jayaganeshkumar** [comment]
@Mr-Vaibhav-Shukla  done with my tasks. Can you check them out?

**Comment by Dutta-SD** [comment]
@Mr-Vaibhav-Shukla 
I have created a PR regarding my tasks. Do see them.

**Comment by kushkamisha** [comment]
Can do the js implementation

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
