### ISSUE TITLE
Relative_Primes

### ISSUE THREAD

**Issue by Vimlesh-Kumar** [ahampriyanshu/algo_ds_101#454]
**Submission Title**
Relative_Primes

**Submission Type**
Maths_And_Stats

**Submission Description**
In number theory, two integers a and b are said to be relatively prime, mutually prime, or coprime if the only positive integer that divides both of them is 1. Consequently, any prime number that divides one of a or b does not divide the other. This is equivalent to their greatest common divisor being 1

**Folder Related To**
Maths_And_Stats => Series => Relative_Primes => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by preeti-1999** [comment]
I will like to do it in c++

**Comment by Harshalszz** [comment]
Hey! I can do it in C language.

**Comment by Dheeraj-01** [comment]
I would like to do it in java😊

**Comment by shaunak56** [comment]
Please assign me in python

**Comment by LuisFerTR** [comment]
I would like to do it in Golang

**Comment by krishnmohan19** [comment]
HEY @Vimlesh-Kumar .
i would like to do this in javascript. please assign it to me.

**Comment by adaugochi** [comment]
I will like to do this in PHP

**Comment by krishnmohan19** [comment]
hey @Vimlesh-Kumar please assign me in javascript

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
