### ISSUE TITLE
Vector(STL)

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#470]
**Submission Title**
Vector

**Submission Type**
STL

**Submission Description**
Vector is a template class in STL (Standard Template Library) of C++ programming language. 

**Contributors**
- [x]  C++ -

**Comment by KalyanKumar-4** [comment]
can u assign me, i want to work on this

**Comment by prajwlr** [comment]
Can you please explain what exactly do we have to do?

**Comment by ahampriyanshu** [comment]
Demonstrate initialization and various method functions of Vector

**Comment by NishthaThakural** [comment]
Hi, could you please assign it to me? I would like to work on this.

**Comment by MonarchChakri** [comment]
Created a PR https://github.com/ahampriyanshu/algo_ds_101/pull/526
Please review and merge.

**Comment by ahampriyanshu** [comment]
thanks @MonarchChakri :v:
