### ISSUE TITLE
Stacks

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#475]
**Submission Title**
Stacks

**Submission Type**
DS

**Submission Description**
 A stack is an abstract data structure that contains a collection of elements. Stack implements the LIFO mechanism.

**Contributors** 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -
- [ ] C# -
- [ ] Swift -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` ,`` C`` , ``Python`` , ``Java`` versions of this algo have been already implemented .

**Comment by Vortex2wenty** [comment]
Hey, I would like to work on this issue. Thanks.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @Vortex2wenty, please opt a language.

**Comment by MonarchChakri** [comment]
Created a PR https://github.com/ahampriyanshu/algo_ds_101/pull/486.
Please review and merge.

**Comment by gabriel21henrique** [comment]
Hey, I would like to work on it, C# lang 🙂

**Comment by kwong21** [comment]
Created PR #547  for Stack in Go.

**Comment by aorellano** [comment]
Hi, I would like to work on this issue in Swift :)

**Comment by dandynaufaldi** [comment]
Hi, would like to work on Ruby version

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by gabriel21henrique** [comment]
Hello @ahampriyanshu , I created the #798, could you check it out?
