### ISSUE TITLE
Unable to Clone this github repository

### ISSUE THREAD

**Issue by Procoder16** [ahampriyanshu/algo_ds_101#479]
**Describe the bug**
I am unable to clone this repository because of some folder naming issue in your remote github repository.

**To Reproduce**
```bash
git clone https://github.com/ahampriyanshu/algo_ds_101.git
``` 

**Expected behavior**
No errors. It should have been cloned successfully

**Screenshots**
Attached below

![image](https://user-images.githubusercontent.com/71066110/94995907-fce93880-05be-11eb-8196-7084b4e65f0c.png)

![image](https://user-images.githubusercontent.com/71066110/94995959-5baeb200-05bf-11eb-9cc4-005657cd8735.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Please fix the folder renaming issue at https://github.com/ahampriyanshu/algo_ds_101/tree/master/Maths_And_Stats/Algebra/Harmonic_Progression

Please rename the folder named: "def HP(a,d,n): curr_term=a for i in range(1,n+1): temp=a+(i-1)*d print(round((1" to something else.

**Comment by ahampriyanshu** [comment]
Thanks @Procoder16 :heart: 
The issue has been resolved
Thanks again

**Comment by Procoder16** [comment]
This issue was figured out by @Bravo68Web .

**Comment by ahampriyanshu** [comment]
Convey my regards to @BRAVO68WEB:v:
