### ISSUE TITLE
AVL Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#489]
**Submission Title**
AVL Tree

**Submission Type**
DS

**Submission Description**
AVL tree is a self-balancing Binary Search Tree where the difference between heights of left and right subtrees cannot be more than one for all nodes.

**Folder Related To**
Data_Structures => Tree => AVL_Tree => Filename.extension

**Contributors**

- [ ]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Jayanth19524** [comment]
I would like to work on this

**Comment by verma-pulkit** [comment]
I can do the CPP version of this.

**Comment by ahampriyanshu** [comment]
Hi @Jayanth19524 , please mention your preffered language:v:

**Comment by sbhavya18** [comment]
Please assign me this. I will work on C++.

**Comment by ahampriyanshu** [comment]
hi @sbhavya18 please opt a different language/issue

**Comment by subham5230** [comment]
Hey @ahampriyanshu  I would like to work on this in python, Please assign me this

**Comment by Harshalszz** [comment]
Hey! can I work on this in C language.

**Comment by Sanika1999** [comment]
Can I work on this for java

**Comment by Dutta-SD** [comment]
Hi
Can I add code for AVL Tree in Python?

**Comment by Nirali0029** [comment]
Please assign this to me in python

**Comment by Jayanth19524** [comment]
Hi, Jayanth here I will do it in Java. But if c++ is prefered I can do it in c++

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by nimishh7** [comment]
@ahampriyanshu Can you please assign this to me in python ?

**Comment by sahelisaha2k** [comment]
Can you please assign me this for C language?

**Comment by esheetaparulekar** [comment]
Can I work on this issue in php?
