### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#494]
**Submission Title**
Queue

**Submission Type**
DS

**Submission Description**
A queue is an abstract data structure that contains a collection of elements. Queue implements the FIFO mechanism

**Folder Related To**
Data_Structures => Queue =>  Filename.extension

**Contributors**

- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [x] Ruby -
- [x] php -
- [x] Swift -
- [x] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` ,`` C`` , ``Python`` versions of this algo have been already implemented .

**Comment by Singh-Aishwarya** [comment]
Please assign this to me in Java @ahampriyanshu

**Comment by KevinMathewTh** [comment]
Please assign me to PHP

**Comment by bryan-wu** [comment]
Please assign C# to me

**Comment by kushkamisha** [comment]
I could do the js version

**Comment by julianasinai** [comment]
Please assign the go version to me

**Comment by gamezcua1** [comment]
I can do the ruby version!

**Comment by dvrzan** [comment]
I would like to submit a solution in Swift.

**Comment by Anu9518** [comment]
Please assign this to me .

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by duttabhishek32** [comment]
Hey there, I can implement it using C programming. Can you assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
