### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#498]
**Submission Title**
Binary Search Tree

**Submission Type**
Data Structure

**Submission Description**
A binary search tree, also called an ordered or sorted binary tree, is a rooted binary tree whose internal nodes each store a key greater than all the keys in the node's left subtree and less than those in its right subtree.

**Folder Related To**
Data_Structures => Tree => Binary_Search_Tree => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
`` Java`` , ``Python`` versions of this algo have been already implemented .

**Comment by markandevansh99** [comment]
Please Assign me the C++ implementation of the same. I would like to contribute.

**Comment by webmidas** [comment]
Please assign me for php version

**Comment by shaunak56** [comment]
Assign me C. I would like to contribute. Thank you

**Comment by bryan-wu** [comment]
Please assign C# to me

**Comment by verma-pulkit** [comment]
Please assign C to me.

**Comment by AlessandroArosio** [comment]
Can I take the GoLang task please?

**Comment by Astrogeek77** [comment]
@ahampriyanshu @Mr-Vaibhav-Shukla Can you assign this task to me in JS?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
