### ISSUE TITLE
Circular Linked List

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#502]
**Submission Title**
Circular Linked List

**Submission Type**
Data Structure

**Submission Description**
Circular Linked List is a variation of Linked list in which the first element points to the last element and the last element points to the first element. Both Singly Linked List and Doubly Linked List can be made into a circular linked list.

**Folder Related To**
Data_Structures => Linked_List =>  Circular_Linked_List => Filename.extension

**Contributors**

- [x]  C -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` ,`` Java`` ,`` JS`` , ``Python`` versions of this algo have been already implemented .

**Comment by meghna25** [comment]
Hey @ahampriyanshu I'd like to add Circular Linked List implemented in C.

**Comment by gottabpro** [comment]
@ahampriyanshu I would contribute C++ code.

**Comment by bryan-wu** [comment]
Please assign C# to me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
