### ISSUE TITLE
Dynamic Programming: Determine maximum number of coins that can be won

### ISSUE THREAD

**Issue by shaunak56** [ahampriyanshu/algo_ds_101#507]
**Submission Title**
Dynamic Programming: Determine the maximum number of coins that can be won

**Submission Type**
Algorithm

**Submission Description**
Consider a row of n coins of values v1 . . . vn, where n is even. We play a game against an opponent by alternating turns. In each turn, a player selects either the first or last coin from the row, removes it from the row permanently, and receives the value of the coin. Determine the maximum possible amount of money we can definitely win if we move first.

**Folder Related To**
Algorithm => Dynamic Programming => Maximum Achievable coins

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by gottabpro** [comment]
I want to work on this issue. @shaunak56

**Comment by rachleona** [comment]
Can I work on this as well? I can do either python, js or the php one

**Comment by arnav-roy** [comment]
I want to work on this issue in python or c++

**Comment by ahampriyanshu** [comment]
Great :clap: 
 @rachleona , go ahead with php
@arnav-roy , go ahead with c++

**Comment by MohitBhagchandani0601** [comment]
I want to work on this issue in java😊

**Comment by MohitBhagchandani0601** [comment]
i have done that problem in java so i make pull request😊

**Comment by prajwlr** [comment]
I too would love to try this problem in c++, as it seems very interesting. Please assign it to me too.

**Comment by TheBlckCat** [comment]
Hi ✌️,
I want to work on this issuein Python🐍

**Comment by subhadeep1912** [comment]
Hey i can work on this in c#. Please assign me for it. Thank you

**Comment by subhadeep1912** [comment]
i just did for C imma do for C# too

**Comment by ahampriyanshu** [comment]
Hi @subhadeep1912  :wave: 
I'm closing this issue but you can still go ahead and create a PR.

**Comment by ahampriyanshu** [comment]
thanks eveyone :v:
