### ISSUE TITLE
Calculate Easter date for a given year

### ISSUE THREAD

**Issue by M4rkoHR** [ahampriyanshu/algo_ds_101#525]
**Submission Title**
Dynamic programming: Calculate Easter date for given year

**Submission Type**
Algorithm

**Submission Description**
Using Gauss' Easter Algorithm, create an algorithm in preferred language

**Folder Related To**
Algorithm => Dynamic Programming => Gauss_Easter_Date

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by M4rkoHR** [comment]
I would like to do it in C++.

**Comment by kushkamisha** [comment]
I could do in C and JS

**Comment by verma-pulkit** [comment]
I could do this for C.

**Comment by Divya247** [comment]
I would like to do it in Python. can you assign it to me?

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @kushkamisha, Please go ahead in JS.

**Comment by ahampriyanshu** [comment]
Hi @M4rkoHR , your commit has been reverted :bangbang: 
Kindly create new PR with the rectified code
Once again thanks @kushkamisha :+1:

**Comment by AlessandroArosio** [comment]
I'll do in Java

**Comment by kushkamisha** [comment]
I'll do C++

**Comment by hansholani** [comment]
I would like to do this in java. Can I?

**Comment by TheBlckCat** [comment]
Hi ✌️,
I want to work on this issue in Ruby 💎

**Comment by ahampriyanshu** [comment]
Hi @TheBlckCat  :wave: 
I'm closing this issue but you can still go ahead and create a PR.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
