### ISSUE TITLE
Algorithm - QuickSelect - Kth Largest Element in an Array

### ISSUE THREAD

**Issue by abhishekpopli** [ahampriyanshu/algo_ds_101#568]
**Submission Title**
QuickSelect Algorithm

**Submission Type**
Algorithm

**Submission Description**
Quickselect is a selection algorithm to find the k-th smallest element in an unordered list
The algorithm is similar to QuickSort. The difference is, instead of recurring for both sides (after finding pivot), it recurs only for the part that contains the k-th smallest element. 

**Folder Related To**
Repo =>Algorithms => Sorting_Algorithms => Quick_Select

**Contributors**
abhishekpopli

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by abhishekpopli** [comment]
Kindly assign it to me.

**Comment by ArchanaDhaker** [comment]
I want to add this algo in python. kindly assign to me.

**Comment by Avninder99** [comment]
I would like to do this algorithm in JavaScript. Please assign it to me.

**Comment by subham5230** [comment]
I can do this in Java please assign it to me @ahampriyanshu

**Comment by Avninder99** [comment]
Please assign me this algorithm to me for C.

**Comment by Astrogeek77** [comment]
@ahampriyanshu Can you assign this task to me in c?

**Comment by ahampriyanshu** [comment]
Hi @Avninder99 :wave:  go ahead with JS
Hi @Astrogeek77 :wave:  go ahead with C

**Comment by krabhisharma** [comment]
@abhishekpopli assign me this for java

**Comment by ayush-670** [comment]
Can I do this in java?

**Comment by ayush-670** [comment]
I could do it with Ruby too, can you assign it to me in either of the two?

**Comment by reyadkhan** [comment]
Hi, I would like to do it in PHP. Would you like to assign me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
