### ISSUE TITLE
A* Search Algorithm

### ISSUE THREAD

**Issue by Jaswantsinghh** [ahampriyanshu/algo_ds_101#597]
**Submission Title**
A* Search Algorithm

**Submission Type**
Algorithm

**Submission Description**
This algprithm helps in finding the shortest path and graph traversals.

**Folder Related To**
Algorithms => Graph_Algorithms => A_star

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by GerardoUbuntu** [comment]
I want to implement this in TypeScript

**Comment by ulieckstein** [comment]
i would like to do it in c#

**Comment by ahampriyanshu** [comment]
Hi @ulieckstein :wave: 
I'm closing this issue but you can still go ahead and create a PR.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
