### ISSUE TITLE
Gnome Sort

### ISSUE THREAD

**Issue by Sidj581** [ahampriyanshu/algo_ds_101#604]
**Submission Title**
Gnome Sort

**Submission Type**
Algorithm

**Submission Description**
The gnome sort is a sorting algorithm which is similar to insertion sort in that it works with one item at a time but gets the item to the proper place by a series of swaps, similar to a bubble sort. I

**Folder Related To**
Algorithm => Sorting_Algorithm => Gnome_Sort => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by Sidj581** [comment]
Hi @ahampriyanshu please assign this task to me in php, ruby, swift, c#

**Comment by Jaswantsinghh** [comment]
Dear @ahampriyanshu,
Assign me this task for c++

**Comment by meghna25** [comment]
hey @ahampriyanshu I'd like to implement this in java. Please assign it to me.

**Comment by ahampriyanshu** [comment]
Hi @Sidj581,
Your contribution in **c++** and **java** has been reverted
Please push files in approriate directories :v:

**Comment by ahampriyanshu** [comment]
Thanks everyone :v:
