### ISSUE TITLE
Sieve of Erasthonanes

### ISSUE THREAD

**Issue by Jaswantsinghh** [ahampriyanshu/algo_ds_101#609]
**Submission Title**
Sieve of Erasthonanes

**Submission Type**
Maths_And_Stats

**Submission Description**
This algorithm is used to print all prime number up to n.

**Folder Related To**
Maths_And_Stats => Number_Theory => Sieve_Of_Erasthonanes

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Kwehdev** [comment]
Hey, I'd like to do this with TypeScript

**Comment by mariothedog** [comment]
I would like to implement this in C#.

**Comment by Jaswantsinghh** [comment]
I would like to do in C,C++

**Comment by marioa98** [comment]
I would like to implement the solution in Ruby

**Comment by ferdinandjason** [comment]
Hi, could you assign me for Golang version?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
