### ISSUE TITLE
Rabin-Karp Pattern searching agorithm

### ISSUE THREAD

**Issue by Jaswantsinghh** [ahampriyanshu/algo_ds_101#623]
**Submission Title**
Rabin-Karp algorithm

**Submission Type**
Algorithm

**Submission Description**
This algorithm returns all the occurrences of repeating patterns of string.

**Folder Related To**
Algorithm => Pattern_Searching

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by Jaswantsinghh** [comment]
Assign me this for c++.

**Comment by chinmaym07** [comment]
Please assign me this for C .

**Comment by manishita24** [comment]
please assign me this for java

**Comment by AnshMishra2001** [comment]
Can I do this in PHP, pls.

**Comment by manishita24** [comment]
java done. @Jaswantsinghh , please review

**Comment by jayanta007** [comment]
Please assign this to me for javascript

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
