### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#649]
**Submission Title**
Shell Sort

**Submission Type**
Algorithm

**Submission Description**
The method starts by sorting pairs of elements far apart from each other, then progressively reducing the gap between elements to be compared.

**Folder Related To**
Algorith => Sorting_Algorithm => Shell_Sort =>Shell_Sort.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rishav311** [comment]
I want to work on this

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by divyanshrastogi51** [comment]
I would like to work on this in Javascript

**Comment by AnaGVF** [comment]
I would very much like to work on this algorithm in C++ !

**Comment by Harshalszz** [comment]
Hey! can I work on this in C.

**Comment by varad64** [comment]
Hi, I'd like to work on it using Java. Could you please assign me to this?

**Comment by Arsenic-ATG** [comment]
I would like to work on it in swift.

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by Rudransh24** [comment]
Can you please assign this to me in C?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
