### ISSUE TITLE
Tree_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#652]
**Submission Title**
Tree_Sort

**Submission Type**
Algorithm

**Submission Description**
A tree sort is a sort algorithm that builds a binary search tree from the elements to be sorted, and then traverses the tree so that the elements come out in sorted order. 

**Folder Related To**
Algorith => Sorting_Algorithm => Tree_Sort => Tree_Sort.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by garimamishraa** [comment]
Can I implement using c++ ?

**Comment by jossiey** [comment]
I can implement this algorithm in Java

**Comment by LSpajic** [comment]
Can i do it in python?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
