### ISSUE TITLE
Heap_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#653]
**Submission Title**
Heap_Sort

**Submission Type**
Algorithm

**Submission Description**
Heap sort is a comparison based sorting technique based on Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end. 

**Folder Related To**
Algorith => Sorting_Algorithm => Heap_Sort => Heap_Sort.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x] Java - 
- [x] TypeScript -
- [x] Golang -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by git-bit-code** [comment]
Hey @ahampriyanshu , i would like to work on this issue.

**Comment by garimamishraa** [comment]
Can i implement using python?

**Comment by ahampriyanshu** [comment]
Hi @garimamishraa ,
Heap Sort has already been implemented in python.
Please opt a different language/issue.

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in c# language.

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu please assign this to me.

**Comment by ahampriyanshu** [comment]
Hi @git-bit-code ,
Your contribution has been reverted :warning: 
Please push a valid file from the next time
:v:

**Comment by garimamishraa** [comment]
I will use java?

**Comment by swas1820** [comment]
Hi I can do it in PHP. Please assign me.

**Comment by ferdinandjason** [comment]
@ahampriyanshu Hi, could you assign me for Golang version?

**Comment by jayanta007** [comment]
@ahampriyanshu I make changes in C language

**Comment by ukitta555** [comment]
Would love to work on it. Language - Javascript

**Comment by varad64** [comment]
Hi, I'd like to work on it using Java. Could you please assign me to this?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
