### ISSUE TITLE
Affine_Cipher

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#661]
**Submission Title**
Affine_Cipher

**Submission Type**
Algorithm

**Submission Description**
The affine cipher is a type of monoalphabetic substitution cipher, where each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter. 

**Submission Directory**
Algorithm => Cryptography_Algorithm => Affine_Cipher => Affine_Cipher.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by strikeraryu** [comment]
I like to get assigned for this issue 
> I will implement the requested algorithm in python 
> add custom function support and fix different case support (i.e uppercase and lowercase) in the file added for c++

**Comment by Rudransh24** [comment]
Can you assign this to me in C/C++??

**Comment by prakhar-agarwall** [comment]
I'd like to take up this issue in C++ or C

**Comment by ahampriyanshu** [comment]
Hi @Rudransh24, go ahead with C.
Hi @prakhar-agarwall, please opt a different language/issue.
:v:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
