### ISSUE TITLE
Bifid_Cipher

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#663]
**Submission Title**
Bifid_Cipher

**Submission Type**
Algorithm

**Submission Description**
In classical cryptography, the bifid cipher is a cipher which combines the Polybius square with transposition, and uses fractionation to achieve diffusion. 

**Submission Directory**
Algorithm => Cryptography_Algorithm => Bifid_Cipher => Bifid_Cipher.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by abhinav-idle** [comment]
I would like to do this in python.
Please assign me this to work on.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
