### ISSUE TITLE
Caesar_Cipher

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#664]
**Submission Title**
Caesar_Cipher

**Submission Type**
Algorithm

**Submission Description**
 It's simply a type of substitution cipher, i.e., each letter of a given text is replaced by a letter some fixed number of positions down the alphabet.

**Submission Directory**
Algorithm => Cryptography_Algorithm => Caesar_Cipher => Caesar_Cipher.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by garimamishraa** [comment]
I'll Implement using python and C++

**Comment by 3t8** [comment]
I'll implement it in C and Javascript

**Comment by Kwehdev** [comment]
May I take TypeScript?

**Comment by rachleona** [comment]
I can do one in php

**Comment by marioa98** [comment]
Can I implemented using Ruby?

**Comment by daviddavo** [comment]
Is Java still available?

**Comment by shrutikdev** [comment]
Can I contribute to this for python?

**Comment by brane** [comment]
I'm up for C#

**Comment by dinendra007** [comment]
i can implement it in scala

**Comment by Kishore-abhimanyu** [comment]
I like to work this in python.Please add me to this issue

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
