### ISSUE TITLE
Vernam_Cipher

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#666]
**Submission Title**
Vernam_Cipher

**Submission Type**
Algorithm

**Submission Description**
Vernam cipher is a symmetrical stream cipher in which the plaintext is combined with a random or pseudorandom stream of data (the "keystream") of the same length, to generate the ciphertext, using the Boolean "exclusive or" (XOR) function.

**Submission Directory**
Algorithm => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by meteoritenhagel** [comment]
I'd like to do the task in C++, please.

**Comment by adrputra** [comment]
I can do it in python and php

**Comment by adrputra** [comment]
I will do in python

**Comment by shubham2704** [comment]
@ahampriyanshu i would like to do it in javascript

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
