### ISSUE TITLE
Vigenere_Cipher

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#667]
**Submission Title**
Vigenere_Cipher

**Submission Type**
Algorithm

**Submission Description**
The Vigenère Cipher is a method of encrypting alphabetic text by using a series of interwoven Caesar ciphers, based on the letters of a keyword. It employs a form of polyalphabetic substitution.

**Submission Directory**
Algorithm => Cryptography_Algorithm => Vigenere_Cipher => Vigenere_Cipher.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by meteoritenhagel** [comment]
I'd like to do the C++ task. Please assign me to it.

**Comment by william-gooch** [comment]
I'd like to take the C# version if possible.

**Comment by am401** [comment]
Hello there. I'd like to work on this in Python if possible! Thank you!

**Comment by HarryPeach** [comment]
I'll do this in Go

**Comment by Kishore-abhimanyu** [comment]
I like to work this in python.Please add me to this issue

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
