### ISSUE TITLE
Validate BST

### ISSUE THREAD

**Issue by ShristiAgrawal** [ahampriyanshu/algo_ds_101#676]
**Submission Title**
Validate BST

**Submission Type**
Data Structure

**Submission Description**
Check if given tree is BSTL

**Submission Directory**
algo_ds_101 -> tree -> master -> Data_Structures ->Tree ->Binary_Search_Tree ->validate_bst.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by Ace117MC** [comment]
can i do this in c++

**Comment by esheetaparulekar** [comment]
Can I contribute in Java?

**Comment by Vivek-Raman** [comment]
I'd like to solve this problem in C#!

**Comment by daviddavo** [comment]
It's this still available in Python?

By the way, It would be interesting to add solutions to some problems also using Haskell or Prolog

**Comment by ahampriyanshu** [comment]
Hi @daviddavo :wave: 
Great suggestion :+1: 
If you got any ideas , go ahead and create a new issue
Thanks & Regard
@ahampriyanshu :v:

**Comment by amogh2019** [comment]
Can I contribute in C++?

**Comment by amogh2019** [comment]
@ahampriyanshu Can I contribute in C++?

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
