### ISSUE TITLE
Validate BST

### ISSUE THREAD

**Issue by GitanshKapoor** [ahampriyanshu/algo_ds_101#680]
**Submission Title**
Bubble Sort/AVL Graph/Vector

**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
Describe the Algo/DS/STL

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**

- [x]  C++ - yes
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
Duplicate issue :warning:
