### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#684]
**Submission Title**
Dijkstra's Algorithm

**Submission Type**
Algorithm/Graph_Algorithms/Dijkstra

**Submission Description**
Describe the Dijsktra's Algorithm to find the shortest path between two nodes in a graph

**Folder Related To**
Algorithm => Graph_Algorithm => Dijkstra => Dijkstra.cpp

**Contributors**

- [x]  C -
- [x]  Python -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` ,`` JS`` , ``Java`` versions of this algo have already been implemented .

**Comment by mhimanshu712** [comment]
I can do C.

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by daviddavo** [comment]
Can I do it in php?

**Comment by ferdinandjason** [comment]
Hi, could you assign me for Golang version?

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
