### ISSUE TITLE
Trie Search

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#685]
**Submission Title**
Trie Search

**Submission Type**
Algorithm

**Submission Description**
Describe the Algo/DS/STL

**Folder Related To**
Algorithm => Search_Algorithm => Trei_Search => Filename.extension

**Contributors**

- [x]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` version of this algo has already been implemented .

**Comment by sbhavya18** [comment]
I can implement this in C. Please assign me this.

**Comment by jayanta007** [comment]
@ahampriyanshu , working for python version

**Comment by onkargagare** [comment]
Please assign me for Java

**Comment by ukitta555** [comment]
Would love to work on it using JS.

**Comment by ravi7799** [comment]
I implemented Trie using HashMap For better space constraints in java.
hope u will assign me for java implementation

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
