### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#686]
**Submission Title**
LIS

**Submission Type**
Algorithmal

**Submission Description**
Longest increasing subsequence problem is to find a subsequence of a given sequence in which the subsequence's elements are in sorted order, lowest to highest, and in which the subsequence is as long as possible.

Folder Related To
Algorithm => Dynamic_Programming => LIS => Filename.extension

**Contributors**

- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` version of this algo has already been implemented .

**Comment by Amulya-coder** [comment]
Can I do it in C. Please Assign it.

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by ferdinandjason** [comment]
Hi, could you assign me for Golang version?

**Comment by jayanta007** [comment]
@ahampriyanshu please assign me for Java

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
