### ISSUE TITLE
Harmonic_Progression

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#688]
**Submission Title**
Harmonic_Progression

**Submission Type**
Maths_And_Stats

**Submission Description**
A harmonic progression is a sequence of real numbers formed by taking the reciprocals of an arithmetic progression.

**Folder Related To**
Maths_And_Stats => Series => Harmonic_Expression => Harmonic_Expression.extension

**Contributors**

- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``C++`` , ``Swift`` versions of this algo have already been implemented .

**Comment by aditya-malik-r** [comment]
Hi if possible I'd like to do the Java implementation for this.

**Comment by Nirali0029** [comment]
I would like to implement this in python

**Comment by appsx13** [comment]
Can i do it in python or javascript?

**Comment by Harshalszz** [comment]
Hey! can I work on this in C.

**Comment by shubham2704** [comment]
@ahampriyanshu i would like to do it in Ruby. pleas assign me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
