### ISSUE TITLE
Euler_Approximation

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#690]
**Submission Title**
Euler_Approximation

**Submission Type**
Maths_And_Stats

**Submission Description**
Euler_Approximation method is a first-order numerical procedure for solving ordinary differential equations with a given initial value. 

**Folder Related To**
Maths_And_Stats => Calculus =>  Euler_Approximation =>  Euler_Approximation.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by ahampriyanshu** [comment]
Hi @everyone :wave: ,
``Java`` version of this algo has already been implemented .

**Comment by sbhavya18** [comment]
I can implement in c++. kindly assign me this

**Comment by huisenbr** [comment]
Added pull request for C#

**Comment by Kartik-byte** [comment]
Hey I would like to do this in python. Can you please assign me this?
Thank you.

**Comment by Rudransh24** [comment]
Can you please assign this to me in c, c++ or python?

**Comment by Mr-Vaibhav-Shukla** [comment]
> Can you please assign this to me in c, c++ or python?

Go ahead in C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
