### ISSUE TITLE
Sudoku_Solver

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#694]
**Submission Title**
Sudoku_Solver

**Submission Type**
Algorithm

**Folder Related To**
Algorithm => Dynamic_Programming => Sudoku_Solver => File.ext

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Amulya-coder** [comment]
@ahampriyanshu I want to contribute to this in C++. Can you Please assign it to me.

**Comment by sbhavya18** [comment]
I can contribute in C. Kindly assign this to me.

**Comment by chinmaym07** [comment]
I can do it in Java .Please assign it to me.

**Comment by CormacKrum** [comment]
Please Assign It to me in Python

**Comment by adidesh07** [comment]
I can contribute to this issue in Python, if assigned. Thanks

**Comment by ahampriyanshu** [comment]
Hi @adidesh07 :wave: 
Please opt a different language/issue :grin:

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by Zaman3027** [comment]
I would like to work on TypeScript please assign this to me

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
