### ISSUE TITLE
Z_Algorithm

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#695]
**Submission Title**
Z_Algorithm

**Submission Type**
Algorithm

**Submission Description**
This algorithm finds all occurrences of a pattern in a text in linear time. Let length of text be n and of pattern be m, then total time taken is O(m + n) with linear space complexity. 

**Folder Related To**
Algorithm => Dynamic_Programming => Z_Algorithm => Z_Algorithm.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by chinmaym07** [comment]
Can you assign it to me for C++?@ahampriyanshu

**Comment by Dutta-SD** [comment]
I would like to work on this in Python.

**Comment by Rudransh24** [comment]
Can you assign this to me in C ?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
