### ISSUE TITLE
Tower_Of_Hanoi

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#697]
**Submission Title**
Tower_Of_Hanoi

**Submission Type**
Algorithm

**Submission Description**
The Tower of Hanoi is a mathematical game or puzzle. It consists of three rods and a number of disks of different sizes, which can slide onto any rod.

**Folder Related To**
Algorithm => Dynamic_Programming => Tower_Of_Hanoi => Tower_Of_Hanoi.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by yogeswarl** [comment]
Can I take this up with Javascript?

**Comment by betsystevens** [comment]
I can do this in JavaScript.

**Comment by mhimanshu712** [comment]
I can do it in C++ and C.

**Comment by chinmaym07** [comment]
Can I do this in C.?

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by neha0123** [comment]
please assign it to me in c++.

**Comment by harshitgupta2000** [comment]
I can do it in Java please assign it to me

**Comment by shubhamsavarn** [comment]
please assign me this task to me in type script ruby php and swift

**Comment by hyunjiLeeTech** [comment]
Can I do this in C#?

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by deveshteotia12** [comment]
Please assign it to me, I'll do it in c++

**Comment by Rudransh24** [comment]
Can you assign this to me in C ?

**Comment by ulieckstein** [comment]
i'd like to do this in go

**Comment by sid-1207** [comment]
Hey can you assign this issue to me?
I will solve it in C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
