### ISSUE TITLE
Cocktail_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#698]
**Submission Title**
Cocktail_Sort

**Submission Type**
Algorithm

**Submission Description**
The algorithm extends bubble sort by operating in two directions.

**Folder Related To**
Algorithm => Sorting_Programming => Cocktail_Sort => Cocktail_Sort.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rainbow-Ninja** [comment]
Can I complete this using ruby?

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in python language. Please assign this to me.

**Comment by sbhavya18** [comment]
i can contribute to this issue in c++. please assign me this.

**Comment by jyotipro10** [comment]
Can you please assign it to me in Python?

**Comment by chinmaym07** [comment]
Hey **@ahampriyanshu**  Can you please assign it to me .I would like to do in C.

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu  i have made a PR please look at it. Also you please make me an assignee.

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu  Please give some insights about the error ocurring in the runtime in my PR.

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu  can i contribute cocktail sort tail in java language.

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu Please give some insights about the error ocurring in the runtime in my PR.

Hello @TechnoPhasePRO :wave: 
I have the master branch's security rules but not the **.yml** conf file of welcome bot
Will fix it later :v:

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu Please look at the PR #870 made, I have added cocktail sort in java language.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
