### ISSUE TITLE
Comb_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#699]
**Submission Title**
Comb_Sort

**Submission Type**
Algorithm

**Submission Description**
Comb sort is a comparison based sorting algorithm which improves on bubble sort. In bubble sort, the adjacent elements are compared for sorting the array.

**Folder Related To**
Algorithm => Sorting_Programming => Comb_Sort => Comb_Sort.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rainbow-Ninja** [comment]
Can I do this in ruby?

**Comment by manvendra3** [comment]
Assign this to me in c++

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in python language. Please assign this to me.

**Comment by chinmaym07** [comment]
Hey **@ahampriyanshu**  Can you Please assign it to me . I would like to do in C.

**Comment by kishore-tw** [comment]
Can you please assign me to this?

**Comment by Kishore-abhimanyu** [comment]
Can you please assign me to this?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
