### ISSUE TITLE
Stooge_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#700]
**Submission Title**
Stooge_Sort

**Submission Type**
Algorithm

**Submission Description**
Stooge Sort is a recursive sorting algorithm. It is inefficient but interesting sorting algorithm. It divides the array into two overlapping parts (2/3 each). 

**Folder Related To**
Algorithm => Sorting_Programming => Stooge_Sort => Stooge_Sort.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by rguzg** [comment]
Hey, can I try this on Python?

**Comment by NEENA-XAVIER** [comment]
May I work on this?
