### ISSUE TITLE
Tim_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#701]
**Submission Title**
Tim_Sort

**Submission Type**
Algorithm

**Submission Description**
Timsort is a hybrid stable sorting algorithm, derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data. 

**Folder Related To**
Algorithm => Sorting_Programming => Tim_Sort => Tim_Sort.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by chinmaym07** [comment]
Can I do this in C++.?

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in python language. Please assign this to me.

**Comment by firehawk23** [comment]
@ahampriyanshu i would like like to work in this in java. Can you assign it to me.

**Comment by afeefaa333** [comment]
Shall I try this in C language?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
