### ISSUE TITLE
Pancake_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#702]
**Submission Title**
Pancake_Sort

**Submission Type**
Algorithm

**Submission Description**
Pancake sorting is the colloquial term for the mathematical problem of sorting a disordered stack of pancakes in order of size when a spatula can be inserted at any point in the stack and used to flip all pancakes above it. 

**Folder Related To**
Algorithm => Sorting_Programming => Pancake_Sort => Pancake_Sort.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by syamilAbdillah** [comment]
i'll try it in js

**Comment by Veguinho** [comment]
I can do it in Python

**Comment by chinmaym07** [comment]
Can I do this in C++.?

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in python language. Please assign this to me.

**Comment by gamezcua1** [comment]
I can do it in Ruby 🙌

**Comment by AlessandroArosio** [comment]
Can I do a pancake (yummy) sort in Java?

**Comment by RahulRS246** [comment]
i would like to do this in java

**Comment by ahampriyanshu** [comment]
Hi @TechnoPhasePRO & @RahulRS246 :wave: 
Please opt a different language/issue :v:

**Comment by huisenbr** [comment]
Can you add me for C#

**Comment by Rudransh24** [comment]
hey! can you please assign this to me in C ?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
