### ISSUE TITLE
Circle_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#703]
**Submission Title**
Circle_Sort

**Submission Type**
Algorithm

**Submission Description**
Circle sort algorithm can be visualized by drawing concentric circles on an array of integers. 

**Folder Related To**
Algorithm => Sorting_Programming => Circle_Sort => Circle_Sort.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Rainbow-Ninja** [comment]
Can I work on this issue in ruby?

**Comment by gamezcua1** [comment]
I can do the ruby version

**Comment by sbhavya18** [comment]
i can implement this in c++. kindly assign me

**Comment by afeefaa333** [comment]
Shall I try this in Java?

**Comment by chinmaym07** [comment]
Hey **@ahampriyanshu**  I would like to do in C. Please assign it to me.

**Comment by huisenbr** [comment]
I will do this in C#

**Comment by Sanika1999** [comment]
can I do this for python?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
