### ISSUE TITLE
Counting_Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#704]
**Submission Title**
Counting_Sort

**Submission Type**
Algorithm

**Submission Description**
In computer science, counting sort is an algorithm for sorting a collection of objects according to keys that are small integers; that is, it is an integer sorting algorithm. 

**Folder Related To**
Algorithm => Sorting_Programming => Counting_Sort => Counting_Sort.ext

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by GuilhermeOliveiraCasagrande** [comment]
Hi can I work on this algorithm?

**Comment by chinmaym07** [comment]
Hey can you assign this to me for C++.?

**Comment by TechnoPhasePRO** [comment]
@ahampriyanshu hey, i would like to work on this issue. I would create it in python language. Please assign this to me.

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by neha0123** [comment]
@ahampriyanshu  hey, i would like to work on this issue in c++ language,please assign it to me

**Comment by Chitresh13** [comment]
I am working it on java

**Comment by appsx13** [comment]
Can i do it in python or javascript?

**Comment by RuchaYagnik** [comment]
Hey @ahampriyanshu can I do it in C ?

**Comment by solanki2899** [comment]
i want to solve it in python.

**Comment by ahampriyanshu** [comment]
Hi @solanki2899 ,
Please opt a different language/issue.
:v:

**Comment by GuilhermeOliveiraCasagrande** [comment]
Hey can I work on this algorithm with javascript?

**Comment by ferdinandjason** [comment]
Hi, could you assign me for Golang version?

**Comment by solanki2899** [comment]
@ahampriyanshu can you pls check whats wrong in my pull request, It is showing some error

**Comment by GuilhermeOliveiraCasagrande** [comment]
@ahampriyanshu it appears that my pull request had an error in sending the welcome message or something

**Comment by solanki2899** [comment]
@GuilhermeOliveiraCasagrande are you also facing welcome run error?

**Comment by GuilhermeOliveiraCasagrande** [comment]
Yes,
`Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration`
in the`Run bubkoo/welcome-action@v1`

**Comment by ahampriyanshu** [comment]
My bad  :sweat_smile: 
I have just updated master branch security rules but not the welocme bot  **.yml**
Thanks @solanki2899 and @GuilhermeOliveiraCasagrande for reporting :clap: :clap:

**Comment by brane** [comment]
I'm up for C#

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
