### ISSUE TITLE
Strassens_Algorithm

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#707]
**Submission Title**
Strassens_Algorithm

**Submission Type**
Algorithm

**Submission Description**
In linear algebra, the Strassen algorithm, named after Volker Strassen, is an algorithm for matrix multiplication. It is faster than the standard matrix multiplication algorithm and is useful in practice for large matrices, but would be slower than the fastest known algorithms for extremely large matrices.

**Folder Related To**
Maths_And_Stats => Algebra => Strassens_Algorithm => Strassens_Algorithm.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by chinmaym07** [comment]
Can you assign this to me for C++.?

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by CormacKrum** [comment]
Please Assign this to me For Java

**Comment by DhruvaG2000** [comment]
would like to work on this in c++, 
Kindly assign

**Comment by ahampriyanshu** [comment]
> would like to work on this in c++ or python whichever needed,
> Kindly assign

Hi @DhruvaG2000 :wave: ,
Both of them have already been done.
Please opt a different language/issue.
:v:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
