### ISSUE TITLE
Markov_Matrix

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#708]
**Submission Title**
Markov_Matrix

**Submission Type**
Algorithm

**Submission Description**
Each of its entries is a nonnegative real number representing a probability. It is also called a probability matrix, transition matrix, substitution matrix, or Markov matrix.

**Folder Related To**
Maths_And_Stats => Algebra => Markov_Matrix => Markov_Matrix.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by manvendra3** [comment]
can i do this in c++

**Comment by chinmaym07** [comment]
Can you assign it to me for C++.?

**Comment by appsx13** [comment]
Can you assign me this for python?

**Comment by GuilhermeOliveiraCasagrande** [comment]
Can I be assigned for a javascript implementation?

**Comment by GuilhermeOliveiraCasagrande** [comment]
I have some problems. First, does it needs to find out if a given square matrix is a markov matrix or does it need to generate one?

**Comment by ahampriyanshu** [comment]
Hi @GuilhermeOliveiraCasagrande :clap: 
The program needs to determine whether the matrix entered is a markov matrix or not :v:

**Comment by ulieckstein** [comment]
i'll do it in c#

**Comment by ukitta555** [comment]
Assign me for JS please.

**Comment by GuilhermeOliveiraCasagrande** [comment]
Already done @ukitta555, check here if you can improve it #874

**Comment by ahampriyanshu** [comment]
Hi @ukitta555 :wave: 
Please opt a different language/issue :v:

**Comment by GregPikitis** [comment]
I can do it in Java!

**Comment by DhruvaG2000** [comment]
I can do it in c++

**Comment by ahampriyanshu** [comment]
Thanks everyone :v:
