### ISSUE TITLE
Lucas_Series

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#709]
**Submission Title**
Lucas_Series

**Submission Type**
Algorithm

**Submission Description**
The Lucas numbers or Lucas series are an integer sequence named after the mathematician François Édouard Anatole Lucas (1842–91), who studied both that sequence and the closely related Fibonacci numbers.

**Folder Related To**
Maths_And_Stats => c => Lucas_Series => Lucas_Series.ext

**Contributors**

- [ ]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [x] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [x] php -
- [ ] Swift -
- [x] C# -

**Comment by lucid-dreem** [comment]
Could I be assigned the C++ version?

**Comment by chinmaym07** [comment]
Can you assign this to me for C.?

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by Chitresh13** [comment]
I want to contribute in java.

**Comment by aanneettgg** [comment]
id like to work on this in C#

**Comment by jyotipro10** [comment]
Can you assign it to me in Java ?

**Comment by adrputra** [comment]
I'll do it in php

**Comment by chinmaym07** [comment]
Hey @ahampriyanshu  I have already added my assigned work for C code of Lucas Series earlier .. Please Check.

**Comment by Sayantan-world** [comment]
I want to code it in JavaScript. Can you assign it to me?

**Comment by tomasloksa** [comment]
Doing this in typescript

**Comment by Rudransh24** [comment]
Hello! Can you assign it to me in C++(recursive/non-recursive solution)?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:

**Comment by parauliya** [comment]
@ahampriyanshu, I think you have missed last couple of PRs.
