### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#71]
**Submission Title**
Arrays

**Submission Type**
Data Structure

**Submission Description**
 An array in C or C++ is a collection of items stored at contiguous memory locations

**Contributors**
- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] Golang -

**Comment by evandroLutz** [comment]
I wanted to better understand what you need :D

**Comment by sbhavya18** [comment]
I want to implement it in c++. Kindly assign me this. Also brief a little for better unsderstanding.

**Comment by ahampriyanshu** [comment]
> I wanted to better understand what you need :D

Declaration, initialization, insertion, deletion ,searching an element and all the other various operation on arrays .

**Comment by ahampriyanshu** [comment]
thanks @Shyamashrita and @harshita-sharma11 :v:
