### ISSUE TITLE
Ugly_Number

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#710]
**Submission Title**
Ugly_Number

**Submission Type**
Algorithm

**Submission Description**
Write a program to check whether a given number is an ugly number. Ugly numbers are positive numbers whose prime factors only include 2, 3, 5 . 

**Folder Related To**
Maths_And_Stats => Number_Theory => Ugly_Number => Ugly_Number.ext

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by caspero-62** [comment]
can i take this in javascript?

**Comment by theniteshnarang** [comment]
Is anyone assigned? I want to contribute in it for JavaScript.

**Comment by marioa98** [comment]
Can I contribute to this one using Ruby?

**Comment by Veguinho** [comment]
I can contribute with Python! Is anyone assigned for it yet?

**Comment by tdserapio** [comment]
I may also contribute to Python! Is anyone assigned for this language yet?

**Comment by lokeshm29** [comment]
Can I contribute to this one using C# ?

**Comment by chinmaym07** [comment]
Can I do this in c.?

**Comment by Mr-Destructive** [comment]
can I do this in bash?

**Comment by Amulya-coder** [comment]
Can I contribute to this in C++.

**Comment by esheetaparulekar** [comment]
Can I contribute in Java?

**Comment by ahampriyanshu** [comment]
Hi @tdserapio :wave:  ,
Please opt a different language/issue. :grin:

**Comment by parauliya** [comment]
@ahampriyanshu , Can you please assign this to me in Golang?

**Comment by AnshMishra2001** [comment]
Can I code this in Swift, pls?

**Comment by appsx13** [comment]
Can i do it in python?

**Comment by Rainbow-Ninja** [comment]
Can i do this in ruby?

**Comment by apostolosdiavolitsis** [comment]
Can i do it for PHP?

**Comment by ChampInMyThought** [comment]
May I queue up for C, C++, and Python?

**Comment by ahampriyanshu** [comment]
Hi @ChampInMyThought
Please opt a different language/issue :v:

**Comment by BhargaviChada** [comment]
Can  I take this in Java

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
