### ISSUE TITLE
Map/Hash/Dict

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#72]
**Submission Title**
Map/Hash/Dict

**Submission Type**
Data Structure

**Submission Description**
Map/Hash/Dict are associative containers that store elements formed by a combination of a key value and a mapped value.

**Contributors**
- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] Golang -

**Comment by NunoAGoncalves** [comment]
I can/have created a hash set with quadratic probing in Java. Not sure if that’s an appropriate solution to the issue, but if it is, I’d like to be assigned for this issue.

**Comment by shaunak56** [comment]
Do we have to demonstrate the Map/Hash/Dict functionality?

**Comment by ahampriyanshu** [comment]
yup @shaunak56 ,initialization and method funtions

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
