### ISSUE TITLE
Graph folder in Data Structures

### ISSUE THREAD

**Issue by ayush-670** [ahampriyanshu/algo_ds_101#726]
Can I add a folder of Graph Algorithms in Data Structures?

**Comment by Shreyansh252001** [comment]
yes you can! i can do this for you but where is the Data Structures repo?

**Comment by NidhiNivedita6** [comment]
Can I add my Newton Raphson Method code in C?

**Comment by Mayankjha997** [comment]
yes @ayush-670 
you can add folder of graph Algorithm in data structures
please assign me ! I will do lagrange Interpolaion in c++

**Comment by NidhiNivedita6** [comment]
Can I add my code for Newton Raphson Method in C?

**Comment by ayush-670** [comment]
Sure, I'll work on adding graph algorithms folder in data structures.

**Comment by Mayankjha997** [comment]
@ayush-670  Please review and merge my PR #869

**Comment by Harshalszz** [comment]
Hey ! can I add Kruskal Algorithm in C++.

**Comment by Shreyansh252001** [comment]
i understood now i can add any algo of your choice with reference if you assign it to me.please assign me!!!!!!

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
