### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#73]
**Submission Title**
Queues

**Submission Type**
DS

**Submission Description**
A queue is an abstract data structure that contains a collection of elements. Queue implements the FIFO mechanism

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ankitgoel25** [comment]
@ahampriyanshu I would like to work on this issue in C++ language.

**Comment by ankitgoel25** [comment]
Hi @ahampriyanshu , this is my first time contributing to Hactoberfest and open source as well. I made a pull request for the issue in C++ language. Please review my PR and do tell me if I need to do some corrections.
Thank You

**Comment by chiragjagad** [comment]
Hey, I would like to take this project and implement in Python

**Comment by rahulsunil2** [comment]
I would like to implement this in Python.

**Comment by ahampriyanshu** [comment]
thanks @ankitgoel25, @chiragjagad and @ssarkar786 :v:
