### ISSUE TITLE
Stooge Sort

### ISSUE THREAD

**Issue by rguzg** [ahampriyanshu/algo_ds_101#734]
**Submission Title**
Stooge Sort

**Submission Type**
Algorithm

**Submission Description**
Stooge Sort sorts an array of numbers by dividing it into thirds

**Submission Directory**
Algorithm => Sorting_Programming => Stooge_Sort => Stooge_Sort.py

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by AnshMishra2001** [comment]
Can I work on this, pls?

**Comment by parth93QA** [comment]
can you assign me for golang

**Comment by Avninder99** [comment]
Can you assign this to me for C++ and JavaScript ?

**Comment by huisenbr** [comment]
Can you add me for C#?

**Comment by Rudransh24** [comment]
Can you assign this problem to me in C/C++?
@ahampriyanshu

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
