### ISSUE TITLE
Find cycle in a Linked List

### ISSUE THREAD

**Issue by Shreyash0713** [ahampriyanshu/algo_ds_101#737]
**Submission Title**
Find cycle in a Linked List

**Submission Type**
Data Structure

**Submission Description**
Given a linked list, check if the linked list has loop or not

**Submission Directory**
Main_Folder => Data_Structures => Linked_List => Singly_Linked_List => DetectCycle.cpp

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Shreyash0713** [comment]
Can I work on this issue, please review.

**Comment by AnshMishra2001** [comment]
Can I code this in cpp

**Comment by vrinda41198** [comment]
Hello, can I work on this issue?

**Comment by garimamishraa** [comment]
Can i implement this using C++?

**Comment by esheetaparulekar** [comment]
Can I contribute in Java?

**Comment by Sayantan-world** [comment]
Can I implement this in Python?

**Comment by ahampriyanshu** [comment]
Hi @garimamishraa 
Please opt a different language/issue :v:

**Comment by jyotipro10** [comment]
Can I write in C#? Please assign it to me.

**Comment by vrinda41198** [comment]
Hi, it seems that the C++ code has already been submitted and merged, can I submit the solution in Golang?

**Comment by kachus22** [comment]
Hey, I would like to submit it with TypeScript

**Comment by nayanika0208** [comment]
hey can i do this in javascript??

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by gamezcua1** [comment]
I'd like to do it with Ruby 🙌

**Comment by truthfool** [comment]
I would like to do it with python with detailed explanation using tortoise method:-)

**Comment by truthfool** [comment]
I would like to do it in swift using tortoise method:-)

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by viveksahu26** [comment]
Hey @Shreyash0713 ., i would like to work on this issue in Golang. Can you assign this to me..

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
