### ISSUE TITLE
Stacks

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#74]
**Submission Title**
Stacks

**Submission Type**
DS

**Submission Description**
 A stack is an abstract data structure that contains a collection of elements. Stack implements the LIFO mechanism.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by aderio25** [comment]
I would like to contribute implement stack in Python, let assign this task to me.

**Comment by GhostUser** [comment]
I would like to work on this, pls assign. I'll use python.

**Comment by sbhavya18** [comment]
Kindly assign me this. I want to implement it in c++.

**Comment by GhostUser** [comment]
Created a PR for stacks implementation using python. 
#132

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @ahampriyanshu , Please assign me this issue in C

**Comment by ahampriyanshu** [comment]
thanks @GhostUser and @Mr-Vaibhav-Shukla :v:

**Comment by jytaloramon** [comment]
Happy to contribute!

**Comment by GhostUser** [comment]
Thank you for the opportunity!
