### ISSUE TITLE
AVL Tree

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#75]
**Submission Title**
AVL Tree

**Submission Type**
DS

**Submission Description**
AVL tree is a self-balancing Binary Search Tree where the difference between heights of left and right subtrees cannot be more than one for all nodes.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by sbhavya18** [comment]
Please assign me this. I will submit my work in C++.

**Comment by mrselukar** [comment]
Hi, Would like to do this in python. Please assign it if possible.

**Comment by Mr-Vaibhav-Shukla** [comment]
Dear @sbhavya18 Kindly make a valid PR

**Comment by sbhavya18** [comment]
@Mr-Vaibhav-Shukla Thanks for pointing out. This is my first attempt in making pull request. Can u please tell me where did I go wrong.

**Comment by ahampriyanshu** [comment]
Hi @sbhavya18 :wave:  , it looks like you are creating a PR within the different branches of your  forked repo.
Kindy create a PR from your forked repo to the master branch my repo.
See the new ``README.md`` for more clarification:v:
