### ISSUE TITLE
Vector

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#76]
**Submission Title**
Vector

**Submission Type**
STL

**Submission Description**
Vector is a template class in STL (Standard Template Library) of C++ programming language. 

**Contributors**
- [x]  C++ -

**Comment by ankur-kayal** [comment]
Can i work on this? i can explain all the member functions of the vector class in c++ stl.

**Comment by sbhavya18** [comment]
I want to work on this. I will give precise yet complete information of all the required functionalities associated along with demonstration to get a clear idea of implementation.

**Comment by ankur-kayal** [comment]
@ahampriyanshu you assigned both of them, who will work on what?

**Comment by ahampriyanshu** [comment]
Hi @ankur-kayal , you can proceed
