### ISSUE TITLE
Compound Interest

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#763]
**Submission Title**
Compound Interest

**Submission Type**
Maths_And_Stats

**Submission Description**
Compound interest is the addition of interest to the principal sum of a loan or deposit, or in other words, interest on interest. It is the result of reinvesting interest, rather than paying it out, so that interest in the next period is then earned on the principal sum plus previously accumulated interest.

**Submission Directory**
Maths_And_Stats => Statistics => Compound _Interest => Compound_Interest.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by waridrox** [comment]
Please assign the code in C++ language. I would be eager to contribute.

**Comment by waridrox** [comment]
I'm sorry but there is no Compound_Interest folder under Statistics section.

**Comment by prajwlr** [comment]
Please assign it to me. I will do it in c++

**Comment by manan288** [comment]
please assign it to me. I will do it in c++

**Comment by esheetaparulekar** [comment]
Can I contribute in Java?

**Comment by ahampriyanshu** [comment]
Hi @manan288 ,
Please opt a different language/issu :v:

**Comment by uV3301** [comment]
Hey @ahampriyanshu I had made a PR and added solutions too. Could you check that.

**Comment by brane** [comment]
I'm up for C#

**Comment by SalmonKing72** [comment]
Can I grab this in Python?

**Comment by Sayantan-world** [comment]
Can I do this in python?

**Comment by Deepak2417** [comment]
Can I solve this using JavaScript?

**Comment by CormacKrum** [comment]
Please Assign Me this Code In Python

**Comment by appsx13** [comment]
Can I do it in python?

**Comment by ahampriyanshu** [comment]
Hi @appsx13 
Please opt a different language/issue. :grin:

**Comment by kinshukdua** [comment]
Kindly assign this task to me in Typescript

**Comment by ukitta555** [comment]
I'd like to do it in JS

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by sid-1207** [comment]
Hey can you assign this issue to me?
I will solve it in C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
