### ISSUE TITLE
K-means_Clustering

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#764]
**Submission Title**
K-means_Clustering

**Submission Type**
Maths_And_Stats

**Submission Description**
k-means clustering is a method of vector quantization, originally from signal processing, that aims to partition n observations into k clusters in which each observation belongs to the cluster with the nearest mean, serving as a prototype of the cluster.

**Submission Directory**
Maths_And_Stats => Statistics => K-means_Clustering => K-means_Clustering.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Dheeraj-01** [comment]
Hi, can you assign me to this?  in java 
Thanks :) 😊

**Comment by KalyanKumar-4** [comment]
we've to write detailed explanation& program about k-means clustering?

**Comment by Mrsterius** [comment]
Hi, I can code this algorithm in Python. Please assign this issue to me.

**Comment by jayanta007** [comment]
@ahampriyanshu i will try in c++, please assign me for c++

**Comment by Mrsterius** [comment]
Submitted. Please let me know if there any changes to be made.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
