### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#77]
**Submission Title**
Array

**Submission Type**
STL

**Submission Description**
The array is a collection of elements of the same data type stored in continuous memory locations. C++ standard library contains many libraries that support the functioning of arrays.

**Contributors**
- [x]  C++ -

**Comment by Jayant-Jeet** [comment]
Please assign me this. I've read and will follow the contributing guidelines.

**Comment by KalyanKumar-4** [comment]
Finally,what we do.either implement code or any description about arrays.

**Comment by souvickroy02** [comment]
I would like to work on this issue. I can implement this in c++. I know STL well. Please allow me to work on this issue. I'll also add an explanation in my code.

**Comment by ahampriyanshu** [comment]
thanks @souvickroy02 :v:
