### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#78]
**Submission Title**
Map

**Submission Type**
STL

**Submission Description**
Maps are associative containers that store elements in a mapped fashion. Each element has a key value and a mapped value.

**Contributors**
- [x]  C++ -

**Comment by hnishal** [comment]
@ahampriyanshu assign me this, i would love to do it

**Comment by ahampriyanshu** [comment]
Great @hnishal Please mention your preffered language,

**Comment by ahampriyanshu** [comment]
thanks @hnishal and @anshupatel06 :v:
