### ISSUE TITLE
Recursion Algorithm

### ISSUE THREAD

**Issue by shadab-me** [ahampriyanshu/algo_ds_101#788]
**Submission Title**
Recursion Algorithm

**Submission Type**
Algorithm/Recursion/

**Submission Description**
Describe the Algo/Recursion

**Submission Directory**
Algorithm/Recursion/

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by atingarg1406** [comment]
I want to do this using C++. Do assign me the particular task.

**Comment by gabriel21henrique** [comment]
I would like to work on it, C# lang. Can you assign me?

**Comment by gabriel21henrique** [comment]
I would like to work on it using JavaScript. Can you assign me?

**Comment by gabriel21henrique** [comment]
Hello @shadab-me, I created the #819, could you check it out?

**Comment by chrisgithubok** [comment]
I would like to work on the ruby example. Can you assign me?

**Comment by JayavardhaniKathika** [comment]
I would like to work on Java? Can you assign me one?

**Comment by ulieckstein** [comment]
i'll do the c# file, please assign me

**Comment by ulieckstein** [comment]
sorry, i had a little error in my PR, already updated my fork. do i need to create another PR?

**Comment by abhinav-idle** [comment]
I'll do it in python, please assign me.

**Comment by GregPikitis** [comment]
I can do C++, C, Java or Python!

**Comment by Kunal2007** [comment]
I can do it in C++. Please assign it to me.

**Comment by Bhavya-Tripathi** [comment]
I would like to add a recursion algorithm in c++ or python, please assign it to me.
