### ISSUE TITLE
Set

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#79]
**Submission Title**
Set

**Submission Type**
STL

**Submission Description**
Sets are containers that store unique elements following a specific order. In a set, the value of an element also identifies it .

**Contributors**
- [x]  C++ -

**Comment by rohitbarvekar** [comment]
Hi, @ahampriyanshu . This is my first hacktoberfest. I am interested could you please assign it to me.

**Comment by geoffgeorgein** [comment]
I shall implement in python .Please assign me this. I'm a newbie to open source and would love to contribute.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @ahampriyanshu Please assign me this issue in C++

**Comment by ahampriyanshu** [comment]
thanks @Mr-Vaibhav-Shukla :v:
