### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#80]
**Submission Title**
Queue

**Submission Type**
STL

**Submission Description**
A queue is an abstract data structure that contains a collection of elements. Queue implements the FIFO mechanism

**Contributors**
- [x]  C++ -

**Comment by rahulsunil2** [comment]
I've great experience in writing [clean and readable code](https://github.com/rahulsunil2/CProgramming/blob/master/GraphTheory/layCables.c), so I would like to work on this issue.
Can you please assign it to me?

**Comment by ankitgoel25** [comment]
@ahampriyanshu I would like to work on this issue!

**Comment by chiragjagad** [comment]
I can do it in python. Can you assign it to me?

**Comment by jyotiGambhir** [comment]
Can you assign it to me? I know CPP STL pretty well

**Comment by ahampriyanshu** [comment]
Hi @chiragjagad this issue only covers STL, to implement queue in python please refer to #73

**Comment by jyotiGambhir** [comment]
> Can you assign it to me? I know CPP STL pretty well

Do I need to implement queue from scratch using some data structure like linked list or just use queue from STL? as I can see a code for queue implemented from scratch in this repo  already.

**Comment by ahampriyanshu** [comment]
thanks @jyotiGambhir and @adite39 :v:
