### ISSUE TITLE
Can I add Templates for Data Structure? 

### ISSUE THREAD

**Issue by jossiey** [ahampriyanshu/algo_ds_101#800]
**Submission Title**
Doubly Linked List

**Submission Type**
Data Structure

**Submission Description**
Using Templates to describe Data Structure with generic types 

**Submission Directory**
Data_Structures => Linked_List => Doubly_Linked_List => DoublyLinkedList_C++_Template.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
