### ISSUE TITLE
BFS

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#81]
**Submission Title**
BFS

**Submission Type**
Algorithm

**Submission Description**
Breadth first traversal or Breadth first Search is a recursive algorithm for searching all the vertices of a graph or tree data structure. 

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by abhinavjonnada82** [comment]
Can I get this?

**Comment by tdchua** [comment]
Please assign this to me - Python

**Comment by sbhavya18** [comment]
Please assign me this. I want to submit my code in c++.

**Comment by alekz7** [comment]
I want to work in the javascript implementation

**Comment by Sameera-Aryasomayajula** [comment]
Can I please take up the implementation in C.

**Comment by aanshi18** [comment]
Can I work for the java code ?

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
