### ISSUE TITLE
DFS

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#82]
**Submission Title**
DFS

**Submission Type**
Algorithm

**Submission Description**
DFS starts with a root node or a start node and then explores the adjacent nodes of the current node by going deeper into the graph or a tree. 

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by rahulsunil2** [comment]
I've great experience in writing [clean and readable code](https://github.com/rahulsunil2/CProgramming/blob/master/GraphTheory/layCables.c), so I would like to work on this issue.
Can you please assign it to me?
 I can work on Python, C and Java

**Comment by ankur-kayal** [comment]
Can i work on this in c++?

**Comment by shivamkumar123** [comment]
I would like to contribute. Please assign it to me

**Comment by alekz7** [comment]
I would like to contribute in javascript, may I've it assigned

**Comment by ahampriyanshu** [comment]
@shivamkumar123 I have already assigned @ankur-kayal in C++
Please opt a different language or issue :grin:

**Comment by OfiliPatrick** [comment]
Can I contribute to this in Python?

**Comment by ahampriyanshu** [comment]
@shivamkumar123 go ahead with C++
@OfiliPatrick go ahead with Python

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
