### ISSUE TITLE
Bellman–Ford

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#83]
**Submission Title**
Bellman–Ford

**Submission Type**
Algorithm

**Submission Description**
The Bellman–Ford algorithm is an algorithm that computes shortest paths from a single source vertex to all of the other vertices in a weighted digraph.

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ankur-kayal** [comment]
Can i work on this in c++?

**Comment by subSri** [comment]
Can i do this in Python?

**Comment by mk1107** [comment]
I want to work on this in python, c, cpp language please assign me

**Comment by CommitIt55** [comment]
@ahampriyanshu I would like to add the implementation of this algorithm in java. Thanks!

**Comment by Mezrik** [comment]
Would love to do this in JS and TS. Assign it to me, please.

**Comment by ahampriyanshu** [comment]
thnaks @everyone :v:
