### ISSUE TITLE
Count divisible pairs in an array

### ISSUE THREAD

**Issue by Mr-Vaibhav-Shukla** [ahampriyanshu/algo_ds_101#842]
**Submission Title**
Count divisible pairs in an array

**Submission Type**
Data Structures

**Submission Description**
Count pairs in the array such that one element of pair divides other.

**Submission Directory**
Data_Structures => Maps_Hash_Dict => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Aryan-dev007** [comment]
I would love to contribute to this!
Preferring C, C++ and Python
Please Assign it to me.

**Comment by Abhicoder03** [comment]
Hi @Mr-Vaibhav-Shukla I would like to work on this.

**Comment by ahampriyanshu** [comment]
> I would love to contribute to this!
> Preferring C, C++ and Python, also Rust if needed.
> Please Assign it to me.

Great :clap: :clap:

**Comment by Upasana9** [comment]
I will love to contribute preferring C++. Please assign it to me.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @Upasana9 Please opt any different language.

**Comment by CormacKrum** [comment]
Please Assign Me this Code in Java

**Comment by Divyessh** [comment]
I also want to contribute in Python

**Comment by GregPikitis** [comment]
I would like to contribute! C, C++, Java or Python are fine with me

**Comment by parth93QA** [comment]
please assign me the GOlang one

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by SusnatoPrime007** [comment]
Please assign me the Javascript one.

**Comment by Rudransh24** [comment]
Hello! Can you please assign this to me in C, C++ or python??

**Comment by Athi223** [comment]
Pr submitted for Javascript version, please check

**Comment by phast184** [comment]
Hi can you please assign this to me the JavaScript version!

**Comment by phast184** [comment]
> Hi can you please assign this to me the JavaScript version!

I have made a PR here, please check https://github.com/ahampriyanshu/algo_ds_101/pull/1202

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
