### ISSUE TITLE
Mode Function (Statistics) - Python

### ISSUE THREAD

**Issue by a-r-1** [ahampriyanshu/algo_ds_101#843]
**Submission Title**
Mode Average

**Submission Type**
Maths_And_Stats

**Submission Description**
Algo takes input of a dataset and finds the mode or modes (if there are multiple). 

**Submission Directory**
algo_ds_101 => Maths_And_Stats => Statistics => Mode => mode.py

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
