### ISSUE TITLE
Verticle sum of Binary Tree

### ISSUE THREAD

**Issue by Mr-Vaibhav-Shukla** [ahampriyanshu/algo_ds_101#845]
**Submission Title**
Verticle sum of Binary Tree

**Submission Type**
Data Structure

**Submission Description**
Find the vertical sum of the nodes that are in the same vertical line in Binary tree.

**Submission Directory**
 Data_Structures => Maps_Hash_Dict => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sakshi-negi123** [comment]
i would like to work on it

**Comment by Amulya-coder** [comment]
I wants to work on C++.

**Comment by Mr-Vaibhav-Shukla** [comment]
Hi @sakshi-negi123 Please opt a language

**Comment by sakshi-negi123** [comment]
@Mr-Vaibhav-Shukla  i want to work  on  c++

**Comment by Sanika1999** [comment]
Can I do this for java?

**Comment by deepanshuoct12** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by SusnatoPrime007** [comment]
I would like to do work on this on C,please assign this to me

**Comment by AnjaliBhuva** [comment]
I would to like to do it in python, can u plz assign it to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
