### ISSUE TITLE
Cuckoo Hashing

### ISSUE THREAD

**Issue by Mr-Vaibhav-Shukla** [ahampriyanshu/algo_ds_101#846]
**Submission Title**
Cuckoo Hashing

**Submission Type**
Data Structure

**Submission Description**
Cuckoo hashing applies the idea of multiple-choice and relocation together and guarantees O(1) worst case lookup time.

**Submission Directory**
 Data_Structures => Maps_Hash_Dict => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Deepak2417** [comment]
Please assign me for C++.

**Comment by chinmaym07** [comment]
Please assign me for java.

**Comment by Kadermiyanyedi** [comment]
Please assign me for python

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
