### ISSUE TITLE
Amicable Numbers

### ISSUE THREAD

**Issue by Mr-Vaibhav-Shukla** [ahampriyanshu/algo_ds_101#847]
**Submission Title**
Amicable Numbers

**Submission Type**
Data Structure

**Submission Description**
Two numbers are amicable if the first is equal to the sum of divisors of the second, and if the second number is equal to the sum of divisors of the first.

**Submission Directory**
 Data_Structures => Maps_Hash_Dict => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by Deepak2417** [comment]
Can I also write code using C++ or Java?

**Comment by Mr-Destructive** [comment]
can I do this in C and C++?

**Comment by ahampriyanshu** [comment]
Hi @Mr-Destructive :wave:  go ahead with C and C++.
Hi @Deepak2417 :wave:  go ahead with java.

**Comment by shadab-me** [comment]
I am working on JavaScript assign to me.

**Comment by tomasloksa** [comment]
doing this in Typescript ^^

**Comment by jkendall327** [comment]
Hi, I'd like to submit a C# version. Thank you.

**Comment by itIsBrando** [comment]
I can get JavaScript

**Comment by Kadermiyanyedi** [comment]
I am working on Golang assign to me please

**Comment by Kadermiyanyedi** [comment]
I am working on TypeScript assign to me.

**Comment by marioa98** [comment]
I would like to implement it using Ruby

**Comment by Kartik-byte** [comment]
Hey I would like to do this in PHP, can you please assign me to it. 
Thank you.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
