### ISSUE TITLE
Recaman’s sequence

### ISSUE THREAD

**Issue by Mr-Vaibhav-Shukla** [ahampriyanshu/algo_ds_101#848]
**Submission Title**
Recaman’s sequence

**Submission Type**
Data Structure

**Submission Description**
It is basically a function with domain and co-domain as natural numbers and 0.

**Submission Directory**
 Data_Structures => Maps_Hash_Dict => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by gokulkannan7** [comment]
@Mr-Vaibhav-Shukla can I solve this question in c++?

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by Deepak2417** [comment]
I can solve this using Java. Kindly assign this to me.

**Comment by chinmaym07** [comment]
Can you assign this to me in C.

**Comment by aanneettgg** [comment]
id like do this in C#

**Comment by tomasloksa** [comment]
Doing this in Typescript ^^

**Comment by rebelfire888** [comment]
please assign it to me in C

**Comment by Rudransh24** [comment]
Hello! Can you please assign this to me in C, C++ ??

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
