### ISSUE TITLE
Kruskal's MST

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#85]
**Submission Title**
Kruskal's MST

**Submission Type**
Algorithm

**Submission Description**
Kruskal's algorithm finds a minimum spanning forest of an undirected edge-weighted graph. If the graph is connected, it finds a minimum spanning tree.

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by LDiazN** [comment]
I can do it in C++, assign it to me

**Comment by rohitbarvekar** [comment]
Hi, @ahampriyanshu . This is my first hacktoberfest request. I am interested in doing it in cpp. Could you please assign it to me.

**Comment by mrselukar** [comment]
Hey! Would be happy to do this in Python.

**Comment by ahampriyanshu** [comment]
Hello @rohitbarvekar , I have already assigned @LDiazN in C++
Please opt a different language or issue

**Comment by souvickroy02** [comment]
I would like to work on this issue. I can implement quicksort in c++, c and python also. Please allow me to work on this issue. I'll also add an explanation in my code.

**Comment by rahulsunil2** [comment]
I've already started working on C. Can you assign that to me?

**Comment by dinijian** [comment]
Hello @ahampriyanshu, I want to contribute to this issue. I will implement Kruskal's algorithm in C++. Please assign it to me.

**Comment by cuber485** [comment]
@ahampriyanshu ,  I would like to implement this in JAVA.

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
