### ISSUE TITLE
Largest Sum Contiguous Subarray (Kadane’s Algorithm)

### ISSUE THREAD

**Issue by Upasana9** [ahampriyanshu/algo_ds_101#852]
**Submission Title**
Largest Sum Contiguous Subarray

**Submission Type**
Algorithm

**Submission Description**
Program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Submission Directory**
Algorithm => Dynamic_Programming =>Largest_Sum_Contiguous_Subarray=> ... => LSCS.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by guygreenleaf** [comment]
Hello, 

Not sure what this issue is asking. The title leads me to believe the problem is to find the largest contiguous subarray.  
I can handle this recursively in C++ if you'd like to assign me to it.

**Comment by Nirali0029** [comment]
I would like to do this for python.

**Comment by guygreenleaf** [comment]
Hello, can you please add the Largest_Sum_Contiguous_Subarray folder inside the Dynamic Programming folder so I can submit a PR? 

Thanks!

**Comment by p-davide** [comment]
I'd like to do this in C.

**Comment by Arsenic-ATG** [comment]
I would like to do this for Swift.

**Comment by chinmaym07** [comment]
Please assign this to me in java.

**Comment by keshari777** [comment]
I would like to contribute to java

**Comment by Kishore-abhimanyu** [comment]
I would like to work on it. Can you please assign me to this?

**Comment by varad64** [comment]
I would like to work on it using Java. Could you please assign it to me?

**Comment by shadab-me** [comment]
Done In JavaScript.

**Comment by Kunal2007** [comment]
I would like to do it with C++. Please assign it to me.

**Comment by hello-fri-end** [comment]
I implemented it in C++

**Comment by hello-fri-end** [comment]
@Vimlesh-Kumar :Already done. I have submitted a pull request as well.

**Comment by hello-fri-end** [comment]
@Vimlesh-Kumar : Is there any issue with my implementation? Why wasn't it merged?

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by Rudransh24** [comment]
Hello! Can you please assign this to me in C??

**Comment by rgarg-2711** [comment]
can you please assign this to me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
