### ISSUE TITLE
More Haskell Programs

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#859]
**Submission Title**
:bangbang: Help Needed :bangbang:

**Submission Type**
Algorithm + Data Structure + STL + Maths_And_Stats + Resources

**Submission Description**
Implement all the existing programs in ``haskell`` 

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.hs/lhs

**Important**

- Don't wait to get assigned :no_entry_sign: 
- Just create the PR :heavy_check_mark: 
- If a PR for a specific algo/ds has already been opened, kindly opt a different program.There are plenty of them :grin:
- Push the program in the appropriate directory
- Please do not **spam** or create **duplicate** PR :warning:

**Comment by Dkgiri619** [comment]
@ahampriyanshu I have submitted few of haskell codes that i could write. Please find my PR and accept if you find it useful.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
