### ISSUE TITLE
LIS

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#86]
**Submission Title**
LIS

**Submission Type**
Algorithmal

**Submission Description**
Longest increasing subsequence problem is to find a subsequence of a given sequence in which the subsequence's elements are in sorted order, lowest to highest, and in which the subsequence is as long as possible.

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by ankur-kayal** [comment]
Can i work on this issue in c++?

**Comment by 5H1V** [comment]
Hello, I would like to work on this issues in Java

**Comment by Sayantan-world** [comment]
Can you assign this to me in python?

**Comment by ankur-kayal** [comment]
@ahampriyanshu Pull request added 👍

**Comment by jyotiGambhir** [comment]
Can you assign this issue to me? I would like to work in CPP.

**Comment by saurabh80521** [comment]
@ahampriyanshu .can you assign this issue to me..i ll work on this in C.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
