### ISSUE TITLE
More Clojure Programs

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#863]
**Submission Title**
:bangbang: Help Needed :bangbang:

**Submission Type**
Algorithm + Data Structure + STL + Maths_And_Stats + Resources

**Submission Description**
Implement all the existing programs in ``clojure`` 

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.clj/cljs

**Important**

- Don't wait to get assigned :no_entry_sign: 
- Just create the PR :heavy_check_mark: 
- If a PR for a specific algo/ds has already been opened, kindly opt a different program.There are plenty of them :grin:
- Push the program in the appropriate directory
- Please do not **spam** or create **duplicate** PR :warning:

**Comment by ferdinandjason** [comment]
Hi @ahampriyanshu I've raised PR to add Clojure version of the Fibonacci number

**Comment by davidlevinwork** [comment]
Hi
If i want to create a new topic folder under 
algo_ds_101/Algorithms/Search_Algorithms/
how can i do it?

I want to implement an algo cols SELECT (find the k number in unsorted array in O(n))

**Comment by harshita-sharma11** [comment]
Please make the required changes according to the new rules of hacktober.

**Comment by ahampriyanshu** [comment]
> Please make the required changes according to the new rules of hacktober.

And what are those ??

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
