### ISSUE TITLE
Ternary Search

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#87]
**Submission Title**
Ternary Search

**Submission Type**
Algorithm

**Submission Description**
A ternary search algorithm is a technique in computer science for finding the minimum or maximum of a unimodal function.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by vortex2099** [comment]
assign me this problem.

**Comment by hnishal** [comment]
@ahampriyanshu i can do this in cpp
assign it to me

**Comment by pranjalkumar153** [comment]
Assign this problem to me.

**Comment by ahampriyanshu** [comment]
Please mention your prefferd language @vortex2099 and @pranjalkumar153 😁

**Comment by pranjalkumar153** [comment]
I would like to use C++. I can also do the same contribution in Python as well.

**Comment by pranjalkumar153** [comment]
I will also explain the code properly with comments.

**Comment by ahampriyanshu** [comment]
@pranjalkumar153 go ahead with C++,Python,Java and JS

**Comment by pranjalkumar153** [comment]
Thanks sir.

**Comment by Sameera-Aryasomayajula** [comment]
Can I contribute the solution in C and C++

**Comment by mk1107** [comment]
I want to work on this in python and cpp language please assign me

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
