### ISSUE TITLE
Remove Items from duplicates Array 

### ISSUE THREAD

**Issue by shadab-me** [ahampriyanshu/algo_ds_101#875]
**Submission Title**
Bubble Sort/AVL Graph/Vector

**Submission Type**
Algorithm/Data Structure/Array/

**Submission Description**
Describe the Algo/DS

**Submission Directory**
Algorithm => Data Structure => ... => ... => Filename.extension

**Contributors**

- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by Arsenic-ATG** [comment]
hi @shadab-me , I would like to work on this issue and can provide the answer in swift , python and C++. If you allow, I may start my work on this issue

**Comment by ShehzadAhm** [comment]
Hi @shadab-me, can I work on this issue?

**Comment by PrathamesR** [comment]
I can resolve this issue using C# and java, assign me if I should start

**Comment by shadab-me** [comment]
I am working on JavaScript. Assign me

**Comment by ahampriyanshu** [comment]
Invalid Issue :warning:
