### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#88]
**Submission Title**
Heap Sort

**Submission Type**
Algorithm

**Submission Description**
Heap Sort is a popular and efficient sorting algorithm in computer programming. Learning how to write the heap sort algorithm requires knowledge of two types of data structures - arrays and trees. 

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [x] Ruby -
- [ ] Scala -

**Comment by Namanmittal0007** [comment]
@ahampriyanshu I would like to contribute to this, please assign me this task to implement Heap sort in C++.

**Comment by ankur-kayal** [comment]
Can i work on this in python3?

**Comment by sbhavya18** [comment]
Please assign me this. I would like to implement this in c++.

**Comment by ahampriyanshu** [comment]
> Please assign me this. I would like to implement this in c++.

@sbhavya18 I have already assigned @Namanmittal0007 in C++ language
Please opt a different language ✌🏽

**Comment by souvickroy02** [comment]
I would like to work on this issue. I can implement heapsort in c++. Please allow me to work on this issue. I'll also add an explanation in my code.

**Comment by sbhavya18** [comment]
> > Please assign me this. I would like to implement this in c++.
> 
> @sbhavya18 I have already assigned @Namanmittal0007 in C++ language
> Please opt a different language ✌🏽

I can implement it in C language. Can u now assign me the task?

**Comment by souvickroy02** [comment]
I can implement this issue in C language.

**Comment by Anjali2001saxena** [comment]
I can contribute towards this issue in java. Please assign me this.

**Comment by subham5230** [comment]
I can contribute to this issue in javascript, please assign me.

**Comment by ankur-kayal** [comment]
@ahampriyanshu Pull Request added 👍

**Comment by Rajwrita** [comment]
I can contribute in Ruby.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
