### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#89]
**Submission Title**
Selection Sort

**Submission Type**
Algorithm

**Submission Description**
Selection sort is a simple sorting algorithm. This sorting algorithm is an in-place comparison-based algorithm in which the list is divided into two parts, the sorted part at the left end and the unsorted part at the right end.

**Contributors**
- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [x] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by Namanmittal0007** [comment]
@ahampriyanshu I would like to contribute to this, please assign me this task to implement selection sort in c++.

**Comment by italovinicius18** [comment]
Hello, I would like to implement Selection Sort in Python

**Comment by 5H1V** [comment]
Hello, I would like to work on implementing Selection Sort in Java

**Comment by architgarg603** [comment]
I would like to code in java

**Comment by sbhavya18** [comment]
I would like to code in C. Kindly assign me this.

**Comment by Sayantan-world** [comment]
I will like to code it in python

**Comment by SoundaryaKhanapur** [comment]
> **Submission Title**
> Selection Sort
> 
> **Submission Type**
> Algorithm
> 
> **Submission Description**
> Selection sort is a simple sorting algorithm. This sorting algorithm is an in-place comparison-based algorithm in which the list is divided into two parts, the sorted part at the left end and the unsorted part at the right end.
> 
> **Contributors**
> 
> * [x]   C++ -
> * [x]   C -
> * [x]   Python -
> * [x]  Java -
> * [ ]  JavaScript -
> * [ ]  TypeScript -
> * [ ]  Golang -
> * [ ]  Ruby -
> * [ ]  Scala -

**Comment by Wekananda** [comment]
Hello, i would like to code in javascript. Thanks

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
