### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#90]
**Submission Title**
Insertion Sort

**Submission Type**
Algorithm

**Submission Description**
Insertion sort is a simple sorting algorithm that works similar to the way you sort playing cards in your hands. The array is virtually split into a sorted and an unsorted part.

**Contributors**
- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] Scala -

**Comment by Namanmittal0007** [comment]
@ahampriyanshu I would like to contribute to this, please assign me this task to implement Insertion sort in C++.

**Comment by italovinicius18** [comment]
Hello, I would like to implement Insertion Sort in Python

**Comment by deepdhar** [comment]
@ahampriyanshu I would like to work on this issue in C, please assign me the task.

**Comment by Carolis** [comment]
Hey I would like to implement Insertion Sort with JavaScript =)

**Comment by krishnmohan19** [comment]
Hey @ahampriyanshu  i would like to work on this issue with javascript. would you please assign me this

**Comment by architgarg603** [comment]
I would like to do it in Java

**Comment by souvickroy02** [comment]
I would like to work on this issue. I can implement insertion sort in c++. Please allow me to work on this issue. I'll also add an explanation in my code.

**Comment by aanshi18** [comment]
Hi @ahampriyanshu , I would like to work for code in c

**Comment by dinijian** [comment]
I would like to contribute to this issue. Please assign me this task. I will do it in C++.

**Comment by satyamasthanaa** [comment]
I would like to contribute on this issue, please allow me work on this task to implement Insertion sort in Python

**Comment by Pacifier25** [comment]
can i do this in c++

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
