### ISSUE TITLE
Generate Brackets code in c++

### ISSUE THREAD

**Issue by sharannyobasu** [ahampriyanshu/algo_ds_101#901]
**Submission Title**
Balanced Parentheses (Recursion)

**Submission Type**
Data Structure/Recursion

**Submission Description**
Describe the Algo/DS/STL

**Submission Directory**
Data_Structures => Recursion => BalancedParentheses.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sharannyobasu** [comment]
Pull request at #904

**Comment by purnima11-igdtu** [comment]
can u assign me this ? i can do with stacks in c++
