### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by ahampriyanshu** [ahampriyanshu/algo_ds_101#91]
**Submission Title**
Quick Sort

**Submission Type**
Algorithm

**Submission Description**
Quick Sort is a sorting algo based on the concept of Divide and Conquer

**Contributors**
- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [x] Golang -
- [ ] Ruby -
- [x] Scala -

**Comment by Namanmittal0007** [comment]
@ahampriyanshu I would like to contribute to this, please assign me this task to implement Quick sort in C++.

**Comment by LuisFerTR** [comment]
I would like to work on this implementing quicksort in golang

**Comment by italovinicius18** [comment]
Hello, I would like to implement Quick Sort in Python

**Comment by 5H1V** [comment]
Hello, I would like to work on implementing Quick Sort in Java

**Comment by hanyangl** [comment]
@ahampriyanshu could you assign Quick Sort in JavaScript to me?

**Comment by Chemasmas** [comment]
@ahampriyanshu Can i make the Scala Version?

**Comment by tdchua** [comment]
Please assign this to me - Python

**Comment by GhostUser** [comment]
I would like to work on this using python, I'll also add the explanation there. I assure that work would be top-notch.

**Comment by souvickroy02** [comment]
I would like to work on this issue. I can implement quicksort in c++. Please allow me to work on this issue.

**Comment by geoffgeorgein** [comment]
I like coding in python and would love to implement it in python.Please assign me this.

**Comment by Nirali0029** [comment]
I would like to make contributions in python. Please assign it to me

**Comment by GhostUser** [comment]
I have also did a Pull Request for quick sort. Check it and merge @ahampriyanshu

**Comment by GhostUser** [comment]
@ahampriyanshu sorry I mentioned the PR.
#141 
confirm pls.

**Comment by hanyangl** [comment]
@ahampriyanshu finished QuickSort in JS https://github.com/ahampriyanshu/algo_ds_101/pull/155. For review, and happy hacktoberfest!

**Comment by ahampriyanshu** [comment]
thanks @everyone :v:
