### ISSUE TITLE
Generic Deque Implementation

### ISSUE THREAD

**Issue by divyadreddy** [ahampriyanshu/algo_ds_101#911]
**Submission Title**
Generic Deque Implementation

**Submission Type**
Data Structures

**Submission Description**
Implementation of Deque STL 

**Submission Directory**
Data Structures=>Deque

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by divyadreddy** [comment]
I am working on this

**Comment by CormacKrum** [comment]
Please Assign me this In Java or C++

**Comment by ShreyasNanaware** [comment]
I want to work on this issue in Python

**Comment by nayanika0208** [comment]
Can i do this in c++??

**Comment by hello-fri-end** [comment]
I'd like to work on this. Can you please assign it to me?

**Comment by Manas502** [comment]
Can I implement the C language version?

**Comment by duttabhishek32** [comment]
Hey there, I can implement it in C. Can you assign me this for C Language ?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
