### ISSUE TITLE
Djikstra on a custom graph using leftist heap C++

### ISSUE THREAD

**Issue by KPsychO** [ahampriyanshu/algo_ds_101#920]
**Submission Title**
Dijkstra using LeftistHeap

**Submission Type**
Algorithm

**Submission Description**
Dijkstra on leftist heap

**Submission Directory**
Algorithms => Graph => Dijkstra => Filename.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by guygreenleaf** [comment]
Hi,
I can submit a solution for this in C++ if you'd like to assign me. 

Cheers!

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
