### ISSUE TITLE
Minimum sum descent in C

### ISSUE THREAD

**Issue by choijean** [ahampriyanshu/algo_ds_101#940]
**Submission Title**
Minimum Sum Descent

**Submission Type**
Algorithm

**Submission Description**
Some positive integers are arranged in an equilateral triangle with n numbers in it's base like the one show below:
```
                 -2-
           -5-        4
     -1-        4          7
  8       -6-        9         6
```

This algorithm determines the smallest sum in a descent from the triangle apex to its base through a series of adjacent numbers (shown in the figure by dashes)

**Submission Directory**
Algorithms/Dynamic_Programming/Minimum_Sum_Descent/minsum.c

**Contributors**
Jean Choi

- [ ]  C++ -
- [x]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [x] C# -

**Comment by gabriel21henrique** [comment]
I would like to work on this using C#. Can you assign me?

**Comment by soorya54** [comment]
I would like to solve this. Can you assign it to me?

**Comment by joy2306** [comment]
is this issue still open , then i want to try for python, can you assign it to me?

**Comment by hello-fri-end** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by DEVinicius** [comment]
I would like to work on this in PHP. Can you please assign it to me?

**Comment by SUJATA19-could** [comment]
I would like to work on this in C++

**Comment by AdamPlaskitt** [comment]
I would like to work on this in java. Can you please assign it to me?

**Comment by GerardoUbuntu** [comment]
I would like to work on this in TypeScript

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
