### ISSUE TITLE
Sramble String/Dynamic Programming

### ISSUE THREAD

**Issue by ricky1812** [ahampriyanshu/algo_ds_101#942]
**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
Describe the Algo/DS/STL

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**

- [x]  C++ -
- [x]  C -
- [ ]  Python -
- [x] Java - 
- [x] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by ricky1812** [comment]
I want to work on this issue.

**Comment by Vimlesh-Kumar** [comment]
> I want to work on this issue.

In which language

**Comment by sushant19-99** [comment]
Would like to work on this assignment using Java, kindly assign it.

**Comment by KritiGandotra** [comment]
Hey there!
I would like to contribute using C++ language. Kindly assign me some work. Thank you!

**Comment by deepanshuoct12** [comment]
I want to work on this issue using c++

**Comment by svashish305** [comment]
i want to work on this issue using c++

**Comment by deepanshuoct12** [comment]
what we have to do in this issue?

**Comment by rishitsaraf** [comment]
I want to work on this issue using c++ please.

**Comment by Riddhima23** [comment]
Hello!I would like to work on this using c++

**Comment by illusionrs** [comment]
I want to work on java. Please assign issue

**Comment by Mayankjha997** [comment]
I Want to work on c language . I want to add rock paper and scissor game. Please assign me

**Comment by SusnatoPrime007** [comment]
I want to work on stack in c,please assign me in this

**Comment by kritika2311** [comment]
I want to work on java ,please assign me some task.

**Comment by shivam3310** [comment]
I want to work on this issue in CPP. Kindly assign. Thankyou!

**Comment by Kartikey246** [comment]
I want to work on this issue in c++

**Comment by dheerajpoonia29** [comment]
I want to work on this issue in Javascript, I request to assign me work

**Comment by meteora2002** [comment]
Hey there!
I would like to contribute using C++ language. Kindly assign me some work. Thank you!Hey there!

**Comment by manthan2501** [comment]
I would like to work on this issue in C++. kindly assign me this work.

**Comment by foulcommander** [comment]
I want to contribute using c++ .

**Comment by tusharfc** [comment]
Hey there!
I would like to contribute using C++ language. Kindly assign me some work.

**Comment by kevinNdyabandiho** [comment]
i would like to assist using java

**Comment by Himanshu2500** [comment]
I want to contribute using c++

**Comment by meteora2002** [comment]
i would like to contribute in python

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
