### ISSUE TITLE
PigeonholeSort

### ISSUE THREAD

**Issue by shruti512** [ahampriyanshu/algo_ds_101#964]
**Submission Title**
PigeonholeSort

**Submission Type**
Algorithm

**Contributors**

- [X]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by chinmaym07** [comment]
Please assign me this for java & C.

**Comment by GerardoUbuntu** [comment]
I want to implement this TypeScript

**Comment by deepanshuoct12** [comment]
please assign me this issue, I will do it in C++

**Comment by Nirali0029** [comment]
Please assign this to me for python

**Comment by shruti512** [comment]
> please assign me this issue, I will do it in C++

That already exists

**Comment by Utkarshn10** [comment]
@shruti512 I would like to code it in Java.

**Comment by sarthak-21** [comment]
Please assign me this issue, I will do it in C

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
