### ISSUE TITLE
B Tree

### ISSUE THREAD

**Issue by rohg007** [ahampriyanshu/algo_ds_101#980]
**Submission Title**
B-Tree
**Submission Type**
Data Structure

**Submission Description**
Implementation of BTree DS. BTree is a DS that supports operations in O(log N) time and all the leaves are at the same level. It is memory efficient. 

**Submission Directory**
Main_Folder => Data_Structures => Tree => BTree.cpp
**Contributors**

- [X]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by vartika-arora** [comment]
I would like to take this issue up in Python.

**Comment by deepanshuoct12** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by belphegor-s** [comment]
I would like to work on this on C++

**Comment by SUJATA19-could** [comment]
hey! can i work on this in C

**Comment by Nirali0029** [comment]
Can you please assign this to me in python

**Comment by gautam08** [comment]
I would like to work on it in JAVA.Please assign me.

**Comment by kcirym10** [comment]
May I implement this in C++?

**Comment by shresth12-jain** [comment]
I would like to contribute to this by implementing Btree using C++.

**Comment by betsystevens** [comment]
Hi! I would like to do this in JavaScript. Can you please assign it to me? Thank You!

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
