### ISSUE TITLE
Extended Euclidean Algorithm for GCD & Multiplicative Inverse

### ISSUE THREAD

**Issue by agsanskar15** [ahampriyanshu/algo_ds_101#988]
**Submission Title**
Extended Euclidean Algorithm

**Submission Type**
Maths_And_Stats/Number Theory

**Submission Description**
Extended Euclidean Algorithm for finding the GCD and the modular multiplicative inverse.

**Submission Directory**
Main_Folder => Maths_And_Stats => Number Theory => Extended Euclidean Algorithm => extendEuclid.cpp

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by agsanskar15** [comment]
Hi there! Please assign this to me I will be using C++.

**Comment by aish0007** [comment]
Please assign to me i will use python3

**Comment by Addhyay** [comment]
Please assign this to me, I'll code in Python3

**Comment by abhinav-idle** [comment]
I would like to work on this in java.
Kindly assign it to me.

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
