### ISSUE TITLE
Priority Queue

### ISSUE THREAD

**Issue by sark-2110** [ahampriyanshu/algo_ds_101#994]
**Submission Title**
Priority Queue

**Submission Type**
Data Structure

**Submission Description**
Priority queues are a type of container adaptors, specifically designed such that its first element is always the greatest of the elements it contains, according to some strict weak ordering criterion.

This context is similar to a heap, where elements can be inserted at any moment, and only the max heap element can be retrieved (the one at the top in the priority queue).

Priority queues are implemented as container adaptors, which are classes that use an encapsulated object of a specific container class as its underlying container, providing a specific set of member functions to access its elements. Elements are popped from the "back" of the specific container, which is known as the top of the priority queue.

**Submission Directory**
Main_Folder => Data_Structures => Queues=> Priority Queue => priorityQueue.cpp

**Contributors**

- [x]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by sark-2110** [comment]
Can you please assign me this issue? Thanks.

**Comment by ukitta555** [comment]
I will go for Java and JS

**Comment by SOURAB-BAPPA** [comment]
i want to solve this program using python language

**Comment by Digislaw** [comment]
I'd like to make it in C#.

**Comment by Digislaw** [comment]
I'd like to implement it in JS.

**Comment by Zaman3027** [comment]
I would like do it in C++ please assign this to me

**Comment by Zaman3027** [comment]
I would like to do it in type Script please assign this to me

**Comment by Rohanfizz** [comment]
I can implement priority queue in cpp please assign this to me 
Peace :)

**Comment by Manas502** [comment]
Can I work on it in C ?

**Comment by aniket173000** [comment]
Hi , could you please assign me this issue , I can implement it in c++.

**Comment by Digislaw** [comment]
@Rohanfizz & @aniket173000 
C++ implementation [already exists](https://github.com/ahampriyanshu/algo_ds_101/blob/master/Data_Structures/Queues/Priority%20Queues/priorityQueue.cpp).

**Comment by Aarti002** [comment]
Can i  take this issue? I would do this problem using python language.

**Comment by sid-1207** [comment]
Hey can you assign me this issue? 
I would solve it in C

**Comment by Aarti002** [comment]
Thank you sir for assigning this task to me:)

**Comment by sid-1207** [comment]
Thanks for assigning 
I have resolved the issue
