### ISSUE TITLE
MOS Algorithm

### ISSUE THREAD

**Issue by aish0007** [ahampriyanshu/algo_ds_101#997]
**Submission Title**
Mos algo

**Submission Type**
Algorithm/Data Structure/STL/Maths_And_Stats

**Submission Description**
Mos algorithm is widely used for decreasing complexity in query base problems but it needs to be in every language
**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by aish0007** [comment]
Can i do it in c++ or python

**Comment by SOURAB-BAPPA** [comment]
i want to program this issue in c and python
if you say also in c++ and go

**Comment by gabriel21henrique** [comment]
I'd like to work on this using C, can you assign me?

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
